### ISSUE TITLE
Release 1.0.0-beta.50 is broken with Search Index Generation enabled

### ISSUE THREAD

**Issue by atiq-cs** [statiqdev/Statiq#1001]
Release 1.0.0-beta.50, 21c63eb fails on `dotnet run`

In output we get,

    [INFO] <- Redirects/Output » Finished Redirects Output phase execution (0 output document(s), 2 ms)
    [ERRO] SearchIndex/PostProcess » ExecuteIf » ExecuteConfig » Value cannot be null. (Parameter 'scriptPath')
    [INFO] <- Sitemap/PostProcess » Finished Sitemap PostProcess phase execution (1 output document(s), 5 ms)
    [INFO] -> Sitemap/Output » Starting Sitemap Output phase execution... (1 input document(s), 1 module(s))

    [INFO] - Engine Execution in 4113 ms
    [CRIT] Value cannot be null. (Parameter 'scriptPath')
    [INFO] To get more detailed logging output run with the "-l Debug" flag

Looks like the issue is,

> Value cannot be null. (Parameter 'scriptPath')  

\* `GenerateSearchIndex: true` is set for this run.

**Comment by daveaglick** [comment]
Well that's not good. Though it does make me wonder how all my test suites passed locally since they would have been running the same code. One way or the other I'll get a patch out today (either a fix or revert).

**Comment by daveaglick** [comment]
Okay, I can repro in a unit test now - the problem with my tests was that I actually wasn't opting into search index generation in any of them! It can be a challenge to cover every possible scenario in a big project like this. Fixing it now (with tests for the future) so I'll have a patch out shortly.

**Comment by daveaglick** [comment]
A new release is out.
