### ISSUE TITLE
install pptx

### ISSUE THREAD

**Issue by ryaaa-yay** [statiqdev/Statiq#1017]
I want to let my python automatically create a pptx, but it shows syntax error when I try to install pptx, I have tried both conda and pip, but they all show this error

runfile('/Users/katherinexia/.spyder-py3/untitled1.py', wdir='/Users/katherinexia/.spyder-py3')
  File <unknown>:1
    pip install aspose.slides
        ^
SyntaxError: invalid syntax

runfile('/Users/katherinexia/.spyder-py3/untitled1.py', wdir='/Users/katherinexia/.spyder-py3')
  File <unknown>:1
    pip install python-pptx==0.5.5
        ^
SyntaxError: invalid syntax

runfile('/Users/katherinexia/.spyder-py3/untitled1.py', wdir='/Users/katherinexia/.spyder-py3')
  File <unknown>:1
    conda install -c conda-forge python-pptx

**Comment by girlpunk** [comment]
It appears the function you are running (`runfile`) requires a python script, not a shell script. As both pip and conda are standard executables and not valid python, you are receiving an error indicating that.

**Comment by daveaglick** [comment]
Agreed - closing this as it doesn't appear to be Statiq related at all.
