### ISSUE TITLE
NSubstitute mockups for Wyam.Common interfaces

### ISSUE THREAD

**Issue by dodyg** [statiqdev/Statiq#105]
Let's create a project with just Mockups for the standard interfaces at `Wyam.Common`

I find myself writing a lot of boring and brittle mockups for testing modules.

```

        IExecutionContext GetExecutionContext()
        {
            IExecutionContext context = Substitute.For<IExecutionContext>();
            context.GetNewDocument(Arg.Any<string>(), Arg.Any<string>(), Arg.Any<IEnumerable<KeyValuePair<string, object>>>())
            .Returns(x =>
            {

                IDocument res = Substitute.For<IDocument>();
                res.Source.Returns((string)x[0]);
                res.Content.Returns((string)x[1]);

                var metadata = (IEnumerable<KeyValuePair<string, object>>)x[2];
                res.Metadata.Count.Returns(metadata.Count());

                return res;
            });

            context.GetNewDocument(Arg.Any<string>(), Arg.Any<IEnumerable<KeyValuePair<string, object>>>())
            .Returns(x =>
            {

                IDocument res = Substitute.For<IDocument>();
                res.Content.Returns((string)x[0]);

                var metadata = (IEnumerable<KeyValuePair<string, object>>)x[1];
                res.Metadata.Count.Returns(metadata.Count());

                return res;
            });

            return context;
        }
```

**Comment by daveaglick** [comment]
I agree that the mocks are tedious and annoying, but the thing that's kept me from doing something like this is not knowing what behavior should be implemented for each test class. It seems like that would be rather specific to the test being performed. I.e., do I want to return something for `IDocument.Content`, or `IDocument.GetStream()`, or both? Mocking is a nice way to only provide implementations for methods and properties that you need for that test.

Any ideas on what sort of test class(es) would make this easier. For example, if we create an `IDocument` test implementation, what should it's behavior be?

**Comment by dodyg** [comment]
hmm..yeah you are right. Let me rethink this.

**Comment by daveaglick** [comment]
Note that there is now a Wyam.Testing library and it has a complete in-memory testing implementation of the new file system abstraction.

**Comment by daveaglick** [comment]
Wyam.Testing has a number of implementations for the most common interfaces and continues to add new mocks as needed, so I think we can consider this issue resolved.
