### ISSUE TITLE
CopyFiles module not working correctly when copying subfolders

### ISSUE THREAD

**Issue by reliak** [statiqdev/Statiq#115]
I have a use case with the following folders:
- input
  - assets
    - js
- output

Now I was trying to copy the assets folder to the output folder with:
`CopyFiles("assets/*.*")`
I was expecting to get something like "output/assets/js" etc. but the files from assets were copied directly to the output folder.

I will soon submit a PR to fix this.

**Comment by daveaglick** [comment]
Resolved by #116
