### ISSUE TITLE
Improve writing files that there were not loaded from ReadFiles module

### ISSUE THREAD

**Issue by reliak** [statiqdev/Statiq#117]
I have this issue for example when creating non existing files and writing them through `WriteFiles` module.
As far as I understand the module correctly, I would need to do the following:

```
Pipelines.Add("Test",
  ModuleThatCreatesSomeContent(), // only a single document, for example sitemap.xml
  WriteFiles( (doc,ctx) => "sitemap.xml").UseWriteMetadata(false)
);
```

Or is there an easier way?
If not, maybe we could add a fluent method or something like that to handle this case?

**Comment by daveaglick** [comment]
Yep, that looks right for what you need to do today. You don't need the `UseWriteMetadata()` call if your documents don't have "WritePath" or similar metadata, but yeah, it's not ideal. What if we added a `useWriteMetadata` flag to the constructor as well? Would that improve it?

**Comment by reliak** [comment]
> You don't need the UseWriteMetadata() call if your documents don't have "WritePath" or similar metadata

But `_useWriteMetadata` in `WriteFiles` is set to true by default, which means it would check for metadata (which I don't provide) if I don't set it to false manually, right?

I tested my above code and actually I needed one more check:

```
WriteFiles( (doc,ctx) => string.IsNullOrEmpty(doc.Content) ? null : "sitemap.xml")
```

or something similar, because there is already an input document with Content `""`. I guess that is added by default in the pipeline?

**Comment by daveaglick** [comment]
Yeah, the document with empty content is the initial document that contains all the engine metadata. It's usually cloned by the first module in the pipeline and replaced with actual documents with content so it wouldn't show up in downstream modules normally. But it's a good point - should add a check to WriteFiles to ignore documents with empty content.

If a document doesn't contain any of the metadata that WriteFiles uses first by default (such as WritePath or WriteFileName), it should defer to the delegate. It should be okay to leave it as true unless those metadata keys are provided. Is that part not working correctly?

**Comment by reliak** [comment]
Oh you're right, I don't need to set the writemetadata to false.
Ignoring empty contents in WriteFiles would be nice, then I wouldn't need the above check.
Then all I would need is: `WriteFiles( (doc,ctx) => "sitemap.xml")`
That's fine by me.

**Comment by daveaglick** [comment]
Okay, great. Away from computer for a while, but I'll make these changes a little later today.
