### ISSUE TITLE
Virtual file system

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#123]
This feature will serve as a replacement for System.IO throughout Wyam. It is important for the implementation of themes and should combine multiple physical locations with a defined search order into one virtual location.

For example, themes should work by providing a theme folder that gets checked for files before checking the actual input folder - if either one contains a file, it's presented as part of the virtual location. If the input folder contains a file that's also contained in the theme folder, the input path takes precedence.

Locations should also be agnostic of media. I.e., they should initially be based on file system, but could be expanded to FTP/SFTP server, GitHub, cloud storage, etc. Depending on how far we go with this, Input and Output folders may correspond to non-file system locations (how would we specify?). ReadFiles and WriteFiles modules may also need to be renamed to simply Read and Write with a optional constructor argument to specify alternate possibly non-file system locations if not inputting/outputting from/to the global input and output location.

Details for this issue will be refined as development progresses.

**Comment by daveaglick** [comment]
Consider if and how this may help enable scenarios like multiple language or multiple doc version support. Perhaps we can specify that the generation be run multiple times with different sets of sources and overrides (I.e., always use a common source with templates, but then specify a different higher priority source for content by language). For that matter, should we also allow changing starting engine metadata on multiple generations? Might need to make a new "multiple generations with different starting settings" issue.

**Comment by avishnyakov** [comment]
+1

**Comment by daveaglick** [comment]
Looked at [Platform.VirtualFileSystem](https://github.com/platformdotnet/Platform.VirtualFileSystem) - it doesn't appear to be actively maintained (owner is only contributor and doesn't respond to issues or pull requests), though I like some of the concepts. Also looked at [sharpfilesystem](https://github.com/FrozenCow/sharpfilesystem) which doesn't have a NuGet package but has an interesting MergedFileSystem idea we need. Also really fond of the IO abstractions in Cake.

Not sure there's a single good solution to this. I'll probably end up having to write our own abstraction - thinking right now is that it'll be modeled after the one in Cake. It's tempting to just reference Cake directly and then write wrappers (instead of porting)...

**Comment by daveaglick** [comment]
Some random implementation thoughts:
- `FilePath` - represents a file path (which may or may not exist). Similar to `FileInfo` in System.IO.
- `IFile` - represents an actual file within the file system. Capable of providing the file as a Stream.
- `DirectoryPath` - represents a directory path (which may or may not exist). Similar to `DirectoryInfo` in System.IO.
- `IDirectory` - represents an actual directory within the file system.
- Use Microsoft.Extensions.FileSystemGlobbing for globbing support. Create derived classes for `FileInfoBase` and `DirectoryInfoBase` that wrap `FilePath` and `DirectoryPath`.
- Audit usages of `System.IO.Path` and use the new `Path` classes wherever possible.
- Move functionality from `PathHelper` such as `.ToLink()` to new classes.
- Audit usages of string-based paths and convert to new classes.
- `Engine.RootFolder`, `Engine.InputFolder`, and `Engine.OutputFolder` (and `IExecutionContext...`) will need to change - should rename to `Engine.RootPath`, etc. and make them `DirectoryPath`.
- The input path should now be a sequence of `DirectoryPath` (either relative or absolute).
- Using `Path.FullPath` as a temporary bridge to old code - audit all uses when done.
- Remove `PathHelper` and `SafeIOHelper`

**Comment by daveaglick** [comment]
- Audit usages of `System.IO.Path` and use the new `Path` classes wherever possible.
- Move functionality from `PathHelper` such as `.ToLink()` to new classes.
- Audit usages of string-based paths and convert to new classes.

**Comment by daveaglick** [comment]
- `Engine.RootFolder`, `Engine.InputFolder`, and `Engine.OutputFolder` will need to change.
  - The input folder (should probably rename to `InputPaths` or something) will probably end up being a sequence of `IFileSystem`.
  - Since each `IFileSystem` has it's own root path, we may not need `Engine.RootFolder` anymore.
  - The output folder should only be specified once, so probably just a single `IFileSystem`?

**Comment by daveaglick** [comment]
Note that this is tightly coupled with #214

**Comment by daveaglick** [comment]
Resolved in 0.12.0
