### ISSUE TITLE
Create a Windows installer

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#127]
Will make onboarding easier for some users who aren't used to the command line. Might also make a lightweight GUI just for picking folders and running (cross-platform? what GUI toolkit? Eto.Forms?) Should also install service described in #21

**Comment by FlorianRappl** [comment]
Let's just use [Squirrel](https://github.com/Squirrel/Squirrel.Windows) for that. I would write the installer and make the PR.

We could have the application self-updating using a new boolean flag `--update`.

Should I start working on it?

**Comment by daveaglick** [comment]
> Should I start working on it?

Yes! That would be awesome.

This is one of those issues that I think is really important for adoption, but I just haven't had the time to dig into yet, so taking it on would be greatly appreciated. And I love the concept behind Squirrel, so I think that's a really good choice.
