### ISSUE TITLE
Create a Cake addin

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#129]
Not sure if this is even needed since behavior is already exposed through code in Wyam.Core. If an addin would help, it would probably be so that Cake IO interfaces can be passed to the engine instead of strings.

**Comment by daveaglick** [comment]
@patriksvensson or @devlead - do either of you have any advice on this? When does it make sense to create a dedicated Cake addin vs. just relying on NuGet packages that aren't Cake specific?

The goal here would be to have a better deployment story post-generation. For example, I could see using Cake to spin up Wyam and generate the site (via an addin?) and then have Cake manage deployment to IIS, FTP, etc. I also plan to add some deployment support directly to Wyam, but supporting Cake would really help in scenarios where the static generation is part of a larger process (like regenerating a code documentation site at the same time the project is otherwise built and deployed).

**Comment by devlead** [comment]
@daveaglick guess making add in makes sense of you can simplify something by an alias, i.e. wrapping series of operations into one alias call or wrap things that are untyped into an typed & documented alias.

Could also be to add behavior like validation post calling the API and breaking build on failure etc.

**Comment by daveaglick** [comment]
@devlead Thanks - that last line makes a lot of sense. Could also extend to error logging - Wyam has it's own logging subsystem, but when used from Cake it would make sense to pipe that through to Cake's logging API.

**Comment by daveaglick** [comment]
This is now done thanks to @gep13 and will officially go out with the next release!
