### ISSUE TITLE
Nightly builds of the develop branch

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#134]
I prefer using NuGet instead of having binaries in my projects. ~~Un~~Fortunately this projects develop fast. To have a nuget feed of the develop branch would be nice.
### Background

Yesterday I created a Project for Modules that are to specialized to contribute them to Wyam. Because I need IModule I need a reference to Wyam.Common. Because I normally use the debug build to build my site the lib provided by nuget is not compatible.
This leaved me with two possibilities copying the binary to the project, which isn't nice for being up to date.
Or referencing the binary directly where it will get build, which is not practical when you want the project in a repo.

**Comment by daveaglick** [comment]
This is a really excellent idea. I'll look at hooking up the develop branch to AppVeyor to automatically build either nightly or on each commit to a MyGet feed.

**Comment by daveaglick** [comment]
This also goes along with an idea I've been thinking about for v 0.13.0 - #135

**Comment by daveaglick** [comment]
I'm going to hold off a week or two on this until the next release is out - I'm trying really hard to focus and get 0.11.0 released as soon as possible (it's been too long without a release). I'll take a look at this soon after that's done.

**Comment by daveaglick** [comment]
Thanks to the new Cake Build support, it was easy to finally add this. Every commit to the repo now triggers a build and publish to MyGet at the following feed: https://www.myget.org/feed/Packages/wyam

**Comment by LokiMidgard** [comment]
Could it be that this feed is private?

If I click the link it requires me to log in. And even after, I can't access it. I also can't find the packages in the Gallery.

**Comment by daveaglick** [comment]
Odd - just checked and it's marked as public, but you're right, I had to log in too. I'll take a closer look when I get to the office in a couple hours.

**Comment by daveaglick** [comment]
I added the wrong endpoint to the docs - turns out that was the management page and not the actual feed. Try the following:

https://www.myget.org/F/wyam/api/v3/index.json (v3)
https://www.myget.org/F/wyam/api/v2 (v2)

To have Cake use the development feed, change the directives at the top of the Cake build script to:

```
#tool nuget:https://www.myget.org/F/wyam/api/v2?package=Wyam&prerelease
#addin nuget:https://www.myget.org/F/wyam/api/v2?package=Cake.Wyam&prerelease
```

Note that you'll also need to delete the existing "tools\Wyam" and "tools\Addins\Cake.Wyam" folders if they exist (otherwise Cake will just use the existing packages and won't download the new packages).

To use the development feed inside a Wyam configuration file for a particular module, specify it like this:

```
#n Wyam.Modules.Markdown -s https://www.myget.org/F/wyam/api/v3/index.json -l -p
```

**Comment by LokiMidgard** [comment]
Hey Thanks.

By the way, I haven't looked how myget works in detail, but is it a good idea to post a screenshot with your api key? Or do you need also your account credentials to push packages in the feed?

**Comment by daveaglick** [comment]
FFS, that was sloppy. Glad you noticed!

**Comment by daveaglick** [comment]
That's what I get for looking at issues while stopped at red lights :)
