### ISSUE TITLE
Wyam just stays in there doing nothing

### ISSUE THREAD

**Issue by alfadormx** [statiqdev/Statiq#138]
Hi,

I downloaded wyam both in my laptop and surface (both win10) and executed wyam through the console. It does nothing.
When I got the .zip I did unblock it before decompressing it, however, nothing happens.
It just stays there waiting for something.

Thank you for any information on how to get it working.

**Comment by daveaglick** [comment]
Does it give any output at all? You should at least get a little splash graphic and some diagnostic information. Do you get anything if you run it with the `--verbose` option?

**Comment by alfadormx** [comment]
Hi, thanks for the quick response. I have seen the source code and no, I do not get the ascii art. Not the --help, --verbose or --watch -- preview combination do anything whatsoever.
I execute the command and then the console (or PowerShell) window just shows a cursor blinking.

**Comment by alfadormx** [comment]
I have added a .gif into imgur that shows you the behaviour I see.
http://imgur.com/UdSfxgU
From there I have to close the PowerShell window since not even Ctrl+C stops the program.
Howeverm, I can still see a process dangling there from "Attach to process" in Visual Studio.

**Comment by daveaglick** [comment]
Yeah, that's not good!

It's interesting that there's still a process running though - that suggests something is happening in the background once the application launches. Nearly the first thing it does is write the version to the console. The only thing that happens before that is getting the Assembly version number - which may be the holdup.

A few questions come to mind:
- Did you unlock all the files in the zip archive (or the zip archive itself before unzipping) or just the .exe file?
- What version of .NET is on the system(s)?
- Are you able to build from source (if not, I can send some prebuilt binaries)? What happens with the newest build?

**Comment by alfadormx** [comment]
- I have unblocked the zip archive and then extracted. I did passed through all the .dll, .pdb & .exe files and no file was blocked after extraction.
- According to http://smallestdotnet.com/ I have 4.6 or greater.
- I am able to build from source. I can execute in debug mode from visual studio and step into the code. However, the generated .exe has the same behavior as the one downloaded from the release github page.

I wonder if it is a failure while trying to load a dependency rather than the Program wrapper class. I don't see any error on the Windows log either.

Just for extra info, the download has no problem whatsoever on my work pc, the OS is Windows 7 with same version of .NET framework.

**Comment by alfadormx** [comment]
Sorry to have bothered you with this. It is not a wyam problem. I have downloaded a couple solutions from github and they have the same behaviour. There is something wrong with my pc. What is weird it that I have the same problem with my Surface tablet.

**Comment by daveaglick** [comment]
No bother at all. That's an odd issue you've got, especially across systems - good luck getting to the bottom of it!

**Comment by daveaglick** [comment]
For reference, this was caused by an antivirus application blocking execution (Avast in this case):
http://stackoverflow.com/questions/34109002/executing-net-apps-from-console-in-windows-10-doesnt-work
