### ISSUE TITLE
Output of method which returns HtmlString is rendered twice

### ISSUE THREAD

**Issue by martinvobr** [statiqdev/Statiq#139]
I have an external assembly with business logic. Some methods outputs html-formatted content. Razor automatically escapes all html, so I need to call them using @Html.Raw

```
@Html.Raw(MyExtensionClass.MyMethod())
```

I would preffer to call them this way:

```
@MyExtensionClass.MyMethod()
```

In AspNet.MVC it can be accomplished by returning HtmlString instead of String. When using such method in Wyam the output is rendered **twice**. First is raw html; second is html-encodeded one.

I would expected only the raw output.

Complete repro with same extension lib used in both Razor web page and in Wyam razor template can be downloaded from http://www.vobr.cz/wyam/wyam-repro-html-string.zip 

I'm using wyam 0.10.0-beta

**Comment by daveaglick** [comment]
Thanks - I'll take a look very soon. I actually finally had some time and was right in the middle of debugging your other issue with passing the model from Razor views to external libraries :)

**Comment by martinvobr** [comment]
Thanks!

**Comment by daveaglick** [comment]
Repros are _so_ helpful. Ran the repro you provided against the most recent develop branch after the work in #141 and can confirm this is no longer an issue.
