### ISSUE TITLE
Allow using @helper syntax in csthml files and add support for App_Code folder

### ISSUE THREAD

**Issue by martinvobr** [statiqdev/Statiq#140]
Just a feature suggestion.

Wyam already supports declaring HtmlHelper in declaration section of the configuration file, which is great. However the config file can get quite big when one would like to use this functionality more often. In ASP.NET MVC it's possible to place helpers into normal cshtml file. Usual place for such helpers are either dedicated file(s) in App_Code folder or placing them directly into the cshml file where they are used.
#### Helpers declared and used in the same file

SomeFile.cshtm

```
@helper ShowValue1(decimal value)
{
    if (value > 0)
    {
        @value
    }
    else
    {
        <span style="color:red;">@value</span>
    }
}

    @MyHelper.ShowValue1(12)
    @MyHelper.ShowValue(-12)
```
#### Helpers declared in external file

App_Code\MyHelper.cshtml

```
@helper ShowValue(decimal value)
{
    if (value > 0)
    {
        @value
    }
    else
    {
        <span style="color:red;">@value</span>
    }
}
```

SomeFile.cshtml

```
    @MyHelper.ShowValue1(12)
    @MyHelper.ShowValue(-12)
```

Similar syntaxt can be used for @function - and easy way how to declare reusable piece of code without need to compile an external lib.

Adding support for this would have following benefits over declaring extension helpers in config.wyam file:
- intellisense while editing cshtml helper files in VisualStudio
- cleaner main config file
- more pleasent way to create a reusable formatting code than partials. Partials are great, but passing values to them via ViewData might lead to lot of infrastructure code which could be eliminated by using helpers.

I don't know how hard or easy would be adding it to Wyam. Would it make sense? What would you think?

**Comment by daveaglick** [comment]
I would love this. I actually use `@function` quite a bit in my normal ASP.NET work, so I definitly miss it. I'm hoping we get this support automatically when I switch off of my custom Razor build and start using the official binaries. That'll also bring over other official capabilities that we lack like TagHelpers, etc.

**Comment by martinvobr** [comment]
Cant' wait for release 0.12 :-). If I can help (e.g. with testing) just let me know.

**Comment by avishnyakov** [comment]
+1 for that feature, just found that ticket while were searching for helper or inline function support

**Comment by daveaglick** [comment]
Note that since we started discussing this feature (with my hope that work on #141 would make it available), it's been removed from ASP.NET Core. See aspnet/Mvc#4127 and aspnet/Razor#715 (which also contains some workarounds). While it may make a comeback, it doesn't look that that'll happen any time soon. I'd rather wait for it to be introduced directly in ASP.NET Core MVC than build it myself - I don't want the Wyam Razor implementation to stray too far from the one in MVC. Therefore, I'm regrettably going to close this issue as a "won't fix".
