### ISSUE TITLE
Update To Official Razor Binaries

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#141]
Now that ASP.NET 5 is RC, we can start looking at replacing the hacked together Razor implementation in Wyam with the official binaries.

**Comment by daveaglick** [comment]
See #140 and #139

**Comment by daveaglick** [comment]
Assigning this to 0.12.0, but might slip to 0.13.0.

**Comment by martinvobr** [comment]
It looks like it did not made into 0.12.0. Any chance to include it  in 0.13.0?

**Comment by daveaglick** [comment]
Possibly. Part of timing relies on Razor getting to at least RC2 and possibly final depending on how stable RC2 looks to be in terms of API changes. There's so much other work to do, I don't want to end up switching to (and possibly porting) the Razor engine again only to have the API drastically change and need to do the work over for the final release of Razor.

I'm keeping a close eye on it. I'd love to get there sooner rather than later.

**Comment by martinvobr** [comment]
Good news: AspNet/Razor recently reached RC2 milestone. https://github.com/aspnet/Razor/releases/tag/1.0.0-rc2

**Comment by martinvobr** [comment]
Even better news: AspNet/Razor reached 1.0.0 milestone
https://github.com/aspnet/Razor/releases/tag/1.0.0

**Comment by daveaglick** [comment]
If enthusiasm could make code appear, we'd be set :smile:

I know you've been waiting to get the full Razor library integrated and I think I'm getting close to a point where that makes sense. Now that Core has gone 1.0 that's no longer the blocker. My own time and priorities are probably the holdup at this point. I'd like to totally finish off the recipe support and then I'll probably start looking at Core-related tasks such as this one.

**Comment by martinvobr** [comment]
:-). I totally understand that you want to finish recipes. It would be great if updating to official Razor binaries will be on shortlist next. I keep my fingers crossed. Thanks for all your work on Wyam.

**Comment by daveaglick** [comment]
FYI - this is under active development in the "razor" branch (and has been for a couple weeks). It's getting close, hope to finish up in the next week and release for testing.

**Comment by martinvobr** [comment]
@daveaglick Thanks for great news!

**Comment by daveaglick** [comment]
This is now merged into the develop branch and will go out with the next release!
