### ISSUE TITLE
"This app can't run on your PC" error while running on win8

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#143]
Hey guys, anyone run Wyam on win8? 

Having "This app can't run on your PC" which seems to be cased by lack of  .NET 4.6. 
Installed 4.6, reboot, all things, but yet still having "This app can't run on your PC". 

The other way around, got the sources to built with 4.5 but surely it was not a good idea - it's all aboyut 4.6 internally :)

Any ideas to solve that and get Wyam running on either win8 or .net45?

**Comment by daveaglick** [comment]
I actually use Win 7 day-to-day and it works fine there, so I would guess 8 works (though to be honest, I haven't actually tried it). I probably won't get a chance to look at this tonight, but I'll fire up a Win 8 VM tomorrow and see if I can replicate.

**Comment by avishnyakov** [comment]
Hey @daveaglick, interesting. Don't worry yet, let me play around and get back with the outcome. Will try on other machines / VMs and will see how it goes.

As for .net45, how hard would it be to compile w/ 45? Suppose some dependencies won't allow that, will they?

**Comment by daveaglick** [comment]
Actually, most of the dependencies should be okay. The one you'd probably have trouble with is the library for Razor support since it's basically copied over from the ASP.NET 5 code. There might also be some issues with the core library since it uses Roslyn.

**Comment by avishnyakov** [comment]
Works well on the other laptop and Win8. Closing the ticket, thanks!

**Comment by daveaglick** [comment]
Great - good to hear!
