### ISSUE TITLE
How to add extra Namespace into Razor View

### ISSUE THREAD

**Issue by heavenwing** [statiqdev/Statiq#144]
I defines some custom types in config file, and use these types in Razor View.
When I move custom types into a custom module class library, Razor module is not working.
I believe that custom namespace is missing in Razor View.
But I don't know how to add namespace into razor view, because of "_ViewImports.cshtml" cannot be added into Razor module.

**Comment by daveaglick** [comment]
You can add new namespaces to a Razor view by writing `@using` at the top of the view:

```
@using Some.Namespace;
```

Does that resolve the problem you're having?

**Comment by heavenwing** [comment]
I tried this way, but it was not work. Should you or (maybe me) add a function to add extra namespaces?

**Comment by daveaglick** [comment]
So does your PR #148 also resolve this problem? By making sure the namespaces collection in the configuration object gets populated, I think this line in the Razor module takes care of adding them to the view scope:

https://github.com/heavenwing/Wyam/blob/develop/Wyam.Modules.Razor/Mvc/Microsoft.AspNet.Mvc.Razor.Host/MvcRazorHost.cs#L52

If you're still having trouble with this after your PR, do have a reproducible example you could send that exhibits the problem?

**Comment by heavenwing** [comment]
My PR #148 don't fix this problem. Actually, I planed to fix it originally. I tried that passing extra namespaces through Configure method, and below this line (https://github.com/Wyamio/Wyam/blob/develop/Wyam.Core/Configuration/Configurator.cs#L237) adding "_namespace.AddRange(_extraNamespaces)". 
However Rozar View still throw a exception.
I will upload a  reproducible example in a moment.

**Comment by heavenwing** [comment]
Sorry , I cannot reproduce it now . You can close this bug for the present.

**Comment by daveaglick** [comment]
Great. Just let me know if the problem presents itself again and I'll be happy to reopen the issue and take a closer look.
