### ISSUE TITLE
Create a github module

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#145]
I see a great value of crafting github module, so that Wyam would know about github issues / milestones. Once done, Wyam could be used to setup "release notes" pages in many interesting ways - not only by manual triggers, but.. some triggers by webhooks and the whole CI/CD story.

There are some "release notes" generators out there, I did one to be used internally too. Hovewer I clearly see that happening with Wyam.

Octokit can be used to deal with github, and then crafting POCOs and pushing to the pipeline.

Outcome is more than exciting, I guess. Easy way to create "release notes" in highly maintainable, automated way not only for github, but also for other systems - we have control over layouts/templates/pipelines.

What do you think, guys?

**Comment by daveaglick** [comment]
I think it's a great idea. In fact, I had already started looking at this to support another project I'm applying Wyam to. So this module may get done sooner rather than later :)

**Comment by avishnyakov** [comment]
@daveaglick, would you please share more details on how would the GitHub module look like?

One of the possible usage of such module would be automated generation of a "Release Note" page for a new release. Frankly saying, extremely keen to move our current hand-made generation to Wyam :)

So once a new release is created, Wyam would be used to generate release notes. Here is a full story:
- Get all closed issues by date range (start / end date) or get all closed issues in the giving milestones
- Filter these issues by giving labels. For instance only "bug", "features", "new module"
- Group issues by giving labels:"bug", "features", "new module"
- Iterate over all issues and create markdown file with the following content:

``` markdown
### bug
* #{issue number + link}, {issue title}
* #{issue number + link}, {issue title}

### features
* #{issue number + link}, {issue title}
* #{issue number + link}, {issue title}

### new modules
* #{issue number + link}, {issue title}
* #{issue number + link}, {issue title}
```

That's gonna get us a neat markdown bit to insert into github release description, later to your bog post or your web site.

Would that kind of story be supported by the GitHub module you mentioned and current state of Wyam? Anything we can help you with?

**Comment by daveaglick** [comment]
I finally started implementing a GitHub module, but very quickly realized that I had no idea what it should do. There are so many different API endpoints, that wrapping them all in a module API would be both time consuming and silly.

So I'm left wondering if a GitHub module is valuable at all, or if this should be one of those areas addressed by custom extensibility depending on the site. It probably comes down to whether we can derive some small(ish) set of behavior we would want a GitHub module to have. I.e.:
- Get information about a repository (but what information?)
- Get issues (but what about filtering, sorting, labels?)
- Get contributor data
- Get statistics

Etc. What I really _don't_ want to end up doing is reimplementing all the calls in Octokit and the GitHub API, just with one extra layer of abstraction...
