### ISSUE TITLE
Cleaning markdown '@' characters before sending them to the razor module?

### ISSUE THREAD

**Issue by alfadormx** [statiqdev/Statiq#146]
Hi, my posts pipeline is configured like this:

```
Pipelines.Add("Posts",
    ReadFiles(@"posts\*.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Replace("<pre><code>", "<pre class=\"prettyprint\"><code>"),
    Concat(
        ReadFiles(@"posts\*.cshtml").Where(x => Path.GetFileName(x)[0] != '_' && Path.GetFileName(x) != "index.cshtml"),
        FrontMatter(Yaml())
    ),  
    Razor(typeof(RazorPage)),
    Excerpt(),
    WriteFiles(".html")
);
```

I have a post written in markdown with the following sql syntax I was writing about:

```
USE [Northwind]
GO

DECLARE @FutureParent  INT
SET @FutureParent = 3 

-- base query
SELECT Employee.[EmployeeID], Employee.[ReportsTo], 1 AS EmpLevel
FROM [dbo].[Employees] AS Employee
WHERE [EmployeeID] = @FutureParent

GO
```

During pipeline execution I had the following error:

```
            5 errors compiling /posts\how-to-find-possible-loops-in-hierarchy-us
ing-sql.md.cshtml:
/posts\how-to-find-possible-loops-in-hierarchy-using-sql.md.cshtml(35,23): error
 CS0103: The name 'FutureParent' does not exist in the current context
```

So in order to fix the problem I had to add double '@@' in the '@FutureParent' so the razor engine would escape it properly.

Wouldn't it be interesting if there was a module that could prepare content coming from markdown files that could remove these potential flaws for the razor module? I would like to have my md files as clean as possible in order to reuse them later in other generator if needed.

What is the best practice concerning this kind of issue?

Thanks

**Comment by daveaglick** [comment]
Have you updated to the latest version yet? In 0.11.0 released last week, all `@` symbols are automatically HTML escaped in the Markdown module output. That should address this exact issue.

You can also turn the behavior off if you need the original behavior to pass the `@` symbols to a downstream Razor module. In that case, you'll have to do exactly what you describe here and double them up if you want to escape them in the downstream Razor module.

See the `EscapeAt` method here: http://wyam.io/modules/markdown

**Comment by alfadormx** [comment]
Hi,

I just downloaded the newest version, restored my markdown file and executed wyam again. It works properly.

Thanks!

**Comment by daveaglick** [comment]
:thumbsup:
