### ISSUE TITLE
Create a link validation module

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#15]
Crawls through specified HTML files and checks relative links to make sure they're all valid. Outputs warnings to trace. Does not perform any transformation.

Look at html-proofer: https://github.com/gjtorikian/html-proofer

**Comment by daveaglick** [comment]
I think the way resolution should work is that the module should have a constructor that takes a path. This path then serves as the root for validating relative links and references in all the input documents. If no path is given (null) then `OutputFolder` is used. Then all that needs to be done for verification is to check for file existence in the specified path.

**Comment by avishnyakov** [comment]
Hm.. seems that one could depend on other things like:
- HTML module to access all hrefs
- potential virtual file system or  root input / output folder access?

How is it possible to get things moving with the current versions and state of the Wyam?
