### ISSUE TITLE
Is the *.wyam config being watched with --watch option?

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#152]
--watch option is pure gold, extremely useful feature

However it seems that  *.wyam config is not being watch, so that every a stop/start of the Wyam is needed. Would not it be awesome to watch .wyam config and restart once changed?

**Comment by daveaglick** [comment]
The config file should be watched (if you dig into the code in the console application, you'll see that when the config file changes the current `Engine` is disposed and a new one is created). That said, it's been flaky for me and there are definitely some times when it doesn't catch the change.

I'm planning on switching over to a whole new file system abstraction very soon as part of 0.12.0, so I've kind of been putting off digging into problems with the watcher in the hopes the new one will behave better.

That said, if you see some sort of pattern in when it works and when it doesn't, that would be very helpful.

**Comment by daveaglick** [comment]
Related to #123

**Comment by avishnyakov** [comment]
Just FYI, we run it from the PS ISE with the following script. Could be related to the custom path of the config or something.

``` ps
cls
cd  $PSScriptRoot

 #. "$PSScriptRoot\Wyam\Wyam.exe" --watch --input "$PSScriptRoot\Content" --output "$PSScriptRoot\Content-Output" --preview --config "s-docs.wyam" --log "s-docs.log" --verbose
 . "$PSScriptRoot\Wyam\Wyam.exe" --watch --input "$PSScriptRoot\Content" --output "$PSScriptRoot\Content-Output" --preview --config "s-docs.wyam" 
```

**Comment by daveaglick** [comment]
Okay, thanks. That very well could be related. The current watcher logic is pretty dumb, I'll take a closer look.

I love that the community is now using this thing in ways I never considered or would have thought of.

**Comment by daveaglick** [comment]
@avishnyakov Could you provide an update on this issue, if possible? Is running from the PS ISE still ignoring changes to the config file?
