### ISSUE TITLE
Consider automatic page reload once Wyam regenerated new pages

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#155]
A big one. 

Similar to Browser Link feature in VS - it be nice if Wyam could refresh current opened pages in the browsers. Extremely useful while actively crafting the content, templates and other components.

Say, you are crafting master page or layout, css and the rest having a few pages opened in the browser at the same time: landing page, post categories, post page. So you changes something, and then you don't need to reload every single page: Wyam regenerates the content on the --watch option... and then automatically refreshes all opened pages in browser. Wooohooo, how awesome is that! Cutting quite a time waste bringing sorta 'live preview' option for Wyam.

A first 'draft' of the feature might be just a small Wyam-system' JS script injected in every page by Wyam. The JS  would ask the web server if there is a fresher page (hash, time stamp in the file, whatever) and simple reload the page. No need to complicate things (SignalR surely awesome), it's local dev so we might live up to that impl for the time being.

**Comment by daveaglick** [comment]
This is definitely a facet of #157. I'll keep the ticket open to track this particular feature separately, but hopefully it'll get wrapped up when implementing that one.

**Comment by daveaglick** [comment]
Resolved using LiveReload by @Silvenga in #420
