### ISSUE TITLE
Confusing FileName module behavior

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#159]
FileName is meant to change the output file name.

Alight, aiming to rename the file so writing the following:

```
// yaml

---
FileName: myfile.html

---

// config
FileName("FileName"),
WiteFiles(".html")

// output, what?
myfilehtml
```

Alight! One more time. Let's remove the extensions, cause we have WriteFiles

```
// yaml

---
FileName: myfile

---

// config
FileName("FileName"),
WriteFiles(".html")

// output, not again..
myfile
```

Ignored stuff? Okay. Let's ignore "." but why?

```
// yaml

---
FileName: myfile

---

// config
FileName("FileName").WithAllowedCharacters(new[] {"."}),
WriteFiles(".html")

// output, c'mon, we asked for HTML in WiteFiles, can't you just get it? :)
myfile
```

Okay, everything has to be provided and not ignored, right?

```
// yaml

---
FileName: myfile.html

---

// config
FileName("FileName").WithAllowedCharacters(new[] {"."}),
WriteFiles(".html")

// now we are talking!
myfile.html
```

A bit confusing behaviour unless you go after the source code of the FileName module.
Reasonable, the following unexpected wonders would arise:
- default trimming of some chars like "_", "-" and ".", hm...
- priority over WriteFiles extension
- confusion in case "myfile"  and "myfile.html" is provided - WiteFiles is still ignored

At the end it works well, but kinda tricky to follow the logic and get it right.

**Comment by daveaglick** [comment]
This seems like a bug to me. If I'm providing a full extension like ".html" to the WriteFiles module as in your first couple examples, I would expect that to work. Whatever happened in the FileName module shouldn't matter either - the WriteFiles module doesn't know or care about what came before. Thanks for the report, I'll dig deeper.
