### ISSUE TITLE
Consider changing Markdown processor to Markdig

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#165]
The current one is CommonMark implementation, so there aren't any neat familiar github-flavored markdown goodies. It would be nice to see alternative markdown implementations with extended syntax support.

**Comment by daveaglick** [comment]
What additional Markdown support were you most interested in (so I know which libraries to investigate)?

**Comment by avishnyakov** [comment]
That be github-flavored markdown, in particular tables.
https://help.github.com/articles/github-flavored-markdown/

Guess that might be a rare case. However if the content is fully stored at github and then Wyam is used  to generate the web sites, then tables comes handy. You just use all what github offers.

**Comment by avishnyakov** [comment]
How does it go?

Stumbled upon this item again, and again github based markup such as tables.

**Comment by miere43** [comment]
As far as I know there are no Github Flavored Markdown implementation in C#. If you really need tables this much, you can put HTML tags inside Markdown and they will work.

**Comment by daveaglick** [comment]
> you can put HTML tags inside Markdown and they will work

This is how I do it right now, and the CommonMark spec is specifically written to allow mixing in HTML tags.

As for a more general solution, this just isn't a priority right now. We have a working Markdown implementation, and there are too many other new features to focus on. Given that the [CommonMark.Net library](https://github.com/Knagis/CommonMark.NET) that we use now supports extensions, what I'd love to see is a set of extensions for this type of thing and flags to turn non-standard functionality on and off.

**Comment by daveaglick** [comment]
[Markdig](https://github.com/lunet-io/markdig) is a new Markdown processor that does support tables, in addition to many other extensions. While I like CommonMark.NET and it's been good to us, there appear to be many benefits to switching. I've retitled this issue and plan to take a close look at swapping out the Markdown processor for Markdig.

A note on providing multiple engines: I don't see any value in that. For one, it means the module library would have to take on additional dependencies. It would also add complexity for the user. How do they know which one to choose? Markdown (or at least CommonMark) is a standard format, the user shouldn't care how their Markdown files become HTML. In short, I don't like the idea of offering choice here. If the user really wants to use an alternate processor, they can easily use the `Extension` module or write a lightweight module in the config file.

**Comment by FlorianRappl** [comment]
I just wanted to open this item (changing to markdig). As I now have time again to contribute here I would like to come up with a potential solution and issue a PR. Hopefully, I'll could submit it by end of next week.

I think the main reason for swapping to markdig should be (at least for me) to gain the extensibility. Not only does markdig come with a lot of (optional) useful extensions, but one can roll out extensions very quickly. In my opinion this would be highly useful in many scenarios.

**Comment by daveaglick** [comment]
@FlorianRappl Great, go for it! This is pretty high on my wish list - would love to get a bit more control over the Markdown processor for things like tables and Bootstrap CSS class insertion.

**Comment by FlorianRappl** [comment]
Hi @daveaglick I made a few changes and pushed the PR. Let's continue the discussion in #328.
