### ISSUE TITLE
Console exit codes for automation

### ISSUE THREAD

**Issue by AlanBarber** [statiqdev/Statiq#171]
Currently the app is set to only set an exit code of 1 for unhandled exceptions, all others times it returns an error code of 0

For automation uses like CI build servers or if say a 3rd party GUI was designed to call the command line app, it is handy to have return values set for failures so that appropriate actions can be taken to recover or correct the failures.

I'm not sure all the codes that would be worth adding at this point but I would think that at the bare minimum there should be an error for failures at each step of the apps process.

Doing a quick code skim I put together this list...

| Code | Issue |
| :-: | --- |
| 0 | No errors |
| 1 | Unhandled generic error |
| 2 | Command line errors |
| 3 | Config errors |
| 4 | Generation errors |
| 5 | Preview server errors |

**Comment by avishnyakov** [comment]
+1

**Comment by daveaglick** [comment]
Added the following exit codes:

``` C#
public enum ExitCode
{
    Normal = 0,
    UnhandledError = 1,
    CommandLineError = 2,
    ConfigurationError = 3,
    ExecutionError = 4
}
```

No exit code for preview server failures needed since that doesn't normally take down the application (you get an error in the console, but generation should complete normally and it will even continue watching).
