### ISSUE TITLE
Files with .rss extension are not served

### ISSUE THREAD

**Issue by miere43** [statiqdev/Statiq#175]
Simple test:
config.wyam

``` c#
Pipelines.Add("Test",
    ReadFiles("any.txt"),
    WriteFiles(".rss")
);

Pipelines.Add("Test 2",
    ReadFiles("any.txt"),
    WriteFiles(".html")
);
```

any.txt

```
blah
```

Wyam CLI settings:

```
wyam --watch --preview force-ext
```

Accessing URL `http://localhost:5080/any.rss` returns 404, while `/any.html` returns `blah`.

**Comment by daveaglick** [comment]
Interesting - first hunch is that the OWIN server is 404ing files that it doesn't have a ContentType mapping for... I'll look into it.
