### ISSUE TITLE
Low contrast of warning messages from modules

### ISSUE THREAD

**Issue by martinvobr** [statiqdev/Statiq#182]
Is it some way how to change color for error messages thrown from modules? Error messages from (for example) razor module are dark red on black on standard Windows 10 cmd shell. It's hard to read and parse what's wrong.  

In the contrast errors from wyam.config are rendered with bright red and are much easier to read.

When developing doc using wyam I have to read errors thrown by Razor module or by my business logic layer very often. 

Is it possible to change colors with some configuration in either wyam or shell? Or is it hardcoded?

Errors from modules (hard to read for me): 
![untitled](https://cloud.githubusercontent.com/assets/10501348/12200957/da712674-b621-11e5-93f2-dbdbc42a15e4.png)

Errors from wyam.config (fine):
![untitled-errors](https://cloud.githubusercontent.com/assets/10501348/12201191/22e4f9f2-b623-11e5-9cc7-e5e502e0ab88.png)

**Comment by martinvobr** [comment]
After some research I've traced it to https://github.com/Wyamio/Wyam/blob/develop/Wyam/SimpleColorConsoleTraceListener.cs and http://blog.flimflan.com/ASimpleColorConsoleTraceListener.html. If you see the screenshot on the end of the second linked page you would see that error message is the less readable of all lines. 

I'll try to come with updated color scheme and post it here when ready.

**Comment by daveaglick** [comment]
@martinvobr Are you still working on this? If I made a quick change that shifted Error and Critical messages to white text with red (or dark red) backgrounds, would that work for you?

**Comment by martinvobr** [comment]
@daveaglick I've tried following settings in my local copy of SimpleColorConsoleTraceListener.cs :

```
{ TraceEventType.Warning, ConsoleColor.DarkYellow },
{ TraceEventType.Error, ConsoleColor.Yellow },
{ TraceEventType.Critical, ConsoleColor.Red },
```

This settings works for me.

I wanted to submit it as a pull request and do some screenshot, but failed to do so, because I got distracted by learning and setting up git client and few other things. I'm new to git and github, I usually use a mercurial. 

Do you have a code with changed backgrounds somewhere so I can try it?

**Comment by daveaglick** [comment]
I made errors bright red and critical messages have a red background:
![2016-01-15_14h37_20](https://cloud.githubusercontent.com/assets/1020407/12363255/c48e1208-bb95-11e5-9ba5-abbff6132788.png)

**Comment by daveaglick** [comment]
I'll close this for now - feel free to comment and I'll reopen if the new scheme isn't sufficient.

**Comment by martinvobr** [comment]
Thanks, new scheme is ok.
