### ISSUE TITLE
Strongly-typed documents

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#183]
Allow the registration of a custom `IDocument` implementation in the engine/config script. This will probably require formalizing the factory pattern and the creation of an `IDocumentFactory` (alternatively, we could just have the user register a `Func<IDocument>` instead of an entire factory class).

The engine will have to be audited to make sure there are no assumptions about the document type that use casts to `Document`. Will also probably want to add a base `Document` class to `Wyam.Common` that can be used as a starting point.

Also note that it would be too hard to change the modules, Razor, etc. to be generic and use the actual document type. Modules, Razor pages, etc. will need to cast to the specialized document type as appropriate.

**Comment by daveaglick** [comment]
Along with supporting strongly-typed documents, we should also provide native support for them in the Razor module. This could be accomplished using a similar mechanism as supplying an alternate base page.

**Comment by daveaglick** [comment]
Notes to self:
- Create a `CustomDocument` class in Wyam.Common that can be used as a base class for custom document types and wraps a `IDocument`. It will need a method, "SetWrappedDocument(IDocument)` or similar that the factory can use.
- Create a `CustomDocumentFactory` in Wyam.Core that will be substituted for the real document factory when a custom document type derived from `CustomDocument` is used (this class doesn't need to be visible to consumers)
- Add a method somewhere (in the engine?) like `UseCustomDocumentType<T>()` to set the custom document type. We will need to enforce that the custom type has a default constructor in the generic constraints.

**Comment by daveaglick** [comment]
Got this implemented, here's a bare-bones config file showing it in action:

```
public class MyDocument : CustomDocument
{
    public int Count { get; set; }
}
---
Engine.DocumentFactory = 
    new CustomDocumentFactory<MyDocument>(Engine.DocumentFactory);

// Just add pipelines and stuff as normal here...
```

Basically, you just derive your document type from `CustomDocument` and then create a `CustomDocumentFactory<T>` with your type as the generic parameter, being sure to pass in the existing `IDocumentFactory` (since the custom factory essentially wraps it).

I'm going to add a more detailed example to the set of examples and hopefully introduce a couple more tests before closing this out, but the implementation should be complete.

**Comment by deanebarker** [comment]
I have a site I can try it out on this weekend. Stay tuned.

**Comment by deanebarker** [comment]
Gave it a whirl, but I'll need a more detailed example, I think. There's more to DocumentFactory than I expected.

**Comment by daveaglick** [comment]
I'll hopefully get a complete example up tonight or tomorrow. The trick though is that you don't have to reimplement `IDocumentFactory`. In the short example above, whereas you have to create your own document class, you can literally use the following line verbatim in your script to use it:

```
Engine.DocumentFactory = 
    new CustomDocumentFactory<MyDocument>(Engine.DocumentFactory);
```

Just substitute your own document type as the generic parameter and you should be good to go.

On the other hand, until I get my own example up and running, there might be bugs or something that's preventing it working as designed...

**Comment by deanebarker** [comment]
This won't compile:

```
public class MyDocument : CustomDocument
{
    public string Title { get { return String("Title"); } }
}
---
Engine.DocumentFactory = new CustomDocumentFactory<MyDocument>(Engine.DocumentFactory);

Pipelines.Add("PostsContent",
    ReadFiles(@"Content\Posts\*.md"),
    Trace((d,c) => d.Title)
);
```

I get this:

```
    1 errors compiling configuration:
Line 15: CS1061: 'IDocument' does not contain a definition for 'Title' and no extension method 'Title' accepting a first
 argument of type 'IDocument' could be found (are you missing a using directive or an assembly reference?)
Error during configuration evaluation: One or more errors occurred.
```

**Comment by daveaglick** [comment]
Progress! The issue now is that all the modules have to continue to operate on `IDocument` unless we introduce all sorts of extra generics. That means anytime you want to access members of your custom document class, it'll just need to be cast:

```
Trace((d,c) => ((MyDocument)d).Title)
```

**Comment by deanebarker** [comment]
Changed to:

```
Trace((d,c) => ((MyDocument)d).Title)
```

Compilation errors are gone.  But now I get a runtime error.  There's a lot output, but I think it boils down to this:

```
---> (Inner Exception #3) System.InvalidCastException: Unable to cast object of type 'MyDocument' to type 'Wyam.Core.Doc
uments.Document'.
   at Wyam.Core.Documents.DocumentFactory.GetDocument(IExecutionContext context, IDocument sourceDocument, IEnumerable`1
 items) in C:\Code\Wyam\src\Wyam.Core\Documents\DocumentFactory.cs:line 75
```

**Comment by daveaglick** [comment]
Doh - that's definitely a bug. I'll need to audit the code for any casts to `Document` being made back when it was the only `IDocument` implementation.

I'm also thinking about adding a `SetCustomDocument<T>()` method to the config script so you don't have to mess with setting the factory - a small enhancement, but should make it a bit clearer.

**Comment by daveaglick** [comment]
So I tracked down that bug, but it brought up a more serious problem: cloning custom documents. 

Presumably, the values of properties on custom documents should be carried forward to their clones. So I can't just instantiate a fresh custom document because then we'd be missing the values from the source document. And I can't just carry one instance through the cloning process because if you change a value of a property after cloning, you wouldn't want that change to affect other clones. I think the custom document type has to be responsible for cloning behavior

That means it'll have an abstract `CustomDocument Clone(CustomDocument sourceDocument)` method (where `sourceDocument` is of the custom document type). This method should instantiate and return a new instance of the custom document with all the appropriate copying of values.

Your custom document type from above might now look like:

```
public class MyDocument : CustomDocument
{
    public string Title { get; set; }

    public override CustomDocument Clone(CustomDocument sourceDocument)
    {
        return new MyDocument
        {
            Title = ((MyDocument)sourceDocument).Title
        };
    }
}
```

**Comment by daveaglick** [comment]
Okay, think I've got it this time. I still need to write a good example for the examples folder, but I did add some tests to verify the implementation is working as intended. Two notes:
- `CustomDocument` does require you implement `protected override CustomDocument Clone(CustomDocument sourceDocument)` (notice this is `protected` which is a slightly different access modifier than the example above where it's `public`) - you _must_ return a new instance of your custom document type, even if nothing will change, otherwise it will throw an exception
- I did add a method, `SetCustomDocumentType<T>()` which you can use right from the config script to set the custom document type without having to worry about the document factory

**Comment by daveaglick** [comment]
Checking in an example momentarily and then I'll be closing this one (unless you find other problems during use). One more small change, the clone method in `CustomDocument` is now simpler and should produce a clone of the current instance: `protected override CustomDocument Clone()`.

**Comment by deanebarker** [comment]
How can I clone the current instance in `Clone`?  Don't I have to have an `IExecutionContext` to get access to `GetDocument`?

I can't understand how to create a brand new document inside `Clone`.

**Comment by daveaglick** [comment]
It's more of a traditional clone method now - all you have to do is return a new instance of your own document class with the same values as the one `Clone()` is being called on:

https://github.com/Wyamio/Wyam/blob/develop/examples/CustomDocumentType/config.wyam

**Comment by deanebarker** [comment]
Okay, I have it now.

I guess my use case was a little different in that I'm looking for a facade or wrapper around `Document`.  My custom document class isn't carrying any actual data, it's just providing convenience methods/properties around meta, which is helpful for keeping templating clean and consistent.

For example:

```
public string Title { get String("title"); }
```

I have this working in test.  I'll fold it over into the Robots site in the next couple days.  That will be a good test, as there's a lot going on there.

**Comment by daveaglick** [comment]
Ah, that's a great point. Actually, the whole `CustomDocument` setup _is_ merely a wrapper around `IDocument` - that part is just hidden right now. It's trivial to add a protected getter for the wrapped document, which should enable the scenarios your looking at. I'll push the change later today.

**Comment by daveaglick** [comment]
Now that I'm looking more closely at your code, I think that's the way to go and we don't need the change after all - since `CustomDocument` also implements `IDocument`, all the interface methods and properties are available on the instance, you just have to know they're there. Exposing the wrapped `IDocument` wouldn't get us anything extra. I'll make sure to add a note about that in the knowledge base article for this.

**Comment by deanebarker** [comment]
I meant to ask -- how is this handled by Razor?  Will the `Model` be `MyDocument`?

**Comment by daveaglick** [comment]
Right now, no. You have to cast it. Easiest way is just to add a cast at the top of the Razor template:

```
@{
    MyDocument myDoc = (MyDocument)Model;
}
<html>
Etc, etc...
@myDoc.Title
<html>
```

**Comment by deanebarker** [comment]
Do we need to make `Clone()` abstract?  Or should we make it virtual and the default implementation just returns a new instance of the `MyDocument` class?  For instance, using my "facade/wrapper" use case described above, all my `Clone()` method has in it is this:

```
protected override CustomDocument Clone()
{
    return new MyDocument();
}
```

It seems extraneous to make people do that for what I think will be a pretty common use case.

**Comment by daveaglick** [comment]
I thought about making it virtual - my concern was that if we don't enforce an override, it might not be clear that needs to be done in the cases where it does. On the other hand, I guess if you don't do it and the generation doesn't look right, then it'll be obvious that you need to go back and add it.

I'm okay switching to virtual. I hadn't envisioned the use case you're doing where it just presents metadata in a more friendly way, which seems like a really great use of custom document types and shouldn't need a custom clone.

**Comment by deanebarker** [comment]
I'll look forward to it... :-)
