### ISSUE TITLE
Add a way to cancel execution

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#187]
Throwing an exception just cancels the current pipeline, but other pipelines keep running. We need a way to cancel execution entirely from within a module. Some options:
- Make all exceptions cancel overall execution. This makes some sense because presumably if one pipeline fails, the whole build is invalid.
- Add an option (globally and/or per-pipeline and/or per-module) to specify that uncaught exceptions cancel the build. This could be done in conjunction with the change to default behavior of exceptions above.
- Keep the current behavior of exceptions just cancelling the pipeline but provide a new exception type (that can wrap other exceptions) to indicate it's serious enough to cancel the build.

**Comment by daveaglick** [comment]
Decided to go the simple route and make all unhandled exceptions cancel execution. This makes sense because if there's an exception from one of the modules, the build is probably in an indeterminate state anyway and continuing probably just means getting invalid output. So to cancel the build, just throw an exception.

I'll implement a more complete cancellation mechanism when I look at parallel pipeline processing in #189.

cc @deanebarker

**Comment by deanebarker** [comment]
Confirmed that this works well.  It could be a little more graceful -- right now, it just dumps the stacktrace  to the console.  Maybe in future implementations, just the message?

But, again, I have verified it works as expected now.  I can throw an unhandled exception, and execution of the pipeline ends.

**Comment by daveaglick** [comment]
Good point - stack trace should probably only dump to the verbose stream
