### ISSUE TITLE
Parallel pipeline execution

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#189]
It's probably time to start looking at parallel pipeline execution. Here are my thoughts:
- It should be opt-in. Unless the user specifies parallel execution (as a CLI switch or a property of the `Engine`), pipelines should still be run sequentially.
- Pipelines can define which other pipelines they depend on. These dependency chains will be calculated and still run sequentially.
- We'll need some way of showing which pipeline trace messages are for since there may be multiples at once. I'm thinking prepending all trace messages with "[Pipeline     ] Message" (the bracket length should be equal to the longest pipeline name to everything lines up). This should happen even for non-parallel execution and will be helpful anyway.
- We'll need to introduce some sort of cancellation mechanism that all pipelines and modules need to adhere to. I.e., of one goes down, they should all gracefully stop. This impacts #187.

**Comment by daveaglick** [comment]
We'll need to audit all classes in the `IExecutionContext` for thread safety. For example, the current `Trace` class probably isn't totally thread-safe (I.e., the indent level is just a simple `int`).

**Comment by daveaglick** [comment]
Changes to the `Trace` class to make it static and thread safe have been made in a branch and will be be merged to master with the next release.

**Comment by deanebarker** [comment]
So, here's my concern...

I think the number of applications of Wyam using parallel processing to any extent in particular will be very low. Something on the order of a single-digit percentage.  So I worry about making huge concessions for this when very few people are likely to use it.

Parallel processing needs to be "turn off-able."  I have a situation right now that will _not_ work with parallel processing.  Certain pipelines have to complete before other pipelines can start.

**Comment by daveaglick** [comment]
I agree this is probably more of an edge case. _If_ I get it to work to my satisfaction, it will certainly always by opt-in. I.e., pipelines will always run sequentially unless a command-line argument turning on parallel processing (or a flag on the `Engine` if embedding) is set.

Note that this doesn't change the parallel processing modules already do internally - that will stay the same as it is now regardless. Also note that modules within a given pipeline will always run sequentially too.

**Comment by deanebarker** [comment]
What would be neat is if you could "group" pipelines for parallel processing.  In my particular application, about half the modules could go in Group 1 and the other half in Group 2.  All of Group 1 can run in parallel, and all of Group 2 can run in parallel, but _all of Group 1 needs to finish before Group 2 starts_.

So, modules _within_ a group can run in parallel.  But the groups themselves need to run sequentially.

**Comment by deanebarker** [comment]
Speaking of my application in particular, I just realized there would be another group, and it doesn't matter when that executed.  So, completely renaming the groups from the prior comment, it looks like this, conceptually.

```
Group 1
  Group 1.1 --> Group 1.2
Group 2
```

Group 1 and Group 2 can start in parallel.  But all the pipelines in Group 1.1 need to complete, _then_ Group 1.2 can begin.

**Comment by deanebarker** [comment]
This may be out there...but did you ever consider "chaining" configs?  So, you can "call" a completely separate config to execute and then return?

Group 1.1 might be its own config, which executes then calls Group 1.2, ensuring that they run sequentially.

**Comment by daveaglick** [comment]
:sparkles: I like this idea - a lot. And I think it could be combined with the `.DependsOn()` concept as well. I.e., modules can either be in a group (in which case they will have an implicit dependency on the previous pipeline in the group as well as any additional explicit dependencies) or not in a group (in which case they will be implicitly in their own group). When you run in parallel mode, the system will figure out the dependency graph for all pipelines based on implicit dependencies from the group as well as additional explicit dependencies.

**Comment by daveaglick** [comment]
RE chaining - see the discussion in #73, and specifically my second comment which lays out how I think it should work. TL;DR: I'd like support for included config files with multiple levels of nesting, and each included config should be able to manipulate all three sections of the overall config (setup, declarations, and main config body).

**Comment by daveaglick** [comment]
Implemented in vnext
