### ISSUE TITLE
Execute module needs to accept delegates that don't require return value

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#194]
For example, right now we can't write `Execute((doc, ctx) => Console.WriteLine(doc["Key"]))`.

**Comment by deanebarker** [comment]
I had this same question.  Sometimes, I just want to...well._execute_ something, not necessarily affect the pipeline in any way.  What I was doing was this:

`Execute((d,c) => { Console.WriteLine("whatever"); return d; })`

This works, but it seems silly.
