### ISSUE TITLE
Add Modules module for reuse

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#197]
This should be a simple one. Add a new `Modules` module that simple wraps other modules and executes them in sequence when executed. This will make it much easier to make reusable chains of modules:

```
Modules commonTextReplacement = Modules(ModuleA(), ModuleB(), ModuleC());
Piplines.Add("A",
    ModuleX(),
    ModuleY(),
    commonTextReplacement,
    ModuleZ()
);
```

**Comment by LokiMidgard** [comment]
:+1: I didn't know what I was missing.

**Comment by deanebarker** [comment]
The person who requested this is likely intelligent, charming, and -- quite clearly -- virile.

**Comment by daveaglick** [comment]
:laughing: Literal LOL

**Comment by deanebarker** [comment]
Confirmed that this works well.

**Comment by daveaglick** [comment]
...and just when you've gotten used to it, I'm going to change the name of the module to `ModuleCollection`. There's good reasoning: it occurred to me that calling it `Modules` will conflict with the `Wyam.Core.Modules` and `Wyam.Common.Modules` namespace names causing you to have to fully-qualify the class name anywhere outside the config file (like in an extension). On reflection, I think `ModuleCollection` is also a little clearer on the whole. Hopefully the change will get done today or tomorrow...

**Comment by deanebarker** [comment]
Yeah, I found out about the name change the hard way. No worries. Your reasoning makes sense.

**Comment by deanebarker** [comment]
Note that I've found myself using ModuleCollections for single modules.  It's handle to concentrate the configuration of a module that you expect to use again and again -- I do this for `Execute` modules that use the same `DocumentConfig`, for example.  Instead of configuring it multiple places, you just configure it once as a variable.

Perhaps not the expected usage, but helpful nonetheless.

**Comment by daveaglick** [comment]
Oh, very interesting - I'll add that use case to the documentation for the module, I can see others finding it very helpful
