### ISSUE TITLE
Audit cloning uses and figure out when to create new documents

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#199]
Lots of good discussion in here - repurposed issue to figure out what to do about clone vs. new documents and make those changes.

Issue was formerly:
Now that we can create new documents with `IExecutionContext.GetNewDocument()` it might be helpful to add a unique ID to each newly-created document. A GUID should serve well for this. These IDs should remain the same for each cloned document so that they can be used to trace a document through the system.

**Comment by deanebarker** [comment]
This...

```
ReadFiles(@"Content\Posts\*.md"),
Trace((d,c) =>  d.Id)
```

...outputs the _exact same Guid_ to the console, for however many documents were in the pipeline.

Is that right?  How come each document is carrying the same Id?

**Comment by daveaglick** [comment]
It's because of this line:
https://github.com/Wyamio/Wyam/blob/develop/src/Wyam.Core/Modules/IO/ReadFiles.cs#L151

ReadFiles, like most of the other modules, clones the input document instead of creating a new one. For the most part, this is a relic of the days before we even could create new documents and they all had to be cloned.

On the other hand, I'm still having a philosophical struggle with myself over the "right way" for these modules to behave. On the one hand, I think it makes sense for a module like ReadFiles to just get new documents. On the other hand though, I could envision scenarios where the input(s) to the ReadFiles module contain metadata that you want to pass on. Getting new documents instead of cloning them would erase that information.

This gets back to the comment of auditing all the clone calls to see if they should really be new documents. I suspect it'll be a case-by-case kind of thing. Any thoughts?

**Comment by deanebarker** [comment]
So, ReadFiles just clones the single, "phantom" input document?  Well, that would certainly render the value of a unique ID pointless, I guess.

I suspect these modules will need to be changed. `ReadFiles` shouldn't be "basing" its output on any input, since it's a "genesis" module.  It's a module from which _new_ documents spring forth. I think this is a fundamentally different type of module than one that just "refines" an existing set.

How do you want to codify the differences between "genesis" modules and everything else?

**Comment by daveaglick** [comment]
A part of me still wonders if the whole idea of creating new documents was a mistake and documents should only ever be cloned...

**Comment by deanebarker** [comment]
Explain the philosophical basis behind that?  Creating new documents for "genesis" situations seems like the obvious solution. `ReadFiles` is _creating something from nothing_, not refining something that exists already.  I think this is an important, base, unavoidable difference in modules.

**Comment by daveaglick** [comment]
I think you've got it - there's a difference between modules that are intended to create new things and those that process existing ones. Might just be a documentation notation for now, but perhaps there's an opportunity to use a different/sub/extra interface or something to formalize the distinction.

**Comment by daveaglick** [comment]
Even in the ReadFiles case the distinction isn't cut and dry though - notice that ReadFiles actually operates for every input document and it's possible to use a delegate to get the path(s) that you want to read from input document metadata. In that case, is the module still a "genesis" module that creates fresh documents or should that input metadata be preserved because it contains valuable information?

**Comment by deanebarker** [comment]
If that's the case, then perhaps it has to be specified?  How about an `AsNewDocument()` method?

**Comment by daveaglick** [comment]
That's along the lines of what I was thinking too - only the script author is going to know if that metadata is important enough to retain. I can think of three options:
- Add a fluent method to certain modules like ReadFiles where it could go either way and just have it set a flag internally that the module would use to either clone or new as appropriate.
- Make a more universal extension method that operates on some (as indicated by an extra interface) or all modules and utilizes a more infrastructure based approach (I.e., the pipeline knows if the module wants cloned or new documents and does the appropriate behavior without the module needing to know).
- Make new documents for modules like ReadFiles exclusively (and document as such) but then provide a wrapping module that can "join" the new documents back with the inputs.

Right now, leaning towards the first option - it will be easiest and clearest and will be fastest to implement, but wanted to include all my thoughts here in case we need to come back and revisit later.

**Comment by deanebarker** [comment]
I feel like an extension method on `IModule` called `ForceNewDocuments` or `AsNewDocuments` is the way to go.

It would set an internal flag. It would be the responsibility of the module author to use it correctly.  For many modules, it clearly wouldn't apply, but it's universal enough that it transcends specific modules, in my mind.

I would hate to implement this for `ReadFiles` one way, then another way for something else, etc.  This is something that speaks to the core of the _idea_ of a module in the abstract.

**Comment by daveaglick** [comment]
How about an interface:

```
public interface INewDocumentModule<TModule> where TModule : IModule
{
    TModule WithNewDocuments(bool newDocuments);
}
```

This keeps the public API consistent, but leaves the implementation of new vs. clone documents up to the module. Of note, this interface assumes the default behavior is to clone and you need to opt-in to get new documents - should it be the other way around for modules like ReadFiles?

**Comment by deanebarker** [comment]
I think this is a problem because with an interface, a module _is_ or _is not_ a Genesis Module, and this is controlled by the module author (by which interface they implement).  That decision is binary and set.

`ReadFiles` can be either, depending on the particular pipeline. And it might be implemented both ways in the same config, in fact.

**Comment by daveaglick** [comment]
That's actually why I think the interface would work well - it would be in addition to the normal `IModule` interface (not instead):

```
public class ReadFiles : IModule, INewDocumentModule<ReadFiles>
{
    public IEnumerable<IDocument> Execute(...) { ... }
    public ReadFiles WithNewDocuments(...) { ... }
}
```

**Comment by deanebarker** [comment]
What about situations where you need both types, in different pipelines?

**Comment by daveaglick** [comment]
The presence (or absence) of the fluent method in each module instantiation would indicate what you want:

``` C#
Pipelines.Add("Posts",
    // Creates new documents for each file
    ReadFiles("/some/path/*")
        .WithNewDocuments(),
    DoSomething(),
    DoSomethingElse()
);
Pipelines.Add("Stuff",
    DoSomething(),
    // Clones from the input document for each file
    ReadFiles(@doc.String["PathToRead"]),
    DoSomethingElse()
);
```

**Comment by deanebarker** [comment]
If you use a fluent method, then I'm fuzzy on what you need the interface for. Why both?

**Comment by daveaglick** [comment]
> Why both?

Technically you could just give all applicable modules a fluent method with the same signature. The interface just enforces the exact same signature for all implementors so the public API is consistent - you're right though, it's not strictly necessary.

You've got me thinking back to the idea of an extension method though. If we used one that applies to any module, then we could "intercept" any calls to `.Clone()` from that module and instead make them create new documents, no per-module changes needed. That seems attractive because it's more global (who knows when you might want to trigger new documents instead of clones from, say, the Razor module?).

Let me play with the options a little and then you can take a look at what I come up with to see if it fits your real-world use cases...

**Comment by daveaglick** [comment]
BTW - thanks for the great back and forth on this, it's awesome to have these kinds of deep-dive discussions with someone when thinking about new features.

**Comment by deanebarker** [comment]
> Let me play with the options a little and then you can take a look at what I come up with to see if it fits your real-world use cases...

I actually have a half-jacked implementation right now that was kind of depending on a unique ID being available.  I might temporarily make `Id` writable in my build, and set it to a new Guid via `Execute` just to keep moving it forward.

(Pretend you didn't read that.)

**Comment by deanebarker** [comment]
If you can hear your code audibly crying right now...

```
ReadFiles(@"Content\Posts\*.md"),
Execute((d,c) =>  { d.Id = Guid.NewGuid().ToString(); return d; })
```

...that's why.  :-)

**Comment by daveaglick** [comment]
Haha - I thought I felt a disturbance in the force...

I thought about this a lot this morning - I've actually come full circle back to your original suggestion and think I've got a plan now, let me know what you think.
- I'll create a generic extension method called `AsNewDocuments()` that can apply to _any_ module.
- When you use the extension on your module, what actually happens is that the module instance is added to a thread-safe hash in the engine so it knows which modules have requested to create new documents no matter what.
- Both `IDocument.Clone()` and `IExecutionContext.GetNewDocument()` methods will go away in favor of a series of `IExecutionContext.GetDocument()` overloads.
  - Some of these will be guaranteed to get a new document no matter what (I.e., the method signature won't have an argument for an existing document).
  - Others will have an `IDocument` argument and _may_ return a clone or a new document depending on if `AsNewDocuments()` was used on the module.
- All uses of `IDocument.Clone()` will be audited to see if they're appropriate. Specifically, some modules like ReadFiles will always return new documents under certain situations.
  - For example, if you use ReadFiles with a plain old path and you don't pull data from the input documents, it doesn't make sense to iterate all the input documents and clone them - the documents it creates will all be new with new IDs.
  - On the other hand, if you use ReadFiles with a delegate that makes use of metadata in the input document(s), then it does make sense to iterate those input documents and clone them for the newly read content by default unless `AsNewDocuments()` was used for the module, in which case they would also be new documents with new IDs.
- This effectivly means `AsNewDocuments()` _may_ force a module that would normally clone to create new documents, but a module that would have created new documents to begin with will continue to do so.
- Whether a given module with a given constructor returns clones or new documents will need to be well documented.

**Comment by deanebarker** [comment]
I like the idea in theory.  Some of the specifics require a level of intimacy with the code that I don't have (I'm just a writer, remember...), but it sounds like a good solution on the surface.

**Comment by daveaglick** [comment]
:+1: Was more looking for a gut reaction to the way it will impact config files, which basically boils down to using `AsNewDocument()` if you want to guarantee new documents.

The behind-the-scenes stuff won't be too hard from a coding perspective, I just included those notes as reminders to myself. I tend to get a mental image of how architecture problems should be solved and then lose it a day later if I don't write it down.

**Comment by deanebarker** [comment]
Oh, that part is good. It's consistent with the other config.

**Comment by daveaglick** [comment]
Working on this now - turns out it's a little related to #183 as they both have to do with creation of documents. I'll probably end up implementing a factory pattern for documents to get this one working which will also get us part of the way there for strongly-typed documents.

**Comment by daveaglick** [comment]
@deanebarker As I'm working through this, it's becoming clear that the `.AsNewDocuments()` concept just doesn't make sense for some modules. For example, GroupBy would return new documents with the grouping metadata but without the template content. I'm having a hard time envisioning why someone would ever want that behavior. Perhaps we should go back to the idea of introducing a `IAsNewDocuments` interface for the extension to use that will make it opt-in for specific modules where it makes sense. Thoughts?

**Comment by daveaglick** [comment]
Another example of one where it might not make sense to get new documents is WriteFiles. In that case, the module adds metadata related to where the file was written to each input document. If you used `.AsNewDocuments()` on it you would get back just the metadata for the write operation but nothing else. Maybe there's a use case for that - I'm not sure?...

**Comment by deanebarker** [comment]
Oh, I agree.  This goes back to our discussion about "Genesis modules."  Some modules generate documents from nothing, others don't. This is clearly module specific, so I guess an interface makes sense.

**Comment by daveaglick** [comment]
This is now resolved with the merging of the feature branch into develop - biggest change is that all new documents must be obtained via `IExecutionContext.GetDocument()` overloads, regardless of whether cloning or creating new ones.

It's enabled on the backend by the introduction of a document factory pattern.

This should make implementing strongly typed documents from #183 much easier.

**Comment by deanebarker** [comment]
This works well.  All `Id` values are now nicely unique.  I was able to remove my hack which made `Id` writable so I could set it with the `Execute` module.
