### ISSUE TITLE
Add IMetadata.Documents()

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#200]
Similar to new `IMetadata.Document()`. Now that we're using documents to represented nested metadata structures more, it makes sense to have a very easy way to return them from the metadata.

**Comment by deanebarker** [comment]
I was actually gonna ask for this.  I have an actual use case here. Implement and I'll give it a real-world test.

**Comment by deanebarker** [comment]
I'm thinking of a module:

`ParseSubdocuments("===")`

This would iterate the pipeline, parse out subdocuments, and then add them to the Documents property of their parent.

But how do we handle module processing on a document with subdocuments?  What if those subdocuments have subdocuments?  Every document could essentially be a "tree" of documents.  This is powerful (and a common pattern of content), but every module will have to recurse down the tree.

**Comment by daveaglick** [comment]
@deanebarker Ah - that takes it quite a bit further than I had originally envisioned. My thought for this particular enhancement was just a simple shortcut for writing (in a Razor template):

```
Model.Get<IEnumerable<IDocument>>("Posts")
```

instead you can write:

```
Model.Documents("Posts")
```

What you're describing sounds an awful lot like #150 - how does that issue line up with what you were thinking?

**Comment by deanebarker** [comment]
Ah, I see.  Yes, #150 is what I was discussing.
