### ISSUE TITLE
Explicitly specifying <guid> for RSS items

### ISSUE THREAD

**Issue by deanebarker** [statiqdev/Statiq#205]
I'd like to change the RSS module to allow the explicit specification of the `guid` element.  Two options (perhaps both...)

`WithGuidMetaKey(string key)`

And/or:

`WithGuid(DocumentConfig execute)`

Let me know your thoughts/preferences, and I'll submit the change.

**Comment by daveaglick** [comment]
I like the idea of having both - but I would just use overloads of a single method `WithGuid()`

**Comment by daveaglick** [comment]
As long as the argument for the metadata key overload is named something like `metadataKey` and it's documented that this overload gets the value for a key (and isn't itself a GUID), I think it'll be clear.

**Comment by deanebarker** [comment]
Yeah, I went with `WithGuidMetaKey` just to be consistent with the other methods.  I have no problem doing an overload, but then you would supply a Guid meta key using a different method naming style than all the other methods.  Any concerns with this?

**Comment by daveaglick** [comment]
Good point. On my phone so didn't notice the other methods. Let's be consistent and go with your original idea.

**Comment by deanebarker** [comment]
Pull request #206.  I was a little less ambitious and just made "RssGuid" the magic meta key and `WithGuidMetaKey` the method for changing it.  The `DocumentConfig` method is probably not necessary, since `Meta` could be used to just set that meta key.

**Comment by daveaglick** [comment]
That implementation sounds fine - module enhancements are generally easy enough to address as needs arise, so if someone out there needs the delegate version we can always add it later.

**Comment by daveaglick** [comment]
Closed via #206
