### ISSUE TITLE
Take Module

### ISSUE THREAD

**Issue by deanebarker** [statiqdev/Statiq#208]
I think we need a "Take" module to emulate the "Take" function of LINQ.

Use case: in my RSS feed, I just want the first 10 posts.  I do this:

```
Documents("PostsContent"),
OrderBy((d,c) => { return d.Get<DateTime>("Date"); }).Descending()
Index(),
Where((d,c) => { return (d.Get<int>("Index") <= 10); }),
```

I set an index with `Index()`, then have to evaluate it.

A lot of work, when this would be so much easier:

```
Take(10)
```

**Comment by daveaglick** [comment]
Makes total sense, especially since we already have other LINQ-like modules like GroupBy, If, etc.

**Comment by deanebarker** [comment]
Pull request #211.
