### ISSUE TITLE
The pipeline excecution validation / errors

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#212]
More of a question or think with me thing :)

Say is there any way to understand of the pipeline has no errors? Here is why there may be potential interest to that thing:
- With the huge sites we'd like to stop the pipeline execution on errors
- With the 'publishing' workflow straight to dev/uat/prop environments  we'd like to stop the pipeline execution on errors
- Same-same with the "publish on commit to github" we'd like to stop the pipeline on errors

I see at least two point here:
- be able to construct the pipeline with if/else logic based on the errors
- be able to understand within the module if there were errors early (say, the module published the content to Amazon S3, so if there were errors it won't publish stuff)

Next, the error reporting becomes a critical one. With large sites (well a few hundreds pages) it may be painful to troubleshoot what went wrong. Not only the execution needs to return -1 as an outcome (there was a ticket and it was implemented), but also trace / log errors somehow / somewhere. 

Well, errors can be pushed to the file or something, and that's fine. Should that be some kind of module too? Where and how we would push errors? Like, into the file, the console output or somewhere else? - that kind useful for the CI/CD scenarios. Say with appveyour / Octopus deployment we are't interested in files, we are interested in the console output, and with the local dev/test environment we might be interested in files, yea.

Have no idea how to handle all that yet, so sharing all that here. Hope that makes sense.

**Comment by deanebarker** [comment]
There are two different things here:
1. The current pipeline
2. The overall execution

The execution is usually made up of multiple pipelines.  And it should stop on an error.  If a pipeline throws an unhandled exception, the entire execution should abandon. This was covered back in #187.

**Comment by avishnyakov** [comment]
Well, makes sense.

However we see sometimes things like "can't get access to a file" or something, and the pipeline is still being executed "successfully". In particular that brings issues with old css/js/html files not being overwritten. Wyam traces it in the console output as warning or something and gives "success". That's actually not true. That made me post thins question here.

**Comment by deanebarker** [comment]
I went looking through the module, and the Obsolete attributes all over the place reminded me that Dave is re-writing this functionality into a new IO abstraction layer, so it's all going to change sometime soon.

I'm still surprised that it doesn't stop execution. Based on my reading of the CopyFiles modules, `SafeIOHelper` should throw an unhandled exception if it fails to copy a file five times.

**Comment by daveaglick** [comment]
@avishnyakov Are you on an old version or release? The SafeIOHelper combined with #187 which changes the exception handling behavior to stop execution on any errors from any pipelines as soon as they happen should be enough to cancel if something goes wrong (including file access errors).

And @deanebarker is right - I'm adding an entire IO abstraction layer which will remove the need for direct `System.IO` use and will also contribute to better error handling.

Long story short, any exception at any time should kill the build. If using the console application it should also report an error code so CI processes stop. If using embedded, the exception should be rethrown so the calling application can exit gracefully. This is a bit stricter than it used to be, but I think it makes more sense - if the build fails, it fails. There's no middle ground.

There may be one or two areas where exceptions are being handled and really shouldn't be. I thought I got them all, but let me know if you come across a specific case where there's an error that should kill the build and doesn't.

**Comment by daveaglick** [comment]
The IO abstraction is done, as well as a variety of other improvements. We've come a long way since this issue so I suspect it's resolved. Feel free to request I reopen it if needed.
