### ISSUE TITLE
Windows Clipboard IO Doesn't Work

### ISSUE THREAD

**Issue by deanebarker** [statiqdev/Statiq#218]
Just for giggles, I tried to add two new modules:

```
ReadFromClipboard()
WriteToClipboard()
```

The idea was that Wyam would read text had been copied, manipulate it, and write it back.

For the record, it doesn't work.  Clipboard IO can only be done with single threading.  You need to decorate the `Main` method in the EXE with `[STAThread]` which is clearly a problem.

This is just an informational issue.  I tried it, but it doesn't appear it can or ever will work with Wyam.

**Comment by deanebarker** [comment]
You can close this "issue," @daveaglick.  It's informational only.

**Comment by daveaglick** [comment]
Yeah, unfortunately this is probably a non-starter (cool idea though). That'll be especially true when it's time to make the jump to .NET Core and cross-platform.
