### ISSUE TITLE
Add the ability to "test compile" the config

### ISSUE THREAD

**Issue by deanebarker** [statiqdev/Statiq#221]
We should have the ability to ensure the config will compile, without running a build.  Sometimes, when modifying the config, it would be handy to simply make sure the syntax is correct and free from potential compilation error, without actually executing.

A command line switch for `--verify-config`?

**Comment by deanebarker** [comment]
I have this implemented.

Command switch: `--verify-config`

Result:

```
---------- Wyam Build ----------
Wyam version 0.11.1-beta
[ASCII Art...]                           
Loading configuration from C:/Code/Robots/config.wyam
No errors. Exiting.
```

It returns `ExitCode.Normal`.

Other than accepting the new command line switch, the code is pretty simple.  Immediately after configuration:

```
if(_verifyConfig)
{
   Trace.Information("No errors. Exiting.");
   return (int)ExitCode.Normal;
}
```

Let me know if you're okay with this, and I'll submit the pull request.

**Comment by daveaglick** [comment]
This is excellent, yes please!

(BTW - lots of good activity this morning, I'm swamped with meetings right now, but will hopefully be able to do some merges, coding, and commenting later today.)

**Comment by deanebarker** [comment]
Pull request is in.  And I don't mean to brag, but I created another branch and made sure it was _only_ this change, and not the other changes too.

![](http://cdn.meme.am/instances/400x/63113523.jpg)

**Comment by daveaglick** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1020407/13021891/993c99cc-d1ab-11e5-9c4b-2b45747abbaf.gif)

Closed by #223

**Comment by deanebarker** [comment]
Do not start a GIF war with me, Glick. You have been warned.

**Comment by daveaglick** [comment]
Haha - I have Giphy in my quick launch, ready to roll at a moment's notice
