### ISSUE TITLE
CLI: Background color doesn't reset when exception occurs.

### ISSUE THREAD

**Issue by miere43** [statiqdev/Statiq#229]
![2016-02-16_14-40-04](https://cloud.githubusercontent.com/assets/3995549/13075342/8f60f0ac-d4bb-11e5-8ebb-c7c08846212b.png)

**Comment by daveaglick** [comment]
Yikes!

**Comment by miere43** [comment]
Looked at code, it's fine, seems to be it appears randomly and its can be fixed by restarting PowerShell. I'll close the issue if I didn't figure it out.
