### ISSUE TITLE
CLI: Stack trace doesn't being highlighted when verbose mode turned on

### ISSUE THREAD

**Issue by miere43** [statiqdev/Statiq#230]
See `Exception: System.AggregateException: ...`. This string should be in red.

![2016-02-16_14-45-05](https://cloud.githubusercontent.com/assets/3995549/13075407/f68e7506-d4bb-11e5-8235-f31f392c4208.png)

**Comment by daveaglick** [comment]
Yeah, probably should be - or maybe even a dedicated color for stack traces...
