### ISSUE TITLE
Unable to specify current folder as input folder

### ISSUE THREAD

**Issue by martinvobr** [statiqdev/Statiq#231]
I'm unable to specify current folder as an input dir in version 0.11.2-beta. It used to work in 0.11.0-beta.

Command line used:
wyam -i .

Symptoms:
- wyam.exe lists two input folders: "input" and the one specified in a command line. (expected: only input folder specified in a command line)
- folder ".\input" is created. (not expected)
- content of the current directory is ignored. (should be processed)
- when debugging ReadFiles module it looks like ".\input" is passed as input directory instead of ".\".

Configuration file used:

```
// Setup code

===
// Configuration code

---

Pipelines.Add("ContentTest",
    ReadFiles("*.cshtml"),
    WriteFiles(".html")
);

```

Repro:
- Download and unpack http://www.vobr.cz/wyam/wyam-input-from-current-dir-repro.zip 
- Run .\run.cmd which NOT uses current dir as an input dir. It outputs 1 document.
- Change dir to input and run run.cmd from the dir. It outputs 0 documents.

**Comment by daveaglick** [comment]
Thanks - I'll take a look later today. A lot of the IO stuff is being refactored to a new virtual file system abstraction to support a new theming engine as well as enable some other cool scenarios. Unfortunately, there a probably going to be a couple bugs along the way... Thanks for the detailed report and repro.

**Comment by martinvobr** [comment]
Just addding workaround mentioned by @daveaglick in https://github.com/Wyamio/Wyam/issues/241:

> A temporary workaround is to remove the default "input" path from the collection. Add the following to the setup (the very top where you add assemblies, etc.) portion of your config:

```
FileSystem.InputPaths.Remove("input");
```

**Comment by daveaglick** [comment]
Thanks for linking the two issues. I've been swamped at work for the last couple weeks, so my issue triage isn't as good as it normally is. I'm hoping to have this squared away in the very next release.

**Comment by daveaglick** [comment]
The command line now correctly handles specifying input paths and removes the default one if any are explicitly specified. In the next minor release, you should be able to remove the `FileSystem.InputPaths.Remove("input")` workaround.
