### ISSUE TITLE
Sharing wyam config between PS script and C# unit test / app

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#238]
What be he best way to have *,wyam config and be able to run Wyam from both PS script AND c# unit test or C# app?

Can see that pipeline can be configured via C#, but we'd like to have ability to run Wyam via PS/bat file locally. And then also be able to run the same config under C# unit test (say CI on the build controller).

What the way to get it done?

**Comment by daveaglick** [comment]
Depending on your unit test framework, you could reference the tools NuGet package (which brings down the executable and supporting libraries) and then just launch a process. That's exactly how the the examples test library in Wyam itself works. Then just run the same config from PS like you normally would.

Tools package: https://www.nuget.org/packages/Wyam/0.11.2-beta

Example unit test code: https://github.com/Wyamio/Wyam/blob/develop/src/Wyam.Examples.Tests/ExamplesTests.cs

**Comment by avishnyakov** [comment]
Woohooo. Looks like that's exactly what we need. Let me give it a shot, and many thanks for pointing out. Wyam rocks!

**Comment by daveaglick** [comment]
:thumbsup:

Just reopen this issue if it looks like it's not working out.

**Comment by avishnyakov** [comment]
Weird, did install-Package Wyam -Pre and got it installed without errors.
However can't see any Wyam assemblies or exe anywhere.

**Comment by daveaglick** [comment]
It should all install into a "tools" subfolder - that's an artifact of the way NuGet handles exe/tools packages. Let me know if you don't see it there - possible something is messed up with the package... I'll reopen this until you get it squared away.

**Comment by daveaglick** [comment]
(BTW, the reason the examples test doesn't need to call wyam.exe from the tools folder is because its referencing the console project directly since it's in the same solution)

**Comment by avishnyakov** [comment]
Could be some kind of glitch, still can't see tool folder. 
VS2015, the latest NuGet Wyam package.

**Comment by daveaglick** [comment]
Maybe this will help: https://lostechies.com/joshuaflanagan/2011/06/24/how-to-use-a-tool-installed-by-nuget-in-your-build-scripts/ - it looks like it installs in a subfolder of the full package name with version (I'm kind of new to using tools packages)

**Comment by daveaglick** [comment]
@avishnyakov Were you able to get this working? Was it just a matter of finding the correct location of the tools folder?
