### ISSUE TITLE
Wyam working folder

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#239]
Once running wyam, what is the logic behind "current / working" folder?

Say the Wyam config has the following line aiming to load all assemblies that live /bin/debug in relation to Wyam.config file.

``` cs
Assemblies.LoadDirectory(@"bin\Debug");
```

Working well once Wyam is run from the same folder as config, and surely fails once it is run somewhere outside. Should we setup the current folder outside of Wyam or should Wyam sets it based on the config file location?

**Comment by daveaglick** [comment]
All relative paths are combined with `Engine.RootPath`, which is initially set to `Environment.CurrentDirectory`, I.e., the path the exe was run from (see https://github.com/Wyamio/Wyam/blob/develop/src/Wyam/Program.cs#L82). If running somewhere other than where the config file is, the root should get set when you provide a path.

All the IO is being refactored right now, so there may be bugs. What command arguments are you using?

**Comment by avishnyakov** [comment]
Something like that,  where {0} is full path to the folder.

```
--input \"{0}\\Views\" --output \"{0}\\Views-Output\" --config  \"{0}\\_site.wyam\" --verbose
```

Running Wyam from other than {0} folders.

**Comment by daveaglick** [comment]
I see. Try setting the root path (as the final argument) and then setting the other ones from that:

```
--input \"Views\" --output \"Views-Output\" --config  \"_site.wyam\" --verbose \"{0}\"
```

That should make it behave as if you ran it from the {0} path.

**Comment by avishnyakov** [comment]
Magic! Can I buy you a coffee? Works as a charm with the last arg. Woohoo, 0.11.1-beta rocks.

**Comment by daveaglick** [comment]
No problem :smile: - this behavior could be documented better, I'll make a note...
