### ISSUE TITLE
ReadFiles with 0.11.2-beta can't find documents or misses recursive option

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#241]
The following config can't find documents:

```
Pipelines.Add("site-md-content-1",

    ReadFiles("*.md"),

    FrontMatter(Yaml()),
    FileName("FileName").WithAllowedCharacters(new[] {".", "-"}),

    Markdown(),
    Razor(),    

    WriteFiles(".html")
);

return;
```

Here is the output:

```
Wyam version 0.11.2-beta
Root path:
  C:/_sps_tfsonline/Mint.Docs/X.Ecosystem/X.Docs
Input path(s):
  input
  C:/_sps_tfsonline/Mint.Docs/X.Ecosystem/X.Docs/Views
Root path:
  C:/_sps_tfsonline/Mint.Docs/X.Ecosystem/X.Docs/Views-Output

Cleaning output path C:/_sps_tfsonline/Mint.Docs/X.Ecosystem/X.Docs/Views-Output
Cleaned output directory
Executing 1 pipelines
    Executing pipeline "site-md-content-1" (1/1) with 6 child module(s)
        Executing module ReadFiles with 1 input document(s)
            Executed module ReadFiles in 39 ms resulting in 0 output document(s)
        Executing module FrontMatter with 0 input document(s)
            Executed module FrontMatter in 4 ms resulting in 0 output document(s)
        Executing module FileName with 0 input document(s)
            Executed module FileName in 4 ms resulting in 0 output document(s)
        Executing module Markdown with 0 input document(s)
            Executed module Markdown in 1 ms resulting in 0 output document(s)
        Executing module Razor with 0 input document(s)
            Executed module Razor in 17 ms resulting in 0 output document(s)
        Executing module WriteFiles with 0 input document(s)
            Executed module WriteFiles in 4 ms resulting in 0 output document(s)
        Executed pipeline "site-md-content-1" (1/1) in 101 ms resulting in 0 output document(s)
    Executed 2/1 pipelines in 106 ms
Preview server listening on port 5080 and serving from path C:/_sps_tfsonline/Mint.Docs/X.Ecosystem/Y.Docs/Views-Output
Watching paths(s) input, C:/_sps_tfsonline/Mint.Docs/X.Ecosystem/Y.Docs/Views
Watching configuration file C:/_sps_tfsonline/Mint.Docs/X.Ecosystem/Y.Docs/_site.wyam

```

Input folder " C:/_sps_tfsonline/Mint.Docs/X.Ecosystem/X.Docs/Views" is full of *.md files - 1 at the top level (index) and tons under nested folders.

**Comment by avishnyakov** [comment]
Arrh.... c'mon..  1 doc found and nothing written?

```
Pipelines.Add("site-md-content-1",
    ReadFiles("*.md"),
    WriteFiles(".html") 
);
```

Output:

```
Executing 1 pipelines
    Executing pipeline "site-md-content-1" (1/1) with 2 child module(s)
        Executing module ReadFiles with 1 input document(s)
            Executed module ReadFiles in 27 ms resulting in 0 output document(s)
        Executing module WriteFiles with 0 input document(s)
            Executed module WriteFiles in 4 ms resulting in 0 output document(s)
        Executed pipeline "site-md-content-1" (1/1) in 53 ms resulting in 0 output document(s)
    Executed 2/1 pipelines in 57 ms
```

**Comment by avishnyakov** [comment]
Wyam version 0.11.1-beta works as expected:

```
Pipelines.Add("site-md-content-1",
    ReadFiles("*.md"),
    WriteFiles(".html") 
);

  Executing pipeline "site-md-content-122" (1/1) with 2 child module(s)
        Executing module ReadFiles with 1 input document(s)
 HUNDREDS  Read file XXXXX.MD here

```

Seems like ne ReadFiles does not resolve path correctly as no "Read files" is written to the trace in 0.11.2-beta.

Folks, either this is kinda cool or my simple config ReadFiles / WriteFiles is terrible wrong :)

**Comment by daveaglick** [comment]
Pretty sure I know what's going on here - it's an artifact of part of the system being switched to the new abstract IO classes and the other part still using the old stuff. There's a temporary bridge between them, but it's obviously got some weak spots.

Notice how there are now two input paths. ReadFiles will eventually read from the aggregate of all input paths, but for now it looks like it's just reading from the first one. A temporary workaround is to remove the default "input" path from the collection. Add the following to the _setup_ (the very top where you add assemblies, etc.) portion of your config:

```
FileSystem.InputPaths.Remove("input");
```

This will be fixed in the next release so you'll be able to take that line back out. We're in a pretty big state of flux right now. I'm all for helping work through the issues that you find, but if you need stability, might be better off sticking with 0.11.1 until the new IO stuff is totally up and running.

**Comment by avishnyakov** [comment]
Sure, not a problem.

The question on how it passed regression tests (if any) is logically arises. ReadFiles kind fundamental thing in the whole set of the modules. Anyway, appreciate the feedback, and Wyam is still cool :)

**Comment by daveaglick** [comment]
The whole multiple input paths thing isn't complete yet and so there isn't a full set of tests for it. Specifically, the existing tests assume a single input path (which is how it used to work) and don't consider paths beyond the first yet. This is all a work in progress and it's going through some growing pains in the 0.11.x release line. The good news is that once we hit 0.12 it'll be in a _much_ better place to continue growing and looking at things like deployment and user experience issues.

**Comment by daveaglick** [comment]
The command line now correctly handles specifying input paths and removes the default one if any are explicitly specified. In the next minor release, you should be able to remove the `FileSystem.InputPaths.Remove("input")` workaround.
