### ISSUE TITLE
Create an RSS feed module

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#27]
Constructs an RSS feed from the input documents. How to handle feed items from multiple pipelines (might not need to worry about it if there's also a module that can "reuse" documents from other pipelines)? How to extract the excerpt (pull from metadata or provide a `Func<IDocument, string>`)?

**Comment by daveaglick** [comment]
Note that `System.ServiceModel.Syndication` isn't yet available in .NET Core (and it's unclear when it will be).

**Comment by miere43** [comment]
I guess this one should be closed because this module already present #174

**Comment by daveaglick** [comment]
Good call, thanks again!
