### ISSUE TITLE
Rename Wyam.Modules.* libraries to Wyam.*

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#295]
Strongly considering this change. It'll be breaking, but it'll also be a mechanical fix. Reasoning is now that we have other extension mechanisms like file providers, it makes sense that a single library might contain multiple types of things. For example, the `Wyam.GitHub` module will reference Octokit and will contain both GitHub based modules and GitHub file providers.

**Comment by daveaglick** [comment]
FYI for any watchers - this change is definitely going to get made for 0.12.4-beta out this week. It's a pretty major breaking change because none of your NuGet references will continue to work. Thankfully the fix is very easy - just remove the `.Modules` part from the package name. I.e., `Wyam.Modules.Markdown` becomes `Wyam.Markdown`. This should make it easier to write and remember Wyam package names going forward and really should have been the convention from the beginning.

**Comment by LokiMidgard** [comment]
In your release notes you said you renamed `wyam.*` to `wyam.*`.

**Comment by LokiMidgard** [comment]
Not sure about this, but maybe you should also hide the `Waym.Modules.*` Packages from nuget search.
