### ISSUE TITLE
Add HTTP/HTTPS provider

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#299]
Might obsolete the `Download` module. Be sure to support both HTTP and HTTPS.

**Comment by MetalDent** [comment]
Hi, anyone working on this?

**Comment by daveaglick** [comment]
Nope, no one is working on this one...but now that you mention it I should probably close this and related issues 😬.

For context, I mentioned in the other issue you commented on that Wyam is deprecated and new development is happening in [Statiq Framework](https://github.com/statiqdev/Statiq.Framework). Statiq is a “reboot” of Wyam leveraging all the lessons learned over the last 4 years. While it’s similar conceptually a lot of the underlying architecture has changed. One of the things to get simplified was file providers - they’re no longer pluggable meaning this issue and other “new file provider” issues are essentially obsolete.

It’s kind of an awkward time for this repo. It’ll eventually move to the statiqdev org and contain a Statiq-based web site and blog generator, but in the meantime it’s here for historical purposes and the occasional Wyam bug fix. Happy to have you take a look at Statiq Framework if you want to get involved in the early-stage Statiq development.
