### ISSUE TITLE
Emulate Filesystem for Testing

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#305]
Hi,

I currently creating a Module for reading Metadata from Sidecar files. It will work like the FrontMatter Module. It is intended to add Metadata to Binary files or Textfiles that would loose syntaxhilighting when FrontMatter is applied.

Is there an Filesystem emulation somewhere already. I haven't see anything.

Ideally would be something like keyValue Pair for path content, that would be used as source and content of the created documents.

**Comment by daveaglick** [comment]
That was one of the primary drivers for the new abstraction. Check out the `Wyam.Testing` library, it should have what you need. Specifically, the testing IO abstraction is here: https://github.com/Wyamio/Wyam/tree/develop/src/Wyam.Testing/IO Most of the test code for Wyam has been rewritten to use it - a good example is at https://github.com/Wyamio/Wyam/blob/develop/src/Wyam.Modules.Razor.Tests/RazorTests.cs#L366

**Comment by LokiMidgard** [comment]
Thank you, just created #306
