### ISSUE TITLE
SearchIndex - enableStemming parameter is reversed

### ISSUE THREAD

**Issue by SteveLowe** [statiqdev/Statiq#315]
Setting the enableStemming parameter to true with the SearchIndex module disable the stemmer that comes with lunr.js.

My understanding from the docs is that it should enable the builtin stemmer when set to true.

See:
https://github.com/Wyamio/Wyam/blob/develop/src/Wyam.SearchIndex/SearchIndex.cs#L172

**Comment by daveaglick** [comment]
Thanks - I'll check it out later today.

**Comment by daveaglick** [comment]
Great catch. So "I'll check it out later today" turned into "I'll check it out in 15 days", but it's fixed in the develop branch now.
