### ISSUE TITLE
Steps to build wyam in contributing.md

### ISSUE THREAD

**Issue by M-Zuber** [statiqdev/Statiq#319]
It would nice to have explicit instructions on how to build wyam for new contributors.

I for one was not sure which `sln` file to open up for example.

**Comment by daveaglick** [comment]
:+1: This is a great idea - I'll add a `building.md` to the root of the repo and add a reference to that document from the `contributing.md` file. That should make it even easier to find build instructions even if someone isn't interested in contributing.

**Comment by daveaglick** [comment]
When you get a chance, take a look and let me know if I covered enough from the perspective of a new user. The instructions aren't long, but then the build process isn't that complicated right now.

**Comment by M-Zuber** [comment]
Looks perfect!
Thank you :tada: 
As we all know taking time to write documentation is usually the hardest part of OSS
