### ISSUE TITLE
Add document path to exception trace

### ISSUE THREAD

**Issue by M-Zuber** [statiqdev/Statiq#320]
When a module throws an exception it would be very helpful to know what document it was trying to process.

This can help with identifying if a given issue is a PEBCAK or `wyam`s fault

**Comment by M-Zuber** [comment]
I would be happy to attempt a PR if this is inline with roadmap

**Comment by daveaglick** [comment]
The challenge here is that many modules process documents in parallel which makes it hard for an outside try/catch block to know which document was being processed. A good general-purpose approach might be:
-  Create a new `Exception` class that can wrap some other extension and also contains the source of the document being processed when the wrapped exception was thrown. 
- Add try/catch blocks _inside_ the parallel code for modules that catch all exceptions and throw the new wrapping exception.
- Add a try/catch just before module execution that first checks for our new `Exception` class and displays an appropriate error w/ the source if found or a more general error if it's some other `Exception` class.

_Everything_ is "inline with the roadmap" :smile: - I'd be happy to take a look at a PR if you're interested in tackling this. Also, the idea above was just a suggestion - other ways of reporting source would be fine too.

**Comment by daveaglick** [comment]
Error messages when something blows up while processing a document should now be much, much better across the board.
