### ISSUE TITLE
Error while configuring engine: The recipe "Blog" could not be found

### ISSUE THREAD

**Issue by doefiets** [statiqdev/Statiq#327]
It's impossible to scaffold the recipe Blog.
I get the error:
Error while configuring engine: The recipe "Blog" could not be found
using 0.13.2

**Comment by daveaglick** [comment]
Yikes! Given that that's like _the_ feature in the latest release, it's not good. That error message indicates that Wyam can't find a class that implements `IRecipe` with a name of `Blog`. The actual implementation is contained in the `Wyam.Blog` NuGet package. My guess is that something is going wrong during NuGet package download or assembly loading.

Can you run it again with the `--verbose` flag and paste the entire output into this issue (I.e., `wyam new -r Blog --verbose`)?

**Comment by doefiets** [comment]
I'm thinking it maybe casued by some DNS issues at the network we use at the office.
I tried to reproduce this at home and everything went fine.

I'll try again at the office later this week. For now, please label this issue as blocked, because there's likely something else in play here.

**Comment by daveaglick** [comment]
Relabeled from a bug to a discussion since it looks like this is the result of not being able to pull down required packages on first use due to network conditions. Let me know if you get any more info on the problem - I'll swap the labels back if we get a repro. I'll also leave this open for a bit just to be sure.

**Comment by daveaglick** [comment]
I'm going to go ahead and close this one - just let me know if you're having any more problems and we can reopen it or start a new issue.

**Comment by ernestogutierrez** [comment]
Hi, I just got the same error.

I ran this command `wyam new -r Blog --verbose` to get a log of the error.

This is the part where it fails:

>  Retrieving package 'Wyam.Sass 2.2.4' from 'https://api.nuget.org/v3/index.json'.
>         Retrieving package 'Wyam.Web 2.2.4' from 'https://api.nuget.org/v3/index.json'.
>         Retrieving package 'Wyam.Yaml 2.2.4' from 'https://api.nuget.org/v3/index.json'.
>         Retrieving package 'YamlDotNet 4.3.1' from 'https://api.nuget.org/v3/index.json'.
>         Install failed. Rolling back...
>         Executing nuget actions took 16.93 sec
>     Exception while installing packages:
>     Error while installing packages, attempting without remote repositories
>     Installing package Wyam.Blog 2.2.4
>     Unexpected exception while installing packages: primarySources
>     Error while installing packages, attempting to continue anyway
>     NuGet packages installed in 25974 ms
> Loading assemblies
>     Adding already loaded assemblies to the collection
>         Added assembly System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e from C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.9\System.Private.CoreLib.dll (unknown target) to the assembly collection
