### ISSUE TITLE
LinkGenerator.GetLink support HTTPS?

### ISSUE THREAD

**Issue by leekelleher** [statiqdev/Statiq#333]
When using `Context.GetLink` (with `includeHost = true` in a template (for me I'm manually building an RSS feed from a Razor script), the URL returned is HTTP.

What are your thoughts on adding an option to also support HTTPS?

We could do this by setting the [Scheme on the UriBuilder](https://github.com/Wyamio/Wyam/blob/master/src/Wyam.Core/Execution/LinkGenerator.cs#L51).

**Comment by daveaglick** [comment]
I think that's a great idea, and a necessity given the push for HTTPS everywhere.

Should probably add a flag argument to the `LinkGenerator` method and then provide the appropriate `GetLink()` overloads in the `IExecutionContext`, etc. with a global setting in `ISettings`.

I can get this implemented and into the next version, no problem.

**Comment by leekelleher** [comment]
@daveaglick Great, thanks! Obviously not wanting to burden you with tasks. I can send a PR if you prefer? (later today or tomorrow).

**Comment by daveaglick** [comment]
@leekelleher No burden at all. This is a really easy one to knock out - I'll let you take the hard ones :wink:.

**Comment by leekelleher** [comment]
Thanks @daveaglick, it's much appreciated! :+1:

**Comment by daveaglick** [comment]
No problem!

FYI - you can use primarily by setting `Settings.LinksUseHttps = true` in the config file (figured you'd either want it on or off across the board in most cases). There's also a `IExecutionContext.GetLink()` overload that accepts a flag to turn it on. 

I briefly considered letting the user specify the whole URL scheme for links, but I couldn't come up with a single scenario where you'd want to generate links to documents for something other than the web.
