### ISSUE TITLE
 Xslt2 module not found

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#341]
Hi I tried to use the new xslt module. I just added a two to the name, but it can't the module. I deleted the tools folder. It seams that I forgot something simple but I can't figure what. I also tried to add the module via #n.

**Comment by daveaglick** [comment]
It's missing the `.nuspec` file so it wasn't packed when I did the build. Sorry, I should have caught that. I'm away from a computer today but I'll try to get it packaged and uploaded to the NuGet gallery tomorrow. In the mean time you should be able to build it and load the assembly directly with the `#a` directive.

**Comment by daveaglick** [comment]
The Xslt2 module is on NuGet now: https://www.nuget.org/packages/Wyam.Xslt2
