### ISSUE TITLE
Add KB article about rewriting on IIS

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#344]
To get extensionless URLs to work, might need to enable URL Rewrite 2.0. See https://github.com/aarondandy/mediocre.site/blob/278f7edf3ee73f9c02364df8fcfad09850863ef0/input/web.config and http://stackoverflow.com/questions/19631493/remove-html-extension-with-web-config-permanently/35523747#35523747. Also check out MIME types for RSS and Atom.

**Comment by daveaglick** [comment]
This has been added to the new docs (to be published shortly).

**Comment by elpatron68** [comment]
Hi,

are there any working rewrite rules for an Apache installation? I helped me out with

```
RewriteEngine on
RewriteCond %{REQUEST_URI} !\.(html|css|js|less|jpg|png|gif|exe|php)$
RewriteCond %{REQUEST_URI} !/$
RewriteCond %{REQUEST_URI} !/posts
RewriteCond %{REQUEST_URI} !/tags
RewriteRule ^(.*)$ $1.html
```

It doesn't look very nice, I'm sure there is a better way to do this. But it helped me out for nor.
