### ISSUE TITLE
Various issues with code highlighting and fencing in blog recipe

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#345]
From Gitter, reported by @aarondandy
- If you add a language specifier to code fences, the HTML rewriter doesn't find them and add the Prettify elements. Instead of `<pre class="prettyprint"><code>` you get `<pre><code class="language-xml">`.
- We should really be handling language specifiers in the code fence - either converting to convention Prettify understands or using a highlighter that can deal with them.
- Consider updating Prettify to latest (reports of problems loading).
- Also want to consider a different highlighter that natively works with standard Markdown fences w/ language specifier so we don't have to do the rewrite step (or see if newer Prettify supports it).

**Comment by aarondandy** [comment]
Something to consider when doing this work too. What if I want to make my own theme and want to use highlightjs.org , could I be able to write some code to override how the css classes are generated? Also note that the newer versions of pretty from https://github.com/google/code-prettify don't seem to require initialization in `onload`.

**Comment by daveaglick** [comment]
> What if I want to make my own theme and want to use highlightjs.org

Yeah, that should totally be allowed.

Best bet is to find a way to get Prettify to work with standard Markdown output of `<pre><code class="language-xyz">` (I'm actually not sure if this is "standard Markdown" or just the way the Markdown renderer Wyam uses renders it). Alternatively, use a different highlighter in the box that works with this output. That way it'll be easy to swap out an alternate highlighter.

Could also be a good place for some sort of extension point (I.e., "place these classes on code fences" or "apply this HTML transform to code fences").

**Comment by daveaglick** [comment]
Actually, after a quick glance, it looks like [highlight.js](https://highlightjs.org/usage/) works exactly this way. Might play with just swapping it out for Prettify.

**Comment by aarondandy** [comment]
I added a light theme based on VS15 that may be of use here if you do switch it over: https://github.com/isagalaev/highlight.js/pull/1316
