### ISSUE TITLE
RestoreFiles module and caching between executions

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#346]
Build a module that will hash the content of input documents and then store that hash along with a specified key from the document (document source, user-defined metadata key). If the hash matches the previous one, don't pass the document as output. If it doesn't continue processing the document. For example, given an image with a time consuming compression phase don't recompress it unless the image actually changes.

Need someplace to put the set of keys and hashes - perhaps make this a specified file path but from the build root path (not output path)

If the hash matches and we stop processing, how do we make sure the previously generated result(s) still make it to output? We clear the output folder at beginning of generation so it can't come from there. Also, the dropped document could have resulted in multiple output files - how to know? Might need to think about this a bit...

**Comment by LokiMidgard** [comment]
Do you mean something like this:

```
[Some Stuff],
Regeneration(
   ExpensiveOperation(),
   OtherExpensivOperation()
),
[More Stuff]
```

So if an input Document has already been processed by the Module it can skip this step and returning the cached documents?

How about storing the cached data in AppData or the Temp folder. (I would prefer the later)

**Comment by daveaglick** [comment]
Yeah, something like that. My initial thought was that it would act more like there `Where` module in that documents that have already been processed would just not "pass through" (because presumably the end result has already been written to disk). There's a few challenges with that - the main one off the bat being that we clear the output folder on every build. Figuring out how to keep the result of documents dropped by this module while still clearing stale output is going to be a tough problem.

On the other hand, your idea presents some interesting posibilities. Instead of relying on output files we could actually cache the documents part way through the process.

In either case this is a pretty tough problem. It'll speed up generation in many cases so it's worth doing somehow, but I don't want to rush the concept either.

**Comment by Silvenga** [comment]
Is anyone working on this? If not, I want to try to take a crack at it after the next nuget release (my blog doesn't work yet due to some breaking changes in the API).

**Comment by daveaglick** [comment]
Thinking through #694 has also triggered some additional thoughts on this issue. That issue is concerned with improving performance for regeneration, which is a little easier because we have access to in-memory caches of previous output documents. This issue is mostly concerned about reusing previously output content from prior invocations, which is much trickier and probably relies on a little more knowledge of the specific generation.

Here's what I'm thinking now:
* Instead of totally clearing the `output` folder at the start of a generation cycle, rename it to something else like `output-previous`
  * A flag should be provided along the lines of "don't reuse previous output" that results in just deleting it on a new invocation
  * Delete the `output-previous` folder at the end of the generation as a clean-up step
* Provide a new module named `RestoreFiles` (?) that works like `CopyFiles` except it copies from `output-previous` instead of input folders, and always copies to the same relative path
  * Like `CopyFiles` it should take a globbing pattern of files to restore
  * Regardless of whether files are actually restored, `RestoreFiles` appends to a file named something like `restorefiles.txt` that gets placed in the root directory and persisted between invocations (and generations)
    * The file contains source/hash pairs (see proposal for a new `IDocument.GetHashCode()` method in #694) for every document any `RestoreFiles` module in the previous generation saw - these will need to be matched to the specific `RestoreFiles` module instance (by parent pipeline + module name? position?)
    * The file is replaced at the end of each generation with values from the current generation
  * Child modules will be specified that should be run if files can't be restored, either because the `output-previous` folder doesn't exist, the `restorefiles.txt` file doesn't exist, or each input document doesn't have a matching hash code in the restorefiles.txt file
  * The output is always an empty document array - that ensures it'll output the same thing regardless of if files were restored or not and discourage using `RestoreFiles` in situations where an actual document output is needed later

For example, it'll look something like this:

```
Pipelines.Add("ShrinkImages",
  ReadFiles("**/*.jpg"),
  RestoreFiles("**/*.jpg",
    // These modules run if the restore couldn't happen
    Image.Resize(100),
    WriteFiles()
  )
);
```

**Comment by daveaglick** [comment]
Superseded by #831
