### ISSUE TITLE
Don't dispose referenced documents at the end of a pipeline

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#347]
This problem came up when working with the `Tree` module. It creates a parent/child relationship between documents, using metadata to store the parent and children for a given document. Other modules like code analysis do something similar.

This becomes an issue when using content of a non-root document outside of the pipeline where it was created. To try and keep memory down, the engine disposes documents created by a pipeline unless they're part of the final output. In the case of a tree, none of the child documents are directly final output documents but they shouldn't be disposed either because they're still part of the overall output.

This idea would make the concept of a document tree first-class. That way the disposal logic could be amended to say "don't dispose any output documents _or any of their children_". Here's a first cut:
- `IExecutionContext.GetDocument()` would provide overloads for specifying a parent document.
- The set of children would be automatically calculated based on which documents have that parent (possibly mirrored as a collection when the parent is set rather than computed each time).
- Need to decide if child ordering matters and how to specify sort order if it does (easier if not, can rely on consumers to sort however they want when they request children).
- Auto-disposal should ignore any document with a parent
- When a parent is disposed, all of it's children are disposed too
- `IDocument` should provide previous/next sibling and previous/next depth-first search iterators
- When cloning a document, what should happen with children? Should they be updated to the new parent? Should the whole tree get cloned? Should we ignore the tree during clone and rely on the cloning module to reconstruct it after if desired with clones of the children (probably this)?

**Comment by daveaglick** [comment]
On second thought I don't like this idea so much. It locks parent/child relationships into the concept of a single parent with one type of child. That's in contrast to other uses like code analysis where the parent has different types of children. Instead, allowing the modules to dictate the type of parent/child relationship by adding those structures as metadata still seems like the best approach.

That leaves us with the original problem though. I'm not thinking the best answer is to recursively scan not only the result documents but all of their metadata for other `IDocument` or collection of `IDocument`. Those documents that appear as metadata of a result document (and down the line) will also not be disposed. That should cover arbitrary metadata-based parent/child or any other document to document relationships.

**Comment by LokiMidgard** [comment]
One Problem I had with trees was that the children were outdate in later pipelines.

If `A` is parent to `B` and `C`, this relation is saved in the Metadata where document `B` and `C` are stored under a child key. Now we perform some transformations on `A`, `B` and `C` resulting in `A'`, `B'` and `C'` . But the documents in the metadata under `A'` are `B` and `C` without the additional data in `B'` and `C'` . 

I hope I remember correctly, I currently can't look it up.

**Comment by daveaglick** [comment]
@LokiMidgard Yeah, I can see why that's a problem. Because the parent, child, and other metadata is taken from the original tree structure it doesn't update when the documents are cloned. Each cloned node is still pointing to the old uncloned nodes.

Unfortunately, I'm not sure there's a way to "solve" this problem. It'll crop up for any document that has references to child documents. If you clone the parent and/or children the references will still point to the older ones unless you update them during the clone. The updating part is also really hard because there's a chicken and egg problem - if you have a two-way link (parent/child for example), when you clone the parent, how do you update the child reference during the clone without creating the clone of the child to point to? And if you do that, you have to point to the new parent from the child. It boils down to immutable trees are _hard_.

I don't think this is going to change. The immutable guarantee for documents gives us a lot of benefits and makes the overall pipeline processing model much cleaner. There are two things we can do to work around the problem:
- Make it clear for modules like `Tree` that build relationships between documents that if you clone documents in the relationship, those relationships won't get updated to the clones.
- Provide guidance that after cloning documents from a module like `Tree` you'll need to recreate the tree by running the module again if you need to preserve those relationships.

**Comment by daveaglick** [comment]
The original problem this issue was trying to address (too eager disposal of child documents) is now resolved.
