### ISSUE TITLE
System.InvalidOperationException (Collection was modified while iterating)

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#351]
I'd run in an Exception in the Insert Method of PathCollection. Line 169 ```if (_paths.Contains(path, new PathEqualityComparer()))``` throws sometimes an exception (at least while debugging).

It's getting called by ```IncludeContentDirectories``` in ```WyamFolderNuGetProject``` which is called by ```ProcessAssembliesAndContent``` in the same File.

Maybe it happens because of the ```Parallel.ForEach```, but I haven't looked much in in yet.

I used a temporary hacked fix that should never be used:
```c#
try
{
    if (_paths.Contains(path, new PathEqualityComparer()))
    {
        return false;
    }
    _paths.Insert(index, path);
    return true;
}
catch (Exception)
{
    return Insert(index, path);
}
```

**Comment by daveaglick** [comment]
Good report, thanks. I see where the problem is - you were right, it's because we're iterating in parallel and potentially manipulating a `List<T>` inside the `PathCollection` while doing so. Fix incoming in a couple minutes.
