### ISSUE TITLE
ArrayIndexOutOfBoundException

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#352]
Not sure what the problem is, But I get an Exception that the source array is not long enough.

BuildCommand:145 (```Trace.Information($"Input path(s):{Environment.NewLine}  {string.Join(Environment.NewLine + "  ", engineManager.Engine.FileSystem.InputPaths)}");```)

Unfortunately the Exception is not reliably reproducible. It occurs not that often.
The Exception seems to occur while iterating the InputPaths:

![image](https://cloud.githubusercontent.com/assets/389101/19909877/eb50e6ac-a089-11e6-990d-6f1e87356db8.png)

**Comment by daveaglick** [comment]
Hmm, that's an odd one. This looks like it's occurring within a `string.Join()`, which just  does an enumeration -  no array indexes should even be involved.  This part of the code is also single threaded so there shouldn't be any issues with parallelism.

 Any chance you could get me a full call stack?

**Comment by LokiMidgard** [comment]
I'll try the next time it occures.

**Comment by LokiMidgard** [comment]
```
System.IndexOutOfRangeException occurred
  HResult=-2146233080
  Message=Der Index war außerhalb des Arraybereichs.
  Source=mscorlib
  StackTrace:
       bei System.Collections.Generic.List`1.Enumerator.MoveNext()
       bei System.String.Join[T](String separator, IEnumerable`1 values)
       bei Wyam.Commands.BuildCommand.RunCommand(Preprocessor preprocessor) in C:\Users\patri\Source\Repos\Wyam\src\clients\Wyam\Commands\BuildCommand.cs:Zeile 145.
  InnerException: 
```

**Comment by LokiMidgard** [comment]
```
Wyam.exe!Wyam.Commands.BuildCommand.RunCommand(Wyam.Configuration.Preprocessing.Preprocessor preprocessor) Line 145
    Wyam.exe!Wyam.Commands.Command.Run(Wyam.Configuration.Preprocessing.Preprocessor preprocessor) Line 117
    Wyam.exe!Wyam.Program.Run(string[] args) Line 80
    Wyam.exe!Wyam.Program.Main(string[] args) Line 29

```

**Comment by LokiMidgard** [comment]
After the last time I pulled from your develop this hasn't occurred. (But it is not like it occurred that often =_=)

**Comment by daveaglick** [comment]
Good - I hate chasing down strange exceptions, would much rather build features :). Let's leave this and the other one open for a week or two just in case the issue comes back. If I don't hear anything more I'll close it out on my next issue review.

**Comment by daveaglick** [comment]
I'll go ahead and close this since it's been open for a while and there's a new released version. Please reopen if the issue comes back.
