### ISSUE TITLE
NullReferenceException in GetExistingDirectories()

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#353]
I got an Exception in ```VirtualInputDirectory.cs:132``` which is Called by:
```
VirtualInputDirectory.cs:64, 
VirtualInputDirectory.cs:31, 
Globber.cs:57
FileSystem.cs:240
```
The InputPaths of _fileSystem contains following ellements (including a null value)
![image](https://cloud.githubusercontent.com/assets/389101/19940086/c5c88ae6-a12b-11e6-9672-0e940752ba69.png)

```
System.NullReferenceException occurred
  HResult=-2147467261
  Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Source=Wyam.Core
  StackTrace:
       bei Wyam.Core.IO.VirtualInputDirectory.<GetExistingDirectories>b__17_0(DirectoryPath x) in C:\Users\patri\Source\Repos\Wyam\src\core\Wyam.Core\IO\VirtualInputDirectory.cs:Zeile 132.
  InnerException: 
```

**Comment by LokiMidgard** [comment]
After the last time I pulled from your develop this hasn't occurred. maybe it was related to #351

**Comment by daveaglick** [comment]
Leaving open for a few weeks - will close later if it doesn't come back.

**Comment by daveaglick** [comment]
I'll go ahead and close this since it's been open for a while and there's a new released version. Please reopen if the issue comes back.
