### ISSUE TITLE
More Flexible Include

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#380]
Hi I currently had the problem that I wanted to use the Include Module, to include a table on a document.

However the table gets generated using the xlst and csv module. So it is not a file in the include directorys.
 I also tried to write the files with the WriteFilesModule and then adding some ../ to get from the input to the output directory. But It seams to have Problems accessing the files before the pipline is finished. (Also I think this is some kind of a hacky approach ;) )

So I thought to extend the Include that in addition to use files can also use Child Modules.
My initial idea is to use the Source property of the documents that where created by the child moduls.

Meaning ```^"/test/bla.md"``` does not include the file that is on the disc under the specified path, but the document that where generated by the child modules that has the Source property of ```/test/bla.md```

The Syntax could be ```Include(Module[] modules)```

Any thought on this?

**Comment by daveaglick** [comment]
If I'm understanding the request correctly, the [Replace](https://wyam.io/modules/replace) module should take care of it:

```
Replace("%%TABLEHERE%%", ReadFiles("table.csv"), CsvToHtml())
```

Would that do the trick? One complication I can see is if there are actually multiple tables and you want to specify which one to insert within the replacement string. That's not currently supported, but may be a better fit for this use case than expanding `Include` to pipeline documents. For example, the `Replace.IsRegex()` setting could be expanded to pass capture groups to a delegate that can handle the replacement, taking whatever information is in the capture group and acting on it.

**Comment by LokiMidgard** [comment]
Yep,

Replace das almost what I want. As you mentiond I dont want to specify every Path manualy if I replace more elements.

```Replace.IsRegex(Func<System.Text.RegularExpressions.Match, String> evaluator)```

So to include some Documents in other Documents with the string ```§"Foo"``` while ID: Foo is part of the metadata of the to include document, I could use:

```
    Replace("§\"(?<name>[^\"]+)\"))
      .IsRegex( match => {
        var found = Context.Documents().FirstOrDefault(x=>x["ID"] == match.Groups["name"].Value);
        if(found==null)
          Trace.Warning("Faild to insert {match.Groups["name"].Value}")
        return found?.Content ?? "";
      })
```
If this should be the behavior, I could try to implement it in the next weeks (hopfully next days ;) ).

**Comment by LokiMidgard** [comment]
I head time to put some thougths in this and ended up with following.

```
 Replace("§\"(?<name>[^\"]+)\"), match => {
        var found = Context.Documents().FirstOrDefault(x=>x["ID"] == match.Groups["name"].Value);
        if(found==null)
          Trace.Warning("Faild to insert {match.Groups["name"].Value}")
        return found?.Content ?? "";
      })
```

Where the Constructor declaration is ```Replace(string search, Func<Match, object> contentFinder)```. If you are okay with the syntax, I can create a pull request ( LokiMidgard/Wyam@ddc4e8631a3387ea2da2ad68464dc6b99c6870c8)

**Comment by daveaglick** [comment]
That looks perfect, please move forward with a PR. Just be sure to edit the doc comments for the new method, especially to point out that the `Func` will get called once for every regex match.
