### ISSUE TITLE
Move the preview server out into a separate library.

### ISSUE THREAD

**Issue by pauldotknopf** [statiqdev/Statiq#385]
I am referencing the core libraries, and building things manually. I'd also like to be able to use your preview server and owin middleware. Currently, the server code is embedded in ```Wyam.exe```.

**Comment by daveaglick** [comment]
That's a great idea.

If it exists outside the console application, how would you start it? Should the preview server API support firing it up from some other consumer or should the new library also be a console application?

**Comment by pauldotknopf** [comment]
I'd say just a library.

Also, we might want to think about moving from Owin, and to Kestrel. This will set us up better for .NET Core, when the port happens.

Maybe I could create a new library completely, using the new Kestrel stuff? I'd love to help out if I could.

I am fucking loving this project.

edit: For some context of what I am doing, I am building a software interface for medical device documentation. It is a beast to tackle, and the people doing the documentation are tech-illiterate. I am embeddeding Wyam into a peice of software to allow the documentation writers to not have to learn command prompt, but still have all the build/preview abilities.

**Comment by daveaglick** [comment]
> I am fucking loving this project.

That's what I like to hear! Comments like this keep me going :smile:

The extra context was helpful. I agree - splitting out into a separate library with a nice public API is the way to go. Also agree it'll be a good opportunity to update to the latest Kestrel libraries.

Feel free to take a stab at it. I'll add it to my queue, but I'm planning on tackling performance (NuGet and otherwise) next so it may be a little while until I get to it. If you beat me to it, all the better.

**Comment by daveaglick** [comment]
Mostly unrelated to this issue, but perhaps helpful for what you're working on, have you seen Netlify CMS? It's something I've been meaning to dig into, looks like a client-side generator-agnostic frontend for editing static site files. Might be relevant (or might not be) but figured I'd mention it.

https://github.com/netlify/netlify-cms

**Comment by pauldotknopf** [comment]
That actually looks like exactly what I am building. I will look into it. Thanks!

**Comment by daveaglick** [comment]
FYI - going to start working on this one in the next couple of days.

**Comment by daveaglick** [comment]
Wyam.Hosting is now complete, it'll go up on NuGet with the next release. The nice thing is that it's not dependant on any other Wyam libraries at all. It can be consumed as a stand alone Kestrel-based server for static sites.

Note that right now it's limited to Windows and .NET 4.6.2. Most of the bits are in place to switch it to netstandard soon - just have to wait for a couple more external things to drop (like VS 2017 RTM).
