### ISSUE TITLE
Can CopyFiles.To give us the intended destination path, in addition to the source path?

### ISSUE THREAD

**Issue by deanebarker** [statiqdev/Statiq#389]
It would be awfully nice if the `To` method on the `CopyFiles` module gave us _both_ the source path and the _intended destination path_.

More often than evaluating the source path, I'd like Wyam to tell me _where it plans to copy the file to_, and then I'd like to modify that.

Possible?

**Comment by daveaglick** [comment]
Probably possible, though I may need a little more help understanding the request. Right now you're given a delegate with a `IFile` that represents the source file.

The default destination is derived by figuring out which input folder that source file belongs to and calculating the file's path relative to that input folder. Is this what would be handy - the relative path? Or were you thinking the full absolute destination path (which is the relative path combined with the output path)?

**Comment by deanebarker** [comment]
My input folder looks like this:

```
input
   assets
    styles
    images
```
I want to copy the contents of that `assets` folder to _the root of the output_. So, I want to "bump them up" a directory, and remove the `assets` directory.

Left to its own devices, Wyam will copy like this:
```
[output]/assets/styles
[output]/assets/images
```
It would be really easy if I could just get those paths that Wyam has gone to all the trouble of calculating and do this on them:
```
doc.Path.FullPath.Replace("/assets", string.Empty)
```
I _want_ Wyam to calculate the path because calculating relativity between directories is a pain and Wyam already does it.  I just want to mess with the path it comes up with.

**Comment by deanebarker** [comment]
Submitted pull request #398.

**Comment by deanebarker** [comment]
@daveaglick Just had a chance to try this out, finally. It works beautifully.

```
engine.Pipelines.Add("Resources",
  new CopyFiles(@"Assets/**")
    .To((source, dest) => { return dest.Path.FullPath.Replace("/Assets", string.Empty); })
```

That effectively "bumps up" the files by one directory, so I can store them somewhere different than the rest of my content.

I love it.

**Comment by daveaglick** [comment]
:tada:
