### ISSUE TITLE
Move settings to global metadata

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#391]
This is related to #358 - `ISettings` should be deprecated (and eventually removed) and instead it should just change global metadata so settings can be set from the global file.

Consider combining `Host`, `LinkRoot`, and `LinksUseHttps` into a single value that uses a URI to specify the "base". If we do that then the deprecated properties in `ISettings` will need to check the existing metadata value when they're set and build it up as each component is added.

**Comment by kamranayub** [comment]
FWIW, as a new user, I thought `Settings` was more intuitive but was confused when seeing both `GlobalMetadata[key] = value` and `Settings.Key = value` in the docs/examples.

**Comment by daveaglick** [comment]
@kamranayub I'm not at all happy with the difference between `Settings`, `GlobalMetadata`, and `InitialMetadata` right now. They all evolved separately for different reasons but now it's confusing what they each do. `GlobalMetadata` is probably the correct engineering approach, but the name isn't great when considering settings like hostname.

I think I'm going to end up consolidating them somehow, but haven't quite settled on a final approach. My current thinking (reflected in this issue) is to move `Settings`, `GlobalMetadata`, and `InitialMetadata` into a single set of metadata called simply `Metadata`. I *think* that makes sense given even the settings aren't universal - I.e., if using Wyam to generate an ebook then something like `Settings.Host` doesn't make any sense.

**Comment by daveaglick** [comment]
Going to try and get this into the next release. Tracking in #379 so going to close this issue.
