### ISSUE TITLE
Ability to "draft" posts using "published: false"

### ISSUE THREAD

**Issue by kamranayub** [statiqdev/Statiq#394]
I am in the process of migrating from Jekyll to Wyam and one feature I liked in Jekyll was providing the `published: false` in the front matter to allow draft posts. I looked through the RawPosts pipeline in the Blog recipe and it looks like I either need to use a different folder for drafts or leave out the Published property *and* not use date-prefixed filenames which I currently do.

I'm okay with both workarounds (preferring the latter solution) but it would be great to formally support "ignoring" posts for draft/other purposes for the Blog recipe. Furthermore, adding some documentation around specifically drafting posts would be great as the first thing I did was try to find the keywords "draft" somewhere in the Blog recipe docs.

**Comment by daveaglick** [comment]
An easy way to do this right now is add a `Published` value to the front matter but set it way into the future. The pipeline will only revert to using the file name for the published date if the front matter doesn't exist (that's what the `.OnlyIfNonExisting()` method does when setting the publish date metadata). 

In other words, you can create a draft by creating a post with a date-based filename and add a future `Published` in the front matter. Then when you're ready, just remove the `Published` front matter and it'll revert to pulling the date from the file name.

**Comment by daveaglick** [comment]
Wanted to make sure this technique worked okay for you. Given that there's a way to accomplish drafts right now, not sure it makes sense implementing an alternative. Perhaps this becomes a documentation issue.

**Comment by kamranayub** [comment]
It does work, I've set all my drafts to 1/1/9999 ;)

**Comment by daveaglick** [comment]
:thumbsup:
