### ISSUE TITLE
CleanBlog not using RssPath or AtomPath metadata

### ISSUE THREAD

**Issue by kamranayub** [statiqdev/Statiq#396]
I was trying to change the Atom XML path and noticed the theme has hardcoded the links to the RSS/Atom feeds:

https://github.com/Wyamio/Wyam/blob/develop/themes/Blog/CleanBlog/_Footer.cshtml#L7

Also in Layout:

https://github.com/Wyamio/Wyam/blob/develop/themes/Blog/CleanBlog/_Layout.cshtml#L16

**Comment by daveaglick** [comment]
Great catch, thanks! I recently added the ability to change the feed locations and must have missed this hard-coded link.

**Comment by kamranayub** [comment]
I'm trying to patch it locally right now, but I tried:

```
<a href="@Context.GetLink(Model.String(BlogKeys.RssPath))"><i class="fa fa-rss"></i> RSS Feed</a> | <a href="@Context.GetLink(Model.String(BlogKeys.AtomPath))"><i class="fa fa-rss"></i> Atom Feed</a>
```

Except this isn't working :( I think I'm doing something wrong? Other partials use `Model` to get at global metadata (I think).

**Comment by daveaglick** [comment]
That looks close. `Model` (and `Document`) get the currently rendering document. You probably want the property `Context` (which is itself an implementation of `IMetadata` for the global metadata).

Not sure if it'll work, but give this a shot:
```
<a href="@Context.GetLink(Context.String(BlogKeys.RssPath))"><i class="fa fa-rss"></i> RSS Feed</a> | <a href="@Context.GetLink(Context.String(BlogKeys.AtomPath))"><i class="fa fa-rss"></i> Atom Feed</a>
```

**Comment by kamranayub** [comment]
That worked! I'll submit a patch PR 👍

**Comment by daveaglick** [comment]
Awesome, thanks!
