### ISSUE TITLE
PostsPath not used for Archive link on Index

### ISSUE THREAD

**Issue by kamranayub** [statiqdev/Statiq#399]
Similar to #396 

The `PostsPath` property is not used on `_Index.cshtml` for the Archive link:

https://github.com/Wyamio/Wyam/blob/develop/themes/Blog/CleanBlog/index.cshtml#L57

Not sure how Archive link is generated in navbar--that may be working.

**edit:** Actually, maybe this isn't an issue--I think it expects the archive path to always be at `/posts` no matter where the posts are sourced from.

**Comment by daveaglick** [comment]
> Actually, maybe this isn't an issue--I think it expects the archive path to always be at /posts no matter where the posts are sourced from

Pretty sure that's right (which is probably a bug in it's own right). I'll keep this open and do some deeper research when I get the chance. Should probably go ahead and audit the themes for other similar issues that may have gotten introduced when adding the path preferences as well.
