### ISSUE TITLE
Always "Installing NuGet packages"

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#401]
When I run 

`wyam.exe --recipe Blog --theme CleanBlog`

Wyam tries to install (or download ?) Nuget packages:

```
Installing NuGet packages
    Installing packages to C:/Users/xyz/.nuget/packages (using global packages folder)
    NuGet packages installed in 15117 ms

```

Why it had to install Nuget packages every single time, and why it takes ~15 seconds?

**Comment by MAJVeld** [comment]
This is well known to happen in Wyam and has already been reported in issue #317. 

I faced it myself when building a static website using Wyam. This is especially noticeable when a lot of dependencies have to be scanned, as is the case when using support for parsing Razor syntax.

**Comment by daveaglick** [comment]
@AllanXu49 @MAJVeld is right, this is a known annoyance at the moment. It has to do with the deep dependency tree of some of that packages Wyam uses (like Razor) and the way the NuGet APIs traverse such trees. This (and other performance bottlenecks) is actually what I'm working on right now and hope to have some improvements soon.

**Comment by daveaglick** [comment]
I'll go ahead and resolve this issue since we've hopefully answered your question. Feel free to reply and I can reopen it if needed.
