### ISSUE TITLE
http://localhost:5000 ==> localhost refused to connect.

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#403]
When I browse to "http://localhost:5000" after running run below command, Chrome shows **localhost refused to connect.**

My **guess** is that this is due to windows firewall. However, I do not get windows firewall popup asking me to allow wyam.exe listen on 5000. I probably have to open the firewall port to wherever I xcopy Wyam.exe 

I do not encounter similar issue with Hexo or Jeckll. Is there any way Wyam pops the windows firewall permission dialog? 

```
..\Wyam\Wyam  --preview --noclean
Wyam version 0.15.8-beta

   ,@@@@@       /@\        @@@@@
   @@@@@@      @@@@@|     $@@@@@h
  $@@@@@     ,@@@@@@@    g@@@@@P
 ]@@@@@M    g@@@@@@@    g@@@@@P
 $@@@@@    @@@@@@@@@   g@@@@@P
j@@@@@   g@@@@@@@@@p ,@@@@@@@
$@@@@@g@@@@@@@@B@@@@@@@@@@@P
`$@@@@@@@@@@@`  ]@@@@@@@@@`
  $@@@@@@@P`     ?$@@@@@P
    `^``           *P*`
**BUILD**
Could not find configuration file at file:///C:/DELTMP/wlab/config.wyam
Installing NuGet packages
    Installing packages to C:/Users/xyz/.nuget/packages (using global packages folder)
    NuGet packages installed in 29 ms
Recursively loading assemblies
    Assemblies loaded in 5 ms
Cataloging classes
    Classes cataloged in 16 ms
Root path:
  file:///C:/DELTMP/wlab
Input path(s):
  theme
  input
Output path:
  output
Executing 0 pipelines
    Executed 0/0 pipelines in 1 ms
Preview server listening on port 5080 and serving from path file:///C:/DELTMP/wlab/output
Hit any key to exit
WShutting down

```

**Comment by daveaglick** [comment]
If you look at the CLI output you'll notice that it says `Preview server listening on port 5080` as opposed to port 5000, which is what it looks like you tried to connect to. Port 5080 is the default preview port. Does it work if you connect to http://localhost:5080? Note that you can adjust the preview port with the `--preview [port]` argument on the command line.

**Comment by AllanXu49** [comment]
5080 is the port and it worked. Sorry for the false alert.

**Comment by daveaglick** [comment]
:thumbsup: No problem, happy to help
