### ISSUE TITLE
URL to posts without .html

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#405]
The site I am generating with Wyam includes many html pages; however all navigation urls href to the page name without html.

It seems that Wyam preview server automatically adds .html to the page names. But I am not sure other hosts like IIS or Github pages would do the same? How can I host Wyam sites on other hosts that do not automatically add .html to the end of pages?

The way that Hexo handles this matter is to create a folder with the page name and add an index.html inside the folder.  I am not sure how exactly Wyam  is handling urls without adding .html to the page hrefs.

Thank you,

**Comment by daveaglick** [comment]
Most static site hosts like GitHub pages automatically hide `.html` and `.htm` extensions. This allows you to use a file like `/foo/bar.html` for the URL `http://my.host/foo/bar`. By default Wyam assumes your host can support this functionality (most can either natively or with some configuration) and the preview server does the same.

Wyam does not use the fallback approach of creating an `index.html` under each "file path" in the blog recipe. You could of course create a custom Wyam configuration that would do this. Instead, to support hosts that do not have extensionless file handling, you can turn off hiding the `.html` and `.htm` extensions in generated links. You do that in the `config.wyam` file:

```
// Make links have the extension of the file
Settings.LinkHideExtensions = true;
```

**Comment by AllanXu49** [comment]
Thanks for the help. Do you know if IIS can automatically hide .html and .htm extensions as well? I am asking since I might have to deploy some of my sites to Godaddy IIS hosting.

**Comment by daveaglick** [comment]
Yep! These instructions are for Azure, but the `web.config` file should work for any IIS host: https://wyam.io/docs/deployment/azure

**Comment by daveaglick** [comment]
Resolving this for now. Please feel free to respond and I'd be happy to reopen it (or create a new issue).

**Comment by jeremyiverson** [comment]
> Wyam does not use the fallback approach of creating an index.html under each "file path" in the blog recipe. You could of course create a custom Wyam configuration that would do this.

For anybody interested in doing this, the following configuration will create directories with an index.html file for every page, so your web server does not need to be configured to serve files without extensions. This sample modifies the Blog recipe, but a similar constructor call on WriteFiles() should work for other recipes or pipelines, too.

```
// Replace the file rendering configuration with a function that
// works out to extensionless URLs.
Pipelines["RenderPages"].ReplaceFirst<WriteFiles>(
    new WriteFiles(ConfigureOutputPath).UseWriteMetadata(false),
    "WriteFiles dirthml");
Pipelines["RenderBlogPosts"].ReplaceFirst<WriteFiles>(
    new WriteFiles(ConfigureOutputPath).UseWriteMetadata(false),
    "WriteFiles dirthml");


// Transform a path like /a/x.html into /a/x/index.html
public object ConfigureOutputPath(IDocument doc, IExecutionContext context)
{
    FilePath originalPath = doc.FilePath(Keys.RelativeFilePath);
    string directoryOnly = originalPath.Directory.ToString();
    string fileNameWithoutExtension = originalPath.FileNameWithoutExtension.ToString();

    if (fileNameWithoutExtension == "index")
    {
        return originalPath;
    }

    string dirhtmlPath = System.IO.Path.Combine(directoryOnly, fileNameWithoutExtension, "index.html");
    return dirhtmlPath;
}
```

**Comment by daveaglick** [comment]
@jeremyiverson Thanks for posting that tip! I love seeing folks use the pipeline modification extensions to customize the recipes.
