### ISSUE TITLE
Better title in the UI for docs recipe

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#410]
Support alternate title image formats like SVG. The fallback should also be text-based and use the site title instead of the big stupid "Docs" image.

**Comment by JimBobSquarePants** [comment]
How do you set this? I couldn't find docs.

```
Settings[Keys.Logo] = "/assets/img/imagesharp-logo.svg";
```

Just left me with the message. 

>    1 errors compiling configuration:
Line 4: CS0117: 'Keys' does not contain a definition for 'Logo'

**Comment by daveaglick** [comment]
This part is a little confusing - I've got it on my near-term todo list to clarify the documentation about metadata keys.

The `Settings` class is just a dictionary with string keys and `Keys` is just a static class with const strings for the "known" items you can add to the dictionary. Because `Keys` is in the core library and the docs recipe is an extension, any keys that are specific to the recipe have to go in a separate class (that is until we get extension properties in C#...someday). You're looking for `DocsKeys.Logo` (https://wyam.io/api/wyam.docs/docskeys/), or you can alternatively just use the string "Logo" as the key.

**Comment by JimBobSquarePants** [comment]
Excellent. Thanks!
