### ISSUE TITLE
Trying to define the number of posts in the front page in the Config file

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#416]
With my theme, I like to show more than 3 posts in the first blog page. 
I can change the number 3 in `Take(3)` below to higher number like 7.

index.chtml

```
<div class="row">
    <div class="col-sm-8 right-border">
        @{
            bool first = true;
            foreach(IDocument doc in Documents[BlogKeys.Posts].Take(3))
            {   

```
or

```
        <h5>Older Posts</h5>
        <ul class="list-unstyled">
            @foreach(IDocument doc in Documents[BlogKeys.Posts].Skip(3).Take(4))

```

However, I prefer to read the number of posts from the config file.

What would be the syntaxt to define an integer in the configuration file and how do I access it in the Razor page - something with @Conetxt I guess?

**Comment by daveaglick** [comment]
That's actually exactly what `GlobalMetadata` is for (renamed to `Settings` in the next version coming out today or tomorrow).

In your config file you just add a value to the `GlobalMetadata` dictionary like this:
```
GlobalMetadata["PostCount"] = 5;
```

In the next version it will look like this:
```
Settings["PostCount"] = 5;
```

Then you can access it from within your Razor page using `@Context`. The `Context` property contains the current `IExecutionContext` which contains all your global metadata:

```
<div class="row">
    <div class="col-sm-8 right-border">
        @{
            bool first = true;
            foreach(IDocument doc in Documents[BlogKeys.Posts].Take(Context.Get<int>("PostCount")))
            {  
```

**Comment by AllanXu49** [comment]
Simple and Beautiful!

Can’t wait to get the next version. 

I am hoping to get a list of breaking changes since I have fair amount of customizations in the theme I created,

**Comment by daveaglick** [comment]
We're getting close to a 1.0 release and as that approaches I'm hoping to keep breaking changes to a minimum, if at all. In this case the old properties will continue to work but will display warnings during the build.
