### ISSUE TITLE
Pipeline exceptions to include file name

### ISSUE THREAD

**Issue by pauldotknopf** [statiqdev/Statiq#417]
Many of the modules in the pipelines don't include information about what file is being processed.

It makes it difficult to find a formatting issue in a large directory.

There should probably be something like this.

```c#
var currentFileProcessing = "" // get this from somewhere.
try
{
   // process module
} catch(Exception ex)
{
   throw new ModuleException(currentFileProcessing, ex);
}
```

I understand it may be difficult, with the concat/transform modules and such, but maybe there is still a way?

I am developing this project into a solution for people who aren't very techy.

I am building a light-weight WPF directory browser and file editor, and I'd like to highlight the files that are causing the build error.

**Comment by daveaglick** [comment]
Totally agree this would be helpful. I've been stung several times myself by not knowing the exact document.

There's actually already an issue over at #320, including a discussion of why this is a little challenging (certainly not insurmountable, but not super-easy either). I'll close this issue, but feel free to pick up the discussion over there.
