### ISSUE TITLE
Do we have Draft" posts in Wyam?

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#425]
I am looking for Draft" posts in capability in Wyam.

When a post is Draft, it does not appear in the archive or 1st front page, but the actual html file is generated and can be accessed by knowing its URL.

I tried the ShowInNavbar: false front matter key, but still, the blog post appears on the 1st page or archive.

**Comment by daveaglick** [comment]
There's no explict concept of a draft but it's easy to achieve this capability by setting the `Published` date far into the future. See this comment for a bit more information: https://github.com/Wyamio/Wyam/issues/394#issuecomment-273904362
