### ISSUE TITLE
Where is the reference to _Scripts.cshtml ? 

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#431]
I am not able to find the reference to _Scripts.cshtml in Wyam. 

Where and how Wyam includes the javascripts in _Scripts.cshtml ?

**Comment by AllanXu49** [comment]
Ok, I found the answer. 

It is the statement `@Html.Partial("_Scripts")` in the _Layout.cshtml.

Is there any way I can delete an issue I created in Github? StackOverflow allows that.

**Comment by daveaglick** [comment]
No way to delete, but you can close it on your own. Every new issue is a chance for the next person with the same question to discover the answer.
