### ISSUE TITLE
Docs recipe should look for source files both under and next to input folder

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#436]
It should look in both places to reduce confusion - use an array for the default `SourceFiles` setting. Be sure to update docs.

**Comment by deap82** [comment]
@daveaglick 

Is this part of 2.2.4?

I've tried both upgrading and setting DocsKeys SourceFiles myself, but the "C# API" section is not generated...

`Settings[DocsKeys.SourceFiles] =  = "../src/**/{!bin,!obj,!packages,!*.Tests,}/**/*.cs";`

I found this config file in another repo, that does a similar thing, so I suppose it's working for them: https://github.com/reactiveui/website/blob/master/config.wyam
Perhaps @RLittlesII has some input? 😇

**Comment by RLittlesII** [comment]
@deap82 if it just a question on the functionality, I recommend joining the Gitter channel.

If you have an issue with the functionality I recommend opening a new issue and linking this one.
