### ISSUE TITLE
Update to latest Cake

### ISSUE THREAD

**Issue by gep13** [statiqdev/Statiq#437]
With the upcoming release of 0.18.0, there is a requirement that all addin's have a minimum version of Cake, i.e. 0.16.2 and above.

@daveaglick would you be in a position to update this addin to the latest Cake version, so that it will be supported OOTB?

Thanks!

**Comment by daveaglick** [comment]
Yep. Actually pushing out a new release *this very second!* so I'll get the Cake addin update in the next one.

**Comment by gep13** [comment]
>@daveaglick said...
so I'll get the Cake addin update in the next one.

That would be great, thank you!  I am now running Wyam as the default documentation generation tool in Cake.Recipe, and it is now rolled out to almost 15 addins, so would be great to get support for it OOTB when 0.18.0 of Cake is released.

**Comment by daveaglick** [comment]
Any suggestions on what version to move to? Should I just target minimum compatible 0.16.2 to support older versions?

**Comment by gep13** [comment]
@daveaglick I have been moving to 0.17.0 for everything except Cake.Testing where I have been using 0.17.1.

**Comment by pascalberger** [comment]
I created a PR:  #457
