### ISSUE TITLE
File globbing not working (I think) as expected, ignoring folders

### ISSUE THREAD

**Issue by pauldotknopf** [statiqdev/Statiq#441]
When I pass in ```{!ignore,**}/*.md```, I expect it to grab every markdown file, except when it is contained within the root folder ```ignore```.

This works, however, files that are in sub directories in ```ignore``` get included.

For example, ```ignore/sub/file.md``` would be returned.

Is this expected? Am I doing it wrong?

**Comment by pauldotknopf** [comment]
Also, I've tried ```{!requirements/**/*.md,**/*.md}```, but that ignored everything, including the files I want included.

**Comment by pauldotknopf** [comment]
Hmm, digging into the code, I see it is using Microsoft's new file system globbing. Let me check it.

**Comment by daveaglick** [comment]
Any word on the resolution to this? Was there a bug in the MS globbing library?

**Comment by pauldotknopf** [comment]
I'm an idiot. I had a typo in my expression. No issue.

Sorry.
