### ISSUE TITLE
Add enforcement for style rules

### ISSUE THREAD

**Issue by shaneray** [statiqdev/Statiq#443]
I was reviewing the `CONTRIBUTING.md` and came across the `Style Guidelines` section,  I was considering adding the `.editiorconfig` file from https://github.com/dotnet/roslyn/blob/master/.editorconfig to help stay consistent with accepted .NET coding styles.  Since this is something that is solution wide I wanted to open an issue/discussion to determine if this is something that would be beneficial.  Also up for discussion is any deviations from the roslyn `.editorconfig` that would be required/preferred for Wyam.

**Comment by Silvenga** [comment]
In addition to `.editiorconfig` I propose an addition of a `.DotSettings` configuration as Resharper is used by a large portion of the C# developers market (and many cannot live without it).

**Comment by shaneray** [comment]
I agree.  Another thing suggested by @enkafan is a simple set of style cop analyzers.  This would be useful for developers that are not using the latest visual studio with the `.editorconfig` support or ReSharper.  The more style helpers we can add to the projects the less chance style issues will make it into pull requests.  Also allows the style guidelines to be enforced by CI.

**Comment by daveaglick** [comment]
Totally on board with this. The more tooling we can add to make hacking on the code easier and consistent, the better.

**Comment by phil-scott-78** [comment]
Something else having the coding style standardized could lend itself to is integration with codebetter.io. I think they require a stylecop config though. Once that's in place it is quite nice to let it be the bad guy if someone submits a PR that doesn't color within the lines.

Tangent idea that might be worth a new issue  - could be clever if a module existed that could take an editorconfig and build out some text to include in the doc recipe.

**Comment by phil-scott-78** [comment]
Err, codefactor not codebetter

**Comment by daveaglick** [comment]
Reopening to track @enkafan idea of using CodeFactor or even just enforcing style rules by emitting build warnings (and treating as errors in CI).

**Comment by shaneray** [comment]
@daveaglick I am currently working on some of these items.  I have added the .editorconfig and StyleCop.MSBuild nuget package to all projects.  Working on a few more tweaks before I submit my PR.

I also added my Wyam fork to CodeFactor.io and it is currently reciving a B grade.  I have added the badge below.  If you setup the original Wyam repository in CodeFactor I can add the badge to the readme in my PR.
[![CodeFactor](https://www.codefactor.io/repository/github/shaneray/wyam/badge/develop)](https://www.codefactor.io/repository/github/shaneray/wyam/overview/develop)

**Comment by shaneray** [comment]
After enabling StyleCop there are 18,136 Warnings, so it will definetly be a bit before we want to enable "Warnings as errors".
![image](https://cloud.githubusercontent.com/assets/482797/22941174/79ca0bdc-f2b2-11e6-8641-81b4d7c73f2c.png)

**Comment by daveaglick** [comment]
@shaneray That's...a lot of warnings :smile: 

I'm wondering if we should use [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) instead of StyleCop.MsBuild - [this thread](https://github.com/StyleCop/StyleCop/issues/12) seems to suggest that's the best way forward. Since it's based on the Roslyn analyzers framework, it'll probably be better supported going forward too. Thoughts?

**Comment by shaneray** [comment]
Already switched out the packages.  :). That dropped the warning count about 3,000.

**Comment by Silvenga** [comment]
@daveaglick any reason for the `DocumentationFile` additions on the test projects?

>   Warning CS1591: Missing XML comment for publicly visible type or member

It's making Resharper very annoyed with me 😿. Do we need XML docs on all the Unit Tests?

**Comment by daveaglick** [comment]
@Silvenga No, the unit tests should be exempted from XML docs IMO. I'm not too concerned about code quality on the tests in any case, so I'll probably just go in and turn off the rules for all the test libraries.

**Comment by daveaglick** [comment]
I ended up splitting into three rulesets:
- "Wyam Code Rules" which contains all the code quality rules.
- "Wyam Documentation Rules" which contains all the rules about XML doc comments.
- "All Wyam Rules" which is just a meta-ruleset with the other two.

"Wyam Code Rules" are applied to the test projects and "All Wyam Rules" are applied to releasable projects.

**Comment by daveaglick** [comment]
...and I take it back :smile: - ended up using two rulesets: "Wyam Rules" and "Wyam Test Rules", that should make it even clearer.

The warnings are still in the 3k range, but I'll cut down on those gradually.

**Comment by daveaglick** [comment]
I'm pretty happy with where this is now. I may still tweak the rules here and there, but they're looking really good. Thanks for the help everyone! It's the kind of thing I never would have gotten around to on my own, but I'm really glad we're enforcing some of these now.

There's still a large number of warnings, but we can cut down on those over time. And as new PRs are considered, I can take a look at rule violations to make evaluation easier.

**Comment by daveaglick** [comment]
Added #474 to track CodeFactor support
