### ISSUE TITLE
KeyNotFoundException when clearing a pipeline from Docs recipe

### ISSUE THREAD

**Issue by k94ll13nn3** [statiqdev/Statiq#455]
In the recipe concept page on the site, it is stated that a pipeline from a recipe can be disabled by clearing it. I tried this with the Code pipeline from the Docs recipe, as I only read API from a DLL, and when generating the site, a `KeyNotFoundException` happened.

Here is what I tried: `Pipelines["Code"].Clear();`

But if I add some new logic to the pipeline that generates no documents, it works:
```
Pipelines["Code"].Clear();
Pipelines["Code"].Add(
    new If(ctx => false, new ReadFiles())
);
```

I tried this with the other pipelines from the recipe, always the same error.

The only other thing in my `.wyam` file is the `DocsKeys.AssemblyFiles` setting.

Here is the exception message: 
```
Exception during execution: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Wyam.Core.Execution.Engine.Execute() in E:\Code\Wyam\src\core\Wyam.Core\Execution\Engine.cs:line 198
```

Wyam version: 0.16.3

**Comment by daveaglick** [comment]
Thanks for the bug report. This should be easy enough to repro so hopefully I'll be able to get in a fix in the next version.

**Comment by daveaglick** [comment]
Thanks again for the bug report - this is resolved in the the develop branch and will make it out in the next release.
