### ISSUE TITLE
Blog recipe should not put out post index page or tags page when posts folder is missing

### ISSUE THREAD

**Issue by adamclifford** [statiqdev/Statiq#456]
It would be good if the Blog recipe didn't output a posts index page, and a tags index page when the posts folder in input has been deleted.

It should also remove the links in the menu when that is the case.

This will mean it is a lot easier to have a customised site without having to create a new set of pipelines in the config.

**Comment by daveaglick** [comment]
Great idea. Already do something similar in the docs recipe, so it shouldn't be too hard to port that to blog.

**Comment by daveaglick** [comment]
Can confirm posts folder and index page is no longer output when no posts exist (at least in develop branch). Fixing up tags now.

**Comment by adamclifford** [comment]
Can confirm that this is currently fixed on the 0.18.2 version
