### ISSUE TITLE
foreach loop isn't reading last item metadata

### ISSUE THREAD

**Issue by elvogel** [statiqdev/Statiq#458]
I have a project with the following [partial] structure:
/blog/index.cshtml
/blog/[blogposts].md
/blog/_layout.cshtml
/blog/_ViewStart.cshtml
/blog/index.cshtml

in my `index.cshtml` file I have the following code: 
```
@{
    Layout = "../Shared/_default.cshtml";
}

<div class="newsPostWidgets">
    <div class="row">
        @foreach (var b in Documents["Blog"].OrderByDescending(x=> x.Get<DateTime>("Published")))
        {
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 newsPostWidgetColumn">
                    <div class="newsPostItem">
                        <a href="/@b.String("RelativeFilePath")">
                            <div class="headerWidget newsPostHeader">
                                <h3>@b.String("Title")</h3>
                                <p>@(b.Get<DateTime>("Published").ToLongDateString())</p>
                            </div>
                            @*<figure><img src="@String.Concat(Model["cdn"],b.String("Image"))" alt="" /></figure>*@
                        </a>
                            <h6>@b.String("Excerpt")</h6>
                    </div>
                </div>
        }
    </div>
</div>
```
For the most part this code runs very well. I have seven blog posts, and they are all showing up in the output as HTML files. But on my `index.cshtml` page I am seeing:
![image](https://cloud.githubusercontent.com/assets/2071112/23338577/b27677c6-fbdc-11e6-90aa-1bd82f00e543.png)

where 'Endpoint Systems - Integrating Everything' is the default Title from `config.wyam` instead of from the Markdown file where the correct name (and date) are both specified. In fact, the link for that page is rendered correctly - just not the title or publish date.

My config.wyam looks like this:
```
Settings["title"] = "Endpoint Systems - Integrating Everything";

Pipelines.Add(
    "News",
    ReadFiles("news/**.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Razor(),
    WriteFiles(".html")
);

Pipelines.Add(
    "Blog",
    ReadFiles("blog/**.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Razor(),
    WriteFiles(".html")
);

//now that our news & blog posts have been proc'd, let's index the entries & build out the rest of the site
Pipelines.Add(
    "Content",
    ReadFiles("**/{!_,}*.cshtml"),
    FrontMatter(Yaml()),
    Razor(),
    WriteFiles(".html")
);

//copy all of our style resources over
Pipelines.Add(
    "Resources",
	CopyFiles("**/*{!.cshtml,!.md,!.yaml,}")
);
```

**Comment by elvogel** [comment]
In my MD file I had an 'equals' separator, instead of dashes.
```
Title: Some Title
Published: 1/1/2016
Excerpt: In the beginning...
===
^ this is wrong - make it --- instead
```

**Comment by daveaglick** [comment]
Ah, glad you figured it out! The [FrontMatter module](https://wyam.io/modules/frontmatter) actually does allow you to specify a custom delimiter if you want, but that's hard-coded to dashes in the blog recipe right now.
