### ISSUE TITLE
Question; is it possible to paginate the result of a GroupByMany?

### ISSUE THREAD

**Issue by alfadormx** [statiqdev/Statiq#459]
Hello,

Following the Blog example/recipe, I would like to know how to paginate the post list for each tag generated by the GroupByMany module. Is this possible?

Thanks for your help
Hector

**Comment by daveaglick** [comment]
Definitely - in fact the docs recipe does exactly this for it's blog categories: https://github.com/Wyamio/Wyam/blob/develop/src/extensions/Wyam.Docs/Docs.cs#L198

You should be able to do something similar in the blog recipe (you'll also need to replicate the docs `_BlogIndex.cshtml`).

Paginating the tags is probably a good candidate for something to implement in the blog recipe directly too - I'll add it in when I get the chance.

**Comment by alfadormx** [comment]
cool! thanks! I will try it out on the blog recipe. If it is ok I could send you a pull request later! :)

**Comment by alfadormx** [comment]
you sir are a master! it worked for my case !!! thank you very much.
