### ISSUE TITLE
Publish Wyam as a dnx package

### ISSUE THREAD

**Issue by jonstelly** [statiqdev/Statiq#46]
I'm still getting my head wrapped around using Wyam and what I'd like my workflow to be, but for now, I think I'd like to use Visual Studio to manage/edit my input project, using an empty asp.net 5 site.

With asp.net 5's project.json format having the ability to register commands, which can then be run from dnx or inside Visual Studio Code: [Link](https://code.visualstudio.com/Docs/ASPnet5).  I think it would be helpful if Wyam could be packaged up and published as a DNX package.

That should let us register a command for wyam and integrate with the IDE or command-line a bit better.

All/most of the moving parts to do this might already exist, so this issue is either an enhancement request, or might just be a place to gather some of this documentation.

**Comment by daveaglick** [comment]
Great idea. I had been toying with ideas about how to do this exact thing (run Wyam as the "compiler" from VS), but that was a while ago before VS 2015 and ASP.NET v5 got mature. I like your idea better - it makes much more sense to hook into the new v5 pipeline than try and support the previous ASP.NET versions and msbuild process.

That said, I haven't been following the v5 stuff that closely (beyond the new Razor bits, which I stole for this project). I've also heard the packaging can get more than a little confusing right now (for example, AutoMapper 4.0 was released yesterday and there were all kinds of issues with the initial packages). There's also the question of dnx support from the libraries Wyam uses. While I'm confident the Wyam core parts could be made to run under dnx without too much trouble, I'm not so sure about the Markdown parser, Less parser, etc.

All this is to say I love the idea and it's definitely something to work towards. I just think it'll take time to figure it all out.

**Comment by daveaglick** [comment]
I'm going to close this issue as superseded by #300 (especially since there isn't even a "dnx" anymore)
