### ISSUE TITLE
De-dupe doc comments for partial classes

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#460]
If a partial class has the same doc comment in more than one place, it shows up multiple times in the summary. Should only show distinct doc comments (but still aggregate from multiple partials).

**Comment by M-Zuber** [comment]
I'd like to try and do, as I have been wanting something bite-sized to contribute.
Say, give me until you get back from vacation?

**Comment by daveaglick** [comment]
:thumbsup: Have at! It'll be in this class: https://github.com/Wyamio/Wyam/blob/develop/src/extensions/Wyam.CodeAnalysis/Analysis/XmlDocumentationParser.cs
