### ISSUE TITLE
Markdown is not generating tables

### ISSUE THREAD

**Issue by alfadormx** [statiqdev/Statiq#462]
Hi,

Could you please help me out? I am using the following configuration for my posts:

```c#
Pipelines.Add("RawPosts",
	ReadFiles(@"posts\*.md"),
	FrontMatter(Yaml()),
	Where((doc, ctx) => {
		if (!doc.ContainsKey("Published") || doc.Get("Published") == null || doc.Get<DateTime>("Published") > DateTime.Now)
		{
			return false;
		}
		return true;
	}),
	Markdown(),
	Replace("<img", "<img class=\"img-responsive center-block\""),
	Meta("RelativeFilePath", (doc, ctx) => {
		string category = SeoFriendlyName(doc.String("Category"));
		string fileName = SeoFriendlyName(doc.String("Title"));
		return $"category/{category}/{fileName}.html";
	}),
	OrderBy((doc, ctx) => doc.Get<DateTime>("Published")).Descending()
);
```

Which I later render through:

```c#
Pipelines.Add("RenderPosts",
	Documents("RawPosts"),
	Razor().WithLayout("/_PostLayout.cshtml"),
	MinifyHtml(),
	Excerpt("div#content")
		.WithMetadataKey("Content")
		.WithOuterHtml(false),
	WriteFiles(".html"),
	OrderBy((doc, ctx) => doc.Get<DateTime>("Published")).Descending()
);
```

My posts are like this:

```
---
Title: Scrum and Kanban
Published: 2016-04-06
---
A board helps teams to organize, priorityze and get things done. Bla bla bla more text goes here and then a wild table appears:

**A simple board**
New    | Active | In Test | Done  
-------|--------|---------|-------
empty  | empty  | empty   | empty 
```

The rendered result is:

```
<p><strong>A simple board</strong> New | Active | In Test | Done<br> -------|--------|---------|------- empty | empty | empty | empty</p>
```

The amazing story is that the same version of Wyam is properly generating tables using the Blog recipe.
It is my understanding that the default Markup configuration is "advanced" and that the Blog recipe is set to "advanced" by default (unless I override it).

I don't know what I'm doing wrong. Could you please help me out?

Thank you very much!

**Comment by daveaglick** [comment]
I'm traveling this weekend, so I probably won't have a chance to take a look at this until Monday. I'll definitely check it out when I can though.

**Comment by alfadormx** [comment]
Thanks!
You can see the live example of this issue here: http://www.alfador.mx/agile-development/scrum-and-kanban

**Comment by daveaglick** [comment]
Sorry - been crashing on a couple other things, hoping to take a look at this and your other issue tomorrow.

**Comment by daveaglick** [comment]
Okay, finally getting back to this. Pretty sure you just need to enable advanced Markdown extensions when you call the Markdown module (tables aren't actually "standard" Markdown, to the extent there is such a thing). The Blog recipe does this automtically, but it's a recent addition so if you've copied the recipe code from an older version you're still using the stock Markdown configuration. Just try replacing the Markdown module in your "RawPosts" pipeline with:

```
// ...
Markdown().UseConfiguration("advanced"),
// ...
```

Or if you're using Bootstrap for CSS:

```
// ...
Markdown().UseConfiguration("advanced+bootstrap"),
// ...
```

Let me know if that works for you.

**Comment by alfadormx** [comment]
Hello Dave,

I had tried that with no success.

Here you have my console output: [console.txt](https://github.com/Wyamio/Wyam/files/835823/console.txt)

And my Wyam Config file as txt: [config.txt](https://github.com/Wyamio/Wyam/files/835824/config.txt)

Finally the rendered post html as txt: [scrum-and-kanban.txt](https://github.com/Wyamio/Wyam/files/835825/scrum-and-kanban.txt)

Finally, my post input file in txt: 
[input.txt](https://github.com/Wyamio/Wyam/files/835826/input.txt)

The output is visible online at https://www.alfador.mx/agile-development/scrum-and-kanban

Thanks for time,
Hector HERNANDEZ

**Comment by daveaglick** [comment]
Thanks a lot for all the reproducible files, that makes it *so* much easier to troubleshoot. I'll take a look and get back to you (might be a few days - I try to take it easy on the weekends :smile:)

**Comment by daveaglick** [comment]
I was able to reproduce and resolve this issue. It looks like a quirk of the way Markdown processors identify tables as being separate from other content. In short, they have to have whitespace above and below the table. In this case, all of the tables on your Markdown file have headings on the line immediately preceding them. When I add an extra newline after the headers (and use the "advanced" rendering configuration mentioned about) the tables come out fine.

**Comment by alfadormx** [comment]
I cannot believe it was something as simple as this. I appreciate a lot the time you spent helping me out with this. Thank you very much!

**Comment by daveaglick** [comment]
No problem, just let me know if you hit any more roadblocks.
