### ISSUE TITLE
Add DateInputCulture and DateDisplayCulture settings

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#475]
This consolidates #454 and #467. We should have two standard settings called DateInputCulture and DateDisplayCulture. I'm getting tired of culture problems so we're just going to always use these settings and not rely on the thread culture anymore (will also need to change the docs topic on this matter).

DateInputCulture will determine the culture that gets used when interpreting input dates. Behavior should be:
- If a global metadata value for DateInputCulture is set, use that.
- Otherwise, use the CurrentCulture.

DateDisplayCulture is the culture that should be used for displaying dates when rendering pages. Behavior should be:
- If a global metadata value for DateDisplayCulture is set, use that.
- Otherwise, if the CurrentCulture is English-speaking then use it for date display.
- Otherwise, if the CurrentCulture is not English-speaking use "en-GB".

Add helper methods to support both settings.

**Comment by awulkan** [comment]
Wouldn't it be better to use en-GB if the CurrentCulture is not English-speaking? That way dates would be typed as day/month/year, which most of the world outside of the US is using.

**Comment by gijswijs** [comment]
I don't understand this part of the decision tree:

- Otherwise, if the CurrentCulture is English-speaking then use it for date display.
- Otherwise, if the CurrentCulture is not English-speaking use "en-US".

Why not have the same decision tree for DateDisplayCulture and default to CurrentCulture, regardless of it being English-speaking? So:

- If a global metadata value for DateInputCulture is set, use that.
- Otherwise, use the CurrentCulture.

**Comment by daveaglick** [comment]
@AWulkan Good call, makes sense for fallback to be most-common format.

@gijswijs The problem with the culture used for display is that if it's not English, it'll look really strange since the whole rest of the theme is English text. You'd end up with just the date in another language with English text all around it. Presumably if some other theme were created with non-English text, the default for the fallback would be whatever language the theme is in. I just don't foresee any foreign-language themes anytime soon (though I'd be thrilled to merge one in if someone proves me wrong). Of course, the first part of the logic tree still lets the user use mismatched languages if they really want to.
