### ISSUE TITLE
Running out of memory with very large numbers of documents

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#476]
As reported by @jlnewell - repro is at https://github.com/jlnewell/sdk_wyam

The API has > 50,000 symbols. Getting lots and lots of `System.OutOfMemoryException` and `System.InvalidOperationException` after a long period of rendering:

```
    Executing pipeline "RenderApi" (13/18) with 1 child module(s)
                Exception while parsing HTML for SolidEdgeConstants.SEBlendRadiusType: Exception of type 'System.OutOfMemoryException' was thrown.
                Exception while parsing HTML for SolidEdgeDraft.DVPoint2d.Range(out double, out double, out double, out double): Exception of type 'System.InvalidOperationException' was thrown.
                Exception while parsing HTML for SolidEdgeFramework.eCPDMode: Exception of type 'System.InvalidOperationException' was thrown.
                Exception while parsing HTML for SolidEdgeFrameworkSupport.WeldSymbol.PMIName: Exception of type 'System.InvalidOperationException' was thrown.
                Exception while parsing HTML for SolidEdgeAssembly._IAFGrooveWeldsAuto.Item(object): Exception of type 'System.InvalidOperationException' was thrown.
```

**Comment by daveaglick** [comment]
Can confirm issue still exists with latest develop branch (was kind of hoping this was due to something in Roslyn and the update to 2.0.0 would have resolved it)

**Comment by daveaglick** [comment]
Doing some memory analysis. A lot of the memory growth is due to uncollected string allocations (and specifically `StringBuilder.ToString()` calls). It actually looks like this might be due to rendering a very large number of views within Razor and only tangentially related to docs and a large API in that those scenarios produce a large number of views.

**Comment by daveaglick** [comment]
Okay, now that I think about it, I'm being dense. This makes perfect sense.

Wyam currently stores the content of each document as either a string or a stream. When we run through Razor and render a view, that becomes a string that gets associated with a document. With > 50,000 symbols, that's 50,000 individual Razor views that are getting created (probably more). That's a lot of documents, each one with a reference to a string that holds the rendered HTML. Each of those strings is potentially many KB depending on size of the page.

Not sure how to address this - going to have to try some things. One option might be to check the number of input documents for the Razor module and use temp files instead of strings for the content. That wouldn't solve the more universal "tons of documents with string content" problem though. Another option might be to handle this at the core and once we exceed a certain threshold, just automatically create temp files to hold the string content of new documents.

**Comment by daveaglick** [comment]
Another (wild) idea might be to make fetching content from a document into a function. While we get document metadata a lot, we typically only need to get the content for a document once. If the part of the module that creates the content is deferred until the content is needed, it could reduce memory pressure. On the other hand, it would result in some odd verbose logs since things like rendering Razor would happen during the WriteFiles module when the content is written to disk.

A lightweight way to implement the deferred rendering idea would be to create a Stream that calls the rendering function when content is requested. That might be a way to test out the concept without committing to a large under-the-hood architecture change.

**Comment by jlnewell** [comment]
Thanks for looking into the issue @daveaglick. A possible workaround: I noticed that wyam.exe is built as x86. If you could provide a x64 or Any CPU release, we might be able to get past the out of memory exceptions. Also, the following changes to app.config could potentially increase performance in the x64 build. I use this on other projects that I work on that deal with large datasets. One 3rd party software I work with in particular, it made a huge improvement.

**app.config**
```
<?xml version ="1.0"?>
<configuration>
   <runtime>
      <gcServer enabled="true"/>
   </runtime>
</configuration>
```

You may have your reasons for providing only x86 that I am unaware of. Just thought I'd mention this possible option. I acknowledge that the code could likely stand to be optimized to handle this scenario.

**Comment by daveaglick** [comment]
Nope, no reason at all - the console app and all the libraries should probably be Any CPU and I'll be darned if I can think why it was set to x86. Probably been like that since the beginning and I never noticed.

I'll also turn on the server GC - most systems are multiprocessor these days so that's another one that is probably best turned on regardless.

Hopefully between those build changes and some additional work on the logic side we can get this to work. It's been a fantastic use case to tinker with getting very large builds to run - thanks again for bringing it up and providing a repo.

**Comment by daveaglick** [comment]
Success!

The build takes about 10 minutes (I'm not a miracle worker) and memory use stays relatively sane and caps around 3 GB for me. It only took totally changing the way the most fundamental data structure works :smile:.

I ended up not even turning on the temporary files (though I left that feature in just in case someone needs it - it really kills performance). Instead most of the gains come from a new pooled stream implementation from #477. I've got other long-term ideas to reduce build times for sites like these, but for upwards of 50,000 pages that doesn't seem too bad.

I've still got some cleanup to do and need to apply the concepts put in place for this to the rest of the modules. This was an excellent experiment in memory usage patterns and the whole system is much better off for it, thanks! You should be good to go in the next release.

![2017-03-17_15h48_28](https://cloud.githubusercontent.com/assets/1020407/24060490/cf1bb178-0b29-11e7-91e1-4e4e018b5a1a.png)
