### ISSUE TITLE
Disable 32-bit preference

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#484]
Current problem is that Kestrel uses libuv which is native. Investigate if there's a way to run as x64 with the 32-bit libuv library on 64-bit platforms.

**Comment by daveaglick** [comment]
Note that this all goes away with Core since it can do runtime native library platform linking

**Comment by daveaglick** [comment]
So here's what I think I'm going to do - we'll leave it as AnyCPU, but turn off the 32-bit preference so it'll run as x64 - users on 32-bit systems will still be able to use it, it'll just spit out a BadImageFormatException in the preview server - if anyone in that position really needs preview support, I can walk them through swapping the libuv library for a x86 version

**Comment by Silvenga** [comment]
@daveaglick you can enable the tests around this now - AppVeyor runs the x64  xunit runner which breaks due to the library. Do you know if VS2017 was able to fix this?

**Comment by daveaglick** [comment]
@Silvenga Yeah, good idea. We should be good to go now. We're still not doing the automatic library selection, but since the 32bit preference is turned off it'll run as x64 and I changed the csproj hack to pull that library instead of the x86 one. That'll work for now until we go full Core and can distribute all the libuv platform libraries.

**Comment by daveaglick** [comment]
Reopening issue to track enabling associated unit tests.

**Comment by daveaglick** [comment]
Enabled server tests under AppVeyor and confirmed passing.
