### ISSUE TITLE
Recipe for eBook marketing sites

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#488]
This seems to be a common kind of site template and to my knowledge other generators don't have specific support for it. One example is http://flyingsquirrelbook.com. Here's what I see as initial recipe features:

- A Table of Contents page with chapter titles and descriptions (this can probably be generated from a YAML or JSON file)
- An (optional) details page for each chapter with expanded description, sections, excerpt(s)
- An (optional) glossary with terms and descriptions
- A persistent "buy now" or "download now" link/banner on every page
- Testimonials and/or reader comments
- Other arbitrary content pages (for things like videos, author details, supplementary content, etc.)
- An (optional) blog

**Comment by JonDouglas** [comment]
This is an excellent idea. I'm currently using a default blog recipe and custom theme for my book:

http://xamarinandroidbook.com/

The idea for a marketing site would probably have me switching over. However my book is a WIP so I find a blogging style to be needed.

**Comment by daveaglick** [comment]
Finally got the initial recipe project committed (mostly a clone of Blog at this point, and without a theme yet). Going to focus on this template for the initial theme: https://html5up.net/escape-velocity. Also going to work this issue in tandem with #501 so we're not re-inventing the wheel on common pipelines.

**Comment by daveaglick** [comment]
This is essentially done now. Last remaining issue before closing and releasing is figuring out the best way to allow changing theme colors. The original theme from HTML5 uses Sass, but we're still working on a Sass library. Might do a setting with inline CSS for now if the color isn't in too many places.

**Comment by daveaglick** [comment]
With the new Sass module (#7), the theme now uses Sass for the colors
