### ISSUE TITLE
Generic types in extension methods does not have a link to the type page

### ISSUE THREAD

**Issue by k94ll13nn3** [statiqdev/Statiq#494]
When trying to use the docs recipe to create an API documentation, it appears that when using extensions methods on a generic type that returns the same type, like: 
``` cs 
public static Foo<T> Create<T>(this Foo<T> foo) => new Foo<T>();
```
the generated documentation does not create a link to the `Foo<T>` type.
![generic min](https://cloud.githubusercontent.com/assets/10998921/24975252/5a89841a-1fc5-11e7-9fe7-b2981215a25c.png)

At first I thought it was because of the generic type, but with a method that returns `Foo<T>` inside `Foo<T>`:
``` cs 
public class Foo<T>
{
    public Foo<T> Create() => new Foo<T>();
}
```
 it works:
![generic inside](https://cloud.githubusercontent.com/assets/10998921/24975423/e3d485f8-1fc5-11e7-9499-c79a8a24e824.png)

It does not seems to be linked to the extension part either, because when using an extension method on a simple type, like:
``` cs 
public static Foo2 Create<T>(this Foo2 foo2) => new Foo2();
```
the generated documentation is correct.
![notgeneric min](https://cloud.githubusercontent.com/assets/10998921/24975259/5e051762-1fc5-11e7-8572-46ec7d4c531f.png)

I have created a repository reproducing the issue: https://github.com/k94ll13nn3/wyam-generic-issue.

Wyam version: 0.17.4

**Comment by daveaglick** [comment]
Thanks a ton for the repro - this was a tricky on to track down and that helped tremendously. Turns out Roslyn will output different symbols for generic types when used as a method parameter - needed to get the original definition for generic method parameters to match up with the actual type. Fix will go out with next release.
