### ISSUE TITLE
Build error with Wyam 0.17.5

### ISSUE THREAD

**Issue by pascalberger** [statiqdev/Statiq#495]
With Wyam 0.17.5 building was broken for the Cake.Prca website:
https://ci.appveyor.com/project/cakecontrib/cake-prca-website/build/1.0.96

Same commit run with 0.17.4 worked fine: 
https://ci.appveyor.com/project/cakecontrib/cake-prca-website/build/1.0.95

**Comment by pascalberger** [comment]
Also the build for the Cake website seems to fail. See https://ci.appveyor.com/project/cakebuild/website/build/1.0.1025#L349

**Comment by daveaglick** [comment]
Damn. I've been having so many problems with binding and dependency trees lately...

What build image are you using on AppVeyor? If not the Visual Studio 2017 one can you give a quick try changing it to that and rebuild the commit?

**Comment by daveaglick** [comment]
I can repro on AppVeyor with both the Visual Studio 2015 and the Visual Studio 2017 images. I'll work this today and release a new version reverting the changes if I can't figure it out so we're not stuck with it broken over the weekend (I'll be mostly unavailable this weekend).

**Comment by daveaglick** [comment]
Went ahead and unlisted all 0.17.5 packages from NuGet for now.

**Comment by daveaglick** [comment]
Pretty sure this is now resolved with the 0.17.6 release. Hopefully that'll be the last of the package dependency problems now that we're totally moved over to the new Roslyn stuff.
