### ISSUE TITLE
LiveReload not working for virtual directories

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#496]
The browser wants the LiveReload JS at the root but the preview server doesn't want to serve anything at the root.

Either need to change the injected LiveReload path to the virtual directory (and be sure to serve it under the virtual directory) or keep it at the root and modify the preview server to bypass the virtual directory for the LiveReload script and serve it at the root. Leaning towards the first option since there may be reasons not to put anything at the root.

**Comment by daveaglick** [comment]
The problem was that `LiveReload.js` can't properly parse the request URL when a subpath is used so you have to hint with a query string.

**Comment by gep13** [comment]
Sweet! Thanks for sorting this!
