### ISSUE TITLE
Assets not found for docs recipe/theme under virtual directory

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#497]
When using a virtual directory for the preview server the paths for assets in the docs recipe/theme don't seem to update to reflect the virtual path. That causes a bunch of them not to load.

**Comment by gep13** [comment]
@daveaglick...

Just to be clear, this isn't *only* when using the preview server.  I have deployed a site here:

https://cake-contrib.github.io/Cake.AliaSql/

and as you will see, the assets aren't found there either:

![image](https://cloud.githubusercontent.com/assets/1271146/25088277/ff916f04-236c-11e7-944a-773568d17360.png)

But perhaps it is the configuration that is wrong here:

https://github.com/cake-contrib/Cake.AliaSql/blob/develop/docs/input/_Bottom.cshtml#L11

**Comment by daveaglick** [comment]
That's certainly *part* of the problem. I've submitted a PR to correct the two links in the `_Bottom.cshtml` file, but in the course of testing it out I also found a few in the theme that needed to be corrected as well.

**Comment by gep13** [comment]
Nice one, thank you for the PR!

**Comment by daveaglick** [comment]
Fixed the remaining links in the theme and [updated the documentation to better explain how to use virtual directories in themes](https://wyam.io/docs/extensibility/creating-a-theme#notes). Changes will go out with next release and that resolves this specific issue - still need to fix the injected LiveReload script path for virtual directories (#496)

**Comment by gep13** [comment]
@daveaglick nice one, thank you!
