### ISSUE TITLE
Getting errors while building a site with TFS Build

### ISSUE THREAD

**Issue by devingoble** [statiqdev/Statiq#499]
I'm trying to build a site as part of a TFS build using the PowerShell task, but I'm having trouble getting it to work.

Here's the script that's being run:
```
param(
		[Parameter(Position=1)]
		[string]$DocCorePath,
		[Parameter(Position=2)]
		[string]$PathToBuild,
		[Parameter(Position=3)]
		[string]$OutputPath,
		[Parameter(Position=4)]
		[string]$NugetPath
	)

Write-Verbose "Path to doc project: $DocCorePath" -Verbose
Write-Verbose "Input path to build: $PathToBuild" -Verbose
Write-Verbose "Output path: $OutputPath" -Verbose
Write-Verbose "Nuget Path: $NugetPath" -Verbose

$wyamPath = Get-ChildItem (Join-Path $DocCorePath "packages\Wyam*") -Recurse -Filter "Wyam.exe" | Select-Object -First 1 | Select -ExpandProperty FullName

if(Test-Path $wyamPath) {
	Write-Output "Success"
} else {
	Write-Output "Fail"
}

$wyamArgs = "build --input `"$PathToBuild`" --output `"$OutputPath`" --nuget-source `"$NugetPath`" --verbose"
$wyamCommand = "&`"$wyamPath`" $wyamArgs"
Write-Output $wyam
Invoke-Expression $wyam
```

$wyamCommand looks like this:
```
&"E:\Agent\_work\10\s\Tooling\packages\Wyam.0.17.6\tools\Wyam.exe" build --input "E:\Agent\_work\10\s\Docs" --output "e:\Deployment\Docs" --nuget-source "https://internalnugetserver:443/nuget" --verbose
```
However, I end up with an error in the console output: 
```
##[error]Process completed with exit code -2146232576.
```
The same script runs fine when run locally. Is there a way to get more detailed errors?

**Comment by daveaglick** [comment]
I'll call in @wekempf for reinforcement to see if he's seen anything similar before when running Wyam via PowerShell. If not, I'll see if I can replicate.

It's interesting that you're not getting any output at all given you're in verbose mode - typically I'd expect to see *something* since it starts spitting out messages to the console almost right away.

**Comment by daveaglick** [comment]
One question would be the version of .NET Framework the TFS server has installed. Wyam currently requires 4.6.2 since we're using some recent netstandard stuff (eventually Wyam is going .NET Core, but for now we're kind of balancing between the two worlds).

**Comment by devingoble** [comment]
That's it. Silly me assumed that the build server was being kept up to date, but apparently it's still on 4.6.1. Those responsible have been sacked.

Thank you!
