### ISSUE TITLE
TypeInitilizationException in Module GitContributors

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#506]
Hi,

I just tried to update to the current Wyam version from 16.2 to 17.7.
Now I can no Longer use the GitContributor.

I now get following error

```
Exception during execution: System.TypeInitializationException: Der Typeninitialisierer f�r "LibGit2Sharp.Core.NativeMethods" hat eine Ausnahme verursacht. ---> System.DllNotFoundException: Die DLL "git2-a5cf255": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.
   bei LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   bei LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\NativeMethods.cs:Zeile 36.
   bei LibGit2Sharp.Core.NativeMethods..cctor() in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\NativeMethods.cs:Zeile 81.
   --- Ende der internen Ausnahmestapel�berwachung ---
   bei LibGit2Sharp.Core.NativeMethods.git_repository_open_ext(git_repository*& repository, FilePath path, RepositoryOpenFlags flags, FilePath ceilingDirs)
   bei LibGit2Sharp.Core.Proxy.git_repository_open_ext(String path, RepositoryOpenFlags flags, String ceilingDirs) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\Proxy.cs:Zeile 2565.
   bei LibGit2Sharp.Repository.IsValid(String path) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Repository.cs:Zeile 216.
   bei Wyam.Git.GitModule.GetRepositoryPath(IExecutionContext context)
   bei Wyam.Git.GitModule.GetCommitDocuments(IReadOnlyList`1 inputs, IExecutionContext context)
   bei Wyam.Git.GitContributors.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   bei Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:Zeile 191.
   bei Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionContext.cs:Zeile 212.
   bei Wyam.Core.Modules.Control.If.Execute(IReadOnlyList`1 inputs, IExecutionContext context) in E:\Code\Wyam\src\core\Wyam.Core\Modules\Control\If.cs:Zeile 119.
   bei Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:Zeile 191.
   bei Wyam.Core.Execution.ExecutionPipeline.Execute(Engine engine) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:Zeile 85.
   bei Wyam.Core.Execution.Engine.Execute() in E:\Code\Wyam\src\core\Wyam.Core\Execution\Engine.cs:Zeile 285.
Der Typeninitialisierer f�r "LibGit2Sharp.Core.NativeMethods" hat eine Ausnahme verursacht.
System.TypeInitializationException: Der Typeninitialisierer f�r "LibGit2Sharp.Core.NativeMethods" hat eine Ausnahme verursacht. ---> System.DllNotFoundException: Die DLL "git2-a5cf255": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.
   bei LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   bei LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor()
   bei LibGit2Sharp.Core.NativeMethods..cctor()
   --- Ende der internen Ausnahmestapel�berwachung ---
   bei LibGit2Sharp.Core.NativeMethods.RemoveHandle()
   bei LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject.Finalize()
```

Maybe it is related to the Update in the Libgit2Sharp version. The dll git2-a5cf255 is not there. But I haven't found out yet what the Problem is.

**Comment by LokiMidgard** [comment]
Explicitly adding the missing nuget package that contains the dll does also not help (#n LibGit2Sharp.NativeBinaries -v [1.0.164]). I guess the dll's under the folder runtimes in the package get ignored. Maybe somewhere is a missing configuration of the current platform so nuget uses none of theses. Or runtimes are treated differently.

I haven't found anything that will fix this besides manually copping the missing dll in the ```Tools/Wayam/Tools``` folder. Which I would not call a real fix. For now I will stay on an older version. Maybe I will look into it when I got more time.

**Comment by daveaglick** [comment]
Adding the NativeBinaries package is half the solution. It sounds like that package is probably using the new runtimes packing method - old csproj projects don't understand this so the correct library isn't getting moved where it needs to go.

It'll light up correctly with the move to Core and the new csproj format. For now there's a workaround - I've had to use it for a couple other modules with native dependencies. I'll get this resolved before the next release early next week.

**Comment by daveaglick** [comment]
Pretty sure this is now resolved - if you get a chance, go ahead and test it out on the develop branch. If not, I'm trying to get the next release out soon so let me know if it's still failing after that.

**Comment by LokiMidgard** [comment]
Unfortunatly it didn't changed.

Not sure if I actually used the nuget urls correctly has been some time till I last used develop.

deploy.cake
```
#tool nuget:https://www.myget.org/F/wyam/api/v2?package=Wyam&prerelease
#addin nuget:https://www.myget.org/F/wyam/api/v2?package=Cake.Wyam&prerelease
```

config.wyam
```
#n Wyam.All -s https://www.myget.org/F/wyam/api/v2?package=Wyam&prerelease
#n LibGit2Sharp.NativeBinaries
```

Console says : ```Wyam version 0.18.0-build-837```. Still the same error ```System.DllNotFoundException:  "git2-a5cf255": HRESULT: 0x8007007E``` and I don't see the dll in any folder under my project.

**Comment by daveaglick** [comment]
Thanks - pretty sure I now know why this still isn't working. Still working on it, but should be resolved in the final release.

**Comment by daveaglick** [comment]
I'll leave issue closed since it should be resolved very soon, but we'll reopen if it still doesn't work after release.

**Comment by LokiMidgard** [comment]
Well 18.2 build perfectly. Thanks. :)
