### ISSUE TITLE
Incorrect link with the default Docs recipe

### ISSUE THREAD

**Issue by mgrosperrin** [statiqdev/Statiq#521]
Hello,

in order to try Wyam, I have follow the overview of the [Docs recipe](https://wyam.io/recipes/docs/overview).
When browsing the resulting site, all links to a page are broken.
For example, the link to the about page is `/about` but the real page is `/about.html`.

I have configured my server to server `index.html` as default page, so the `/docs`, `/blog`, etc. links work fine.

Is there a parameter to set to add the extension to the link of every page ?

**Comment by daveaglick** [comment]
Wyam assumes the site will be deployed to a host that support extensionless URLs and hides index files by default. When it generates links, those assumptions are taken into account and the links drop extensions and index files. This results in much nicer URLs, but makes the site unviewable directly from the local file system. To address this, Wyam also ships with a preview server that gets activated when you use the `--preview` argument on the command line. This preview server does support extensionless URLs and hidden index files so it can be used to preview your site.

All that said, these settings are configurable. If you want to turn them off, add the following to your `config.wyam` file:

```
Settings[Keys.LinkHideExtensions] = false;
Settings[Keys.LinkHideIndexPages] = false;
```

You can read more about the available settings at https://wyam.io/docs/usage/settings (and each recipe also has it's own set of settings).

**Comment by mgrosperrin** [comment]
Thank you Dave, it is exactly what I was looking for.

I will read the rest of the documentation before asking other questions 😄 .
