### ISSUE TITLE
Create helper methods for Razor templates

### ISSUE THREAD

**Issue by dodyg** [statiqdev/Statiq#53]
There are common operations such as reading files and listing them that can be provided out of the box. I am going to use this issue to keep track of various patterns that keep cropping up when trying to build a decent website.

```
<div class="row">
@foreach(var x in Html.List(root, "images\\catalog\\birds")){
 <div class="col-xs-6 col-md-3"> 
    <a href="@Html.ToWebPath(Html.Suffix(x, "-medium"))" class="thumbnail"><img src="@Html.ToWebPath(Html.Suffix(x, "-thumb"))"/></a>
  </div>
}
</div>
```

**Comment by daveaglick** [comment]
Now that the Wyam Razor implementation is built on top of the stock ASP.NET Core MVC Razor engine, any helpers that are designed for ASP.NET Core MVC should also work with Wyam. That should cover most cases. If there are any other helper functions that are needed, let's open separate issues for them.
