### ISSUE TITLE
Discussion: Change "server listening on port 5080" to "server is listening at http://localhost:5080"

### ISSUE THREAD

**Issue by ghuntley** [statiqdev/Statiq#533]
Howdy,

Quick proposal to change this message to be a URL (some terminals even support parsing/clicking them to open a browser!) so I don't have to manually type stuff...

```
Preview server listening on port 5080 and serving from path file:///C:/Dropbox/OSS/reactiveui/wyam/output and LiveReload support
Watching paths(s) file:///C:/Users/ghuntley/.nuget/packages/Wyam.Docs.Samson.0.18.4/content, theme, input
Watching configuration file file:///C:/Dropbox/OSS/reactiveui/wyam/config.wyam
```

**Comment by daveaglick** [comment]
Great idea, never even occurred to me some terminals might link a URL. Wonder if VS Code does, hot if so. Easy change, so I'll add it for the next release.

**Comment by daveaglick** [comment]
Change made. Looks like VS Code does link the URL with a Ctrl-click, which is awesome.
