### ISSUE TITLE
Can no longer "stack" modules in the PipeCollection.Add method

### ISSUE THREAD

**Issue by deanebarker** [statiqdev/Statiq#538]
Working in LINQPad, this used to work:

    engine.Pipelines.Add("MyPipeline",
      MyModule(),
      MyOtherModule()
    );

It seemed like the method signature for `Add` was:

    public void Add(string name, params IModule modules)

After the name of the pipeline, you could just stack modules forever, due to the `params` modifier.

But that stopped working last time I updated the Nuget package. Now I get an error:

    No overload for Method 'Add' takes 3 arguments.

I have to do this now:

    engine.Pipelines.Add("MyPipeline", new ModuleList() {
      MyModule(),
      MyOtherModule()
    });

Was this intentional? If so, what was the reasoning behind the change?

**Comment by daveaglick** [comment]
I'll need to dig into this one when I get some downtime. The pipeline `Add` methods did change a bit to support more advanced recipe pipeline customization, but almost positive that shouldn't prevent the params use.

**Comment by daveaglick** [comment]
The `Add` method that takes a `params` was moved to an extension method - all the utility methods were getting too much to maintain right in the class. Extensions have to be explicitly in-scope, so you'll need to add the namespace `Wyam.Common.Execution` to your LINQPad script. Then you should be good to go - let me know if you still have trouble after that.

**Comment by deanebarker** [comment]
Yes, this worked thanks.
