### ISSUE TITLE
Possible casing issue for links to docs category pages

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#546]
See [this link](https://github.com/punker76/mahapps.metro.docs.wyam/blob/17c6177aa74396a54fa214a8319daab9d2936ec7/blog/index.html#L120). The category specified in the posts and the generated category index file both use `Release` but the generated link seems to be all-lower. This causes problems on hosts like GH Pages that use case-sensitive URLs.

**Comment by daveaglick** [comment]
@punker76 this should be resolved for you now and the fix will go out with the next release. Thanks for the bug report.

**Comment by punker76** [comment]
@daveaglick thx for fixing this 👍
