### ISSUE TITLE
Inheritdoc does not seem to work for properties

### ISSUE THREAD

**Issue by k94ll13nn3** [statiqdev/Statiq#553]
When using `inheritdoc` on an implementation of an interface with a method and a property, the documentation is correctly generated for the class summary and the method, but for the property, it stays empty.

Wyam version: 0.18.6

I just have the template generated by `Wyam new -r Docs` and a source file:
``` csharp
namespace N
{
    /// <summary>
    /// Interface IFoo.
    /// </summary>
    public interface IFoo
    {
        /// <summary>
        /// Gets Bar.
        /// </summary>
        string Bar { get; }

        /// <summary>
        /// BarMethod.
        /// </summary>
        /// <param name="arguments">Arguments.</param>
        /// <returns>A bool.</returns>
        bool BarMethod(string[] arguments);
    }

    /// <inheritdoc />
    public class Foo : IFoo
    {
        /// <inheritdoc/>
        public string Bar => "Bar";

        /// <inheritdoc/>
        public bool BarMethod(string[] arguments) => true;
    }
}
```

And here is a screenshot of the bug:
![bug-interface](https://user-images.githubusercontent.com/10998921/29427095-04c27668-8389-11e7-8db8-5b52b430c617.PNG)

**Comment by daveaglick** [comment]
This is now resolved. The `inheritdoc` support is all home-grown and there were some cases where properties and events weren't getting picked up. The fix will go out with the next release.
