### ISSUE TITLE
API search with virtual dir has wrong path

### ISSUE THREAD

**Issue by k94ll13nn3** [statiqdev/Statiq#554]
When using the API search feature in the docs recipe under a virtual dir, the links generated by the search have the wrong path: if the virual dir is `/virtual`, the links are generated with `/virtual/virtual`. It works fine when there is no virtual dir.

Wyam version: 0.18.6

I just have the template generated by `Wyam new -r Docs`, `Settings[Keys.LinkRoot] = "/virtual";` and a source file:
``` csharp
namespace N
{
    public class Foo
    {
        public string FooBar => "FooBar";
    }

    public class Bar
    {
        public string BarFoo => "BarFoo";
    }
}
```

Here is, I think, the part of `/searchIndex.js` that is used for the links:
``` javascript
    y({
        url:'/virtual/virtual/api/N/Bar',
        title:"Bar",
        description:""
    });

    y({
        url:'/virtual/virtual/api/N/Foo',
        title:"Foo",
        description:""
    });
```

**Comment by daveaglick** [comment]
Good catch, thanks. The search index items were being double-generated which resulted in adding the virtual path twice.
