### ISSUE TITLE
wyam.io server problem from Iran

### ISSUE THREAD

**Issue by rseyf** [statiqdev/Statiq#558]
Hi there!
Thank you for your awesome tool, Wyam. 
I want to report that your website is not available for Iranian users.  It's not censored by ISPs , the server cannot handle requests from Iranian IP addresses. no ping replies.
Please provide a solution for this. We had to download and use Wyam binary from github repository releases.

Thanks.

**Comment by daveaglick** [comment]
Sorry about that - I'll check with my host and see if they're aware of any issues with availability from Iran. I'll get back to you.

**Comment by daveaglick** [comment]
@rseyf Are you able to perform a DNS lookup on the site (`nslookup -d2 wyam.io`)? And can you reach https://www.netlify.com? Also wondering if it has something to do with the site being SSL only...any issues with HTTPS traffic from where you are?

**Comment by rseyf** [comment]
@daveaglick as you asked for:
DNS lookup result:
<pre>
reza@seyf:~ $ nslookup -d2 wyam.io
main parsing wyam.io
addlookup()
make_empty_lookup()
looking up wyam.io
setup_system()
create_search_list()
ndots is 1.
copy_server_list()
make_server(192.168.110.250)
make_server(4.2.2.4)
make_server(8.8.4.4)
lock_lookup dighost.c:4222
success
start_lookup()
setup_lookup(0x5624cf876498)
resetting lookup counter.
cloning server list
clone_server_list()
make_server(192.168.110.250)
make_server(4.2.2.4)
make_server(8.8.4.4)
libidn_locale_to_utf8
libidn_utf8_to_ascii
using root origin
output_filter
wyam.io.
recursive query
add_question()
starting to render the message
done rendering
create query 0x7fa84a06f018 linked to lookup 0x5624cf876498
create query 0x7fa84a06f268 linked to lookup 0x5624cf876498
create query 0x7fa84a06f4b8 linked to lookup 0x5624cf876498
do_lookup()
send_udp(0x7fa84a06f018)
bringup_timer()
have local timeout of 1
working on lookup 0x5624cf876498, query 0x7fa84a06f018
sockcount=1
recving with lookup=0x5624cf876498, query=0x7fa84a06f018, sock=0x7fa84a071010
recvcount=1
sending a request
unlock_lookup dighost.c:4224
lock_lookup dighost.c:2732
success
send_done()
sendcount=0
check_next_lookup(0x5624cf876498)
still have a worker
unlock_lookup dighost.c:2763
recv_done()
lock_lookup dighost.c:3606
success
recvcount=0
lookup=0x5624cf876498, query=0x7fa84a06f018
before parse starts
after parse
printmessage()
Server:		192.168.110.250
Address:	192.168.110.250#53

Non-authoritative answer:
printsection()
output_filter
wyam.io.
Name:	wyam.io
Address: 104.198.14.52
still pending.
cancel_lookup()
check_if_done()
list empty
clear_query(0x7fa84a06f268)
clear_query(0x7fa84a06f4b8)
clear_query(0x7fa84a06f018)
sockcount=0
check_next_lookup(0x5624cf876498)
try_clear_lookup(0x5624cf876498)
destroy
freeing server 0x7fa8380008e8 belonging to 0x5624cf876498
freeing server 0x7fa838001108 belonging to 0x5624cf876498
freeing server 0x7fa838001928 belonging to 0x5624cf876498
start_lookup()
check_if_done()
list empty
shutting down
dighost_shutdown()
unlock_lookup dighost.c:4123

done, and starting to shut down
cancel_all()
lock_lookup dighost.c:4238
success
unlock_lookup dighost.c:4281
destroy_libs()
freeing task
freeing taskmgr
lock_lookup dighost.c:4313
success
flush_server_list()
freeing commctx
freeing socketmgr
freeing timermgr
destroy DST lib
detach from entropy
unlock_lookup dighost.c:4370
Destroy the messages kept for sigchase
Removing log context
Destroy memory
</pre>

[Netlify](https://www.netlify.com/)  is reachable from Iran IP address. 
I have uploaded two screenshots  [ [1st](http://seyf.fr/wyam.io/issue1.png) , [2nd](http://seyf.fr/wyam.io/issue2.png)  ]  for you  to see what happens when I'm trying to open wyam.io by using my office workstation.  
today, ping replies,  but no website shows up. If I use proxy or connect to vpn (outside of Iran)  , it works but with Iran's IP address, nothing shows up .
I had used 3 different ISP's before submitting this issue to make sure problem is not ISP related.
But as you said, maybe the problem comes from SSL issues. 
<hr>
PS: Google blocks Iranians from using Google servers, are you using Google services for delivering your website?

**Comment by MaximRouiller** [comment]
```none
make_server(192.168.110.250)
make_server(4.2.2.4)
make_server(8.8.4.4)
```

This looks like it's making its way internally, to a Level-3 DNS(`4.2.2.4`) and bounce it back to Google (`8.8.4.4`).

Have you tried from a public cafe or another area? It looks like an issue with how DNS is being bounced on your end.

**Comment by rseyf** [comment]
@MaximRouiller Yes, I had tested mobile Data , different ISPs with different devices (smartphone,tablet,laptop) , no website shows up. :(

**Comment by daveaglick** [comment]
I’m going to go ahead and close this as being an upstream problem with my host Netlify. Hopefully whatever Internet hiccups were preventing the routing between them and Iran have been resolved by now.
