### ISSUE TITLE
Missing files when using setup.exe

### ISSUE THREAD

**Issue by dpen2000** [statiqdev/Statiq#565]
I installed 0.18.6 with setup.exe. When I put wyam in my path and tried to run wyam, I got:
```Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.```

My \AppData\Local\Wyam\app-0.18.6 folder was in fact missing this and a few other DLLs. The zip download for this release did contain all missing DLLs.

**Comment by daveaglick** [comment]
Thanks for the report. Glad you were able to get up and running with the zip. I've had some issues with the installer and will probably remove it entirely after 1.0 in favor of a different release mechanism (haven't decided what - maybe a dotnet bootstrapper tool or something).

I'll take a closer look at this - if I can't quickly figure out why the installer isn't bundling all the assemblies, I'll probably remove it for 1.0 too.

**Comment by daveaglick** [comment]
I’m going to close this issue - the installer has been deprecated in 1.0 and a Chocolaty package will be available with the next release. I’m also looking at other distribution strategies for 2.0 when Wyam moves to .NET Core - maybe something like a bootstrapped CLI tool. In any case, the old Windows Installer .exe won’t have another release.
