### ISSUE TITLE
Bug with trailing space

### ISSUE THREAD

**Issue by ghuntley** [statiqdev/Statiq#566]
# Information
![image](https://user-images.githubusercontent.com/127353/30114019-db43b5fa-9359-11e7-8ff5-09f34070ae16.png)

Create a blog post w/filename such as `2017-09-05-assemblies-are-now-signed-with-the-dotnet-foundation-code-signing-certificate .md` (clone the ReactiveUI website to repro I guess)

The blog post displays correctly in `/blog` but clicking on the link is a 404 when using `build.cmd --target preview`

There are no warnings in the console.

# Severity
💄 and polish territory

**Comment by daveaglick** [comment]
Easy fix - `NormalizedPath` was trimming spaces, now only trims non-printables.
