### ISSUE TITLE
Add ElementQuery to Wyam.Modules.Html

### ISSUE THREAD

**Issue by dodyg** [statiqdev/Statiq#57]
I butchered Excerpt to take QuerySelectorAll and extract a specific attribute value from matching elements. Excerpt only takes the first match. We need a module that takes multiple matching elements and allow extract of its attributes or content (check below's one off migration script)

```
var segment = "sandboarding";

Pipelines.Add("Download",
    Execute(x => {
        Func<Task<Stream>> download = async () => {
            var url = $"http://siwawi.com/en/catalog/{segment}";
            using(var client = new HttpClient()){
                using (HttpResponseMessage response = await client.GetAsync(url)){
                    using (HttpContent content = response.Content){
                        Stream result = await content.ReadAsStreamAsync();

                        var mem = new MemoryStream();
                        result.CopyTo(mem);
                        return mem;
                    }
                }
            } 
        };

        var res = download().Result;

        return new[] { x.Clone(res) };
    }),
    Excerpt("a.popup").SetMetadataKey("image").SetAttribute("href"),
    Execute(x => {
        Func<Task<Stream>> download = async () => {
            var url = "http://siwawi.com" + x.Metadata["href"].ToString().Replace("&resize=xlarge","");
            using(var client = new HttpClient()){
                using (HttpResponseMessage response = await client.GetAsync(url)){
                    using (HttpContent content = response.Content){
                        Stream result = await content.ReadAsStreamAsync();

                        var mem = new MemoryStream();
                        result.CopyTo(mem);
                        return mem;
                    }
                }
            } 
        };

        var res = download().Result;

        return new IDocument[] { x.Clone(res, new Dictionary<string, object>{
             { "WritePath", $"F:\\Repository\\Web Content\\Output\\Siwawi\\images\\catalog\\{segment}\\" + DateTime.Now.Ticks + ".jpg"}
            })
        };
    }),
    WriteFiles("*")    
 );

```

**Comment by daveaglick** [comment]
A more general HTML query module shouldn't be hard to write at all - it would probably look very similar to `Excerpt` (which I'd want to keep focused on the simple case of getting the InnerHtml of some element, presumably the first paragraph). The new more general module could be called `HtmlQuery` or something similar.

I've got two questions:
- What should get returned?
  
  Depending on the type of DOM node that the query selector returns (element, text, attribute), there are different possibilities for what to get. An element has InnerHtml, OuterHtml, and InnerText. An attribute doesn't have any of those, but it has a value. Maybe allowing the user to choose what to return by using an enum or something would work best.
- What should be done with it?
  
  In the case above you're adding the returned content to the metadata key `image`. In the case of metadata, how should multiple query results be handled? Maybe as a collection for the specified metadata key? Another possibility would be to clone new documents with their content set to the returned content from the HTML query. Maybe two modules are in order, one that sets metadata and one that clones documents - or maybe make this an option in the single module?

Also, aside from the subject of this issue, I love the use of Execute in your example to download some HTTP resources. This kind of config is _exactly_ the sort of scenario I had in mind when first envisioning Wyam as a "code-based" static site generator.

**Comment by dodyg** [comment]
- https://github.com/Wyamio/Wyam/blob/develop/Wyam.Modules.Html/Excerpt.cs has `SetMatadataKey` (misspelling) 

**Simple scenario**

Source

```
<ul>
  <li data-id="1" class="active">NYTimes</a></li>
  <li data-id="2">WashingtonPost</a></li>
</ul>
```

Processing

```
    HtmlQuery('li')
       .SetAttribute("data-id")
       .SetAttribute("class")
       .SetInnerText("inner")
       .SetInnerHtml("innerH")
       .SetOuterHtml("Outer")
```

Result(1 out of 2)

```
   var element = x.Content //<li data-id="1" class="active">NYTimes</a></li>
   var data = x.Metadata["data-id"]//1
   var @class = x.Metadata["class"]//active
   var innerText = x.Metadata["inner"]//NYTimes
   var innerHtml = x.Metadata["innerH"]//null
   var outer = x.Metadata["outer"]//<li data-id="1" class="active">NYTimes</a></li> 
```

**Inner/Outer Html Problem**

The problem I realized yesterday when hacking on `Excerpt` was that I get the matched elements as string and I don't have any tools from the config to deal with parsing it further.

```
<li data-id="1">
<a href="http://www.nytimes.com"><h1>NYTimes</h1></a>
</li>
```

If my query selector returns this result, I am pretty much paralyzed. I can solve the issue by making more elaborate query selector to get precisely what's needed but sometimes that gets really hairy.

Now if I can get some methods somehow to parse this element further without passing it to another module and return what I need, that would be amazing.

**Comment by avishnyakov** [comment]
Hm.. a good discussions.

Can see the HtmlQuery module, but the following flow is not supported:

``` cs
HtmlQuery('li')
       .SetAttribute("data-id")
       .SetAttribute("class")
       .SetInnerText("inner")
       .SetInnerHtml("innerH")
       .SetOuterHtml("Outer");
```

For instance, a post-processing for the rendered html to get bootstrap classes set correctly for all img tags. I would see that as following, hoverer no SetAttribute() method can be found in HtmlQuery module. 

Is that correct assumption that HtmlQuery would see a current document as HTML allowing some modification over attributes and tags, and then would return the processed HTML further in the pipeline?

``` cs
Pipelines.Add("site-md-content",

    ReadFiles("*.md"),
    FrontMatter(Yaml()),

    Markdown(),
    Razor(),    

    HtmlQuery("img")
        .SetAttribute("class", "img-responsive")
        .SetAttribute("class", "img-thumbnail"),

    WriteFiles("html")
);
```

Another case is to replace markdown render. We have '>' tag in the markdown so that a blockquote HTML tag is rendered. So we'd like to replace all 'blockquote' tags to the following HTML:

``` html
<div class="bs-callout bs-callout-info">
      <p> { HERE WOULD BE ALL blockquote CONTENT  } </p>
    </div>
```

Such thing would render a neat bootstrap styled callout, like 'warning' or 'info'.

Is that correct thinking? Does HtmlQuery work that way and so that it can be enhanced to support .SetAttribute and HTML replacements? 

Generaly speaking HTML post processing would be nice to have. Something close to jQuery selectors in terms of queries and then neat ability to push processed HTML content further to the pipeline.

**Comment by avishnyakov** [comment]
Whatever, here is a workaround. Wyam amazingly extendible, gosh!

``` cs
Pipelines.Add("site-md-content",

    ReadFiles("*.md"),
    FrontMatter(Yaml()),

    Markdown(),
    Razor(),    
    // here we go, adding more attrs for all IMG tags
    Execute( (doc, context) => {

        var result = new List<IDocument>();
        var x = doc;

        AngleSharp.Parser.Html.HtmlParser parser = new AngleSharp.Parser.Html.HtmlParser();
        AngleSharp.Dom.Html.IHtmlDocument htmlDocument;

        try
        {
            using (Stream stream = x.GetStream())
            {
                htmlDocument = parser.Parse(stream);
            }
        }
        catch (Exception ex)
        {
            context.Trace.Warning("Exception while parsing HTML for {0}: {1}", x.Source, ex.Message);
            return new [] { x };
        }

        var images = htmlDocument.QuerySelectorAll("img").ToArray();

        var targetAttValues = new string[] {
            "img-thumbnail",
            "img-responsive",
        };

        foreach (var image in images) {

            var attValue = image.GetAttribute("class");

            if(attValue == null)    
                attValue = string.Empty;
            else
                attValue = attValue.ToLower();

            foreach(var targetAttrValue in targetAttValues) {

                if(!attValue.Contains(targetAttrValue.ToLower())) {
                    attValue += " " + targetAttrValue.ToLower();
                }
            }

            image.SetAttribute("class", attValue);
        }

        var newDoc = x.Clone(htmlDocument.DocumentElement.OuterHtml);
        result.Add(newDoc);

        return result;
    }),

    //HtmlQuery("img")
    //  .SetAttribute("class", "img-responsive")
    //  .SetAttribute("class", "img-thumbnail"),

    WriteFiles("html")
);
```

It goes after all img tags in the HTML and adds two css classes if not there - 'img-responsive' and 'img-thumbnail'. It could have been said that way, I guess:

``` cs
HtmlQuery("img")
        .AddAttribute("class", "img-responsive")
        .AddAttribute("class", "img-thumbnail")
```

Not that .AddAttribute() != .SetAttribute. That comes to several methods similar to jQuery:
- AddAttribute(name, value) - add if not there, don't change the rest
- RemoveAttribute(name, value) - remove if there, don't change the rest
- SetAttribute(name, value) - overwrite the value

Hope HtmlQuery could be enhanced that way, would be truly powerful thing!

**Comment by daveaglick** [comment]
Editing HTML via an object model is a great idea! I think it's appropriate for a new module though since the intent is totally different from HtmlQuery. I've created issue #160 to track.
