### ISSUE TITLE
Cake.Wyam Upgrade to VS2017 and add .NET Core target

### ISSUE THREAD

**Issue by RLittlesII** [statiqdev/Statiq#571]
@daveaglick I know you've got a plan to upgrade Wyam to target .NET Core.  I am opening this issue specifically to track the dependency that [Cake.Recipe](https://github.com/cake-contrib/Cake.Recipe) has on Cake.Wyam.  Trying to get all addins to target .NET Core so they can be loaded from Cake CoreCLR runner.  If I can help in that effort please let me know.

**Comment by daveaglick** [comment]
Good call - Cake.Wyam just shells out so it should be pretty straightforward to port it before everything else is done.

**Comment by RLittlesII** [comment]
Alright.  This on my list of things to do.  You can assign this to me if you'd like.

**Comment by daveaglick** [comment]
Resolved with #573
