### ISSUE TITLE
Cannot get  Settings[Keys.DateTimeDisplayCulture] = "en-US"; to work

### ISSUE THREAD

**Issue by snielsson** [statiqdev/Statiq#574]
I would like my blog to use US english for dates instead of Danish culture which is the culture of the machine I am developing on. I have tried using this setting in config.wyam

    Settings[Keys.DateTimeDisplayCulture] = "en-US";

But I still get danish date strings generated:

    Posted on mandag, januar 30, 2017

**Comment by daveaglick** [comment]
Which theme were you using? Unfortunately I can't override date/time display in general (it's always going to be the thread culture) so it's up to the theme/template to use the special `.ToLongDateString(IExecutionContext)` and related extensions whenever displaying dates or times. Possible one (or more) of the themes are still using the other display methods.

**Comment by daveaglick** [comment]
@snielsson Any updates on which theme was having problems? Would love to get this fixed if one of them isn't using the correct date display handling.

**Comment by snielsson** [comment]
@daveaglick sorry for not getting back before now. I have tested all current themes in version 1.1.0 and they all have the problem:

I used a config.wyam starting like this:
#r blog
#t SolidState
Settings[Keys.DateTimeDisplayCulture] = "en-US";

And I got these results:

#t BlogTemplate: does not show date strings
#t CleanBlog: Shows danish date strings
#t Phantom: Shows danish date strings
#t SolidState: Shows danish date strings
#t Stellar: Shows danish date strings
#t Trophy: Shows danish date strings

What can I do to fix it for now in the SolidState theme?

**Comment by pawelklimczyk** [comment]
@snielsson [https://wyam.io/docs/advanced/setting-the-culture](this) helped me. Both setting the thread culture and keys.

```
System.Globalization.CultureInfo.DefaultThreadCurrentCulture = System.Globalization.CultureInfo.CreateSpecificCulture("en-GB");

Settings[Keys.DateTimeInputCulture] = System.Globalization.CultureInfo.CreateSpecificCulture("en-GB");
Settings[Keys.DateTimeDisplayCulture] = System.Globalization.CultureInfo.CreateSpecificCulture("en-GB");
```
