### ISSUE TITLE
Build Cake.Wyam against Cake 0.22.0 and target .NET 4.6

### ISSUE THREAD

**Issue by pascalberger** [statiqdev/Statiq#578]
To support Cake >= 0.22.0 the Cake.Wyam addin needs to be built against Cake 0.22.0 and target .NET Framework 4.6

**Comment by ProgrammerAL** [comment]
If it helps, I submitted a pull request for this in issue #579.

**Comment by daveaglick** [comment]
Thanks! I'll merge in the PR and get it out with the next release (probably later this week or next).

**Comment by gep13** [comment]
@daveaglick has this shipped?

**Comment by daveaglick** [comment]
No :( - I'm blocked by a project system bug right now that kicked in with the most recent VS/SDK updates. Hopeing tonget that cleared or worked around this week.

**Comment by gep13** [comment]
@daveaglick not a problem, just wanted to touch base.

**Comment by gep13** [comment]
@daveaglick just wanted to touch base on this one again...

The Cake.Wyam addin is now the last one that needs updated in order for Cake.Recipe to start using Cake 0.22.0.  Do you have a time line for when you think you will be in a position to ship this?

Thanks.

**Comment by daveaglick** [comment]
Hopefully soon - I've been working through some blocking issues with Wyam proper after converting to SDK style projects. Had a breakthrough yesterday so I think I'm getting close. My hope is for a release this week.

**Comment by gep13** [comment]
@daveaglick that is great news!  Thank you for the update!

**Comment by daveaglick** [comment]
Resolved by #573 - new release going out shortly (providing my move to SDK projects doesn't screw up my release scripts)

**Comment by gep13** [comment]
@daveaglick great news, thank you for the update!

**Comment by daveaglick** [comment]
Don't get too excited. I'm hitting blocker after blocker. Was hoping to get this out yesterday, but at this rate it might be early next week instead.

**Comment by gep13** [comment]
Aw man! Sounds like you are not having fun at all 😢 

Hope you get you the bottom of it.

**Comment by daveaglick** [comment]
Finally! 1.1.0 is going out now, you should be good to go with newer Cake versions.

**Comment by gep13** [comment]
That is great news, thank you!
