### ISSUE TITLE
Critical bug at Razor module on console --preview and --watch

### ISSUE THREAD

**Issue by dodyg** [statiqdev/Statiq#58]
If you are using section in `@RenderSection("MySection", false)` in _layout.cshtml  and `@section MySection` in a page, a watch trigger will generate error. The console will throw `Section MySection is already defined` every time you modify a file. It works fine if you end the console and run it again. So it generates error at watch trigger.

This is based on the basic configuration

```
Pipelines.Add("Content",
    ReadFiles("*.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Concat(
        ReadFiles("*.cshtml").Where(x => Path.GetFileName(x)[0] != '_'),
        FrontMatter(Yaml())     
    ),
    Razor(),
    WriteFiles(".html")
);
```

**Comment by daveaglick** [comment]
Thanks - I was able to make a unit test reproduce this, so I should have a fix shortly.

**Comment by daveaglick** [comment]
Fixed. Bug due to re-using IRazorPage instances which are not stateless. On subsequent calls, some state, like the list of section writers, was already populated from the previous execution. Fix was to cache the compiled page type and not the page instance.
