### ISSUE TITLE
Tag post excerpts in the BlogTemplate theme outputs HTML as text

### ISSUE THREAD

**Issue by awulkan** [statiqdev/Statiq#580]
As you can see here:
https://wyam.io/recipes/blog/themes/preview/blogtemplate/tags/introduction
The excerpt for each tag is outputting html as plain text.

I personally fixed this by going to this file:
https://github.com/Wyamio/Wyam/blob/develop/themes/Blog/BlogTemplate/_Tag.cshtml

And changing 
```cs
@post.String(BlogKeys.Excerpt)
```
to
```cs
@Html.Raw(post.String(BlogKeys.Excerpt))
```

I don't know if this is the correct way to fix it though since I am new to Razor and Wyam.

**Comment by daveaglick** [comment]
That was exactly right, thanks for tracking it down!
