### ISSUE TITLE
Recipe docs have copy/paste typos

### ISSUE THREAD

**Issue by breyed** [statiqdev/Statiq#582]
For example, the [Docs](https://wyam.io/recipes/docs/overview) recipe Scaffolding section says, "This generates a skeleton set of input files that includes a blog post and a content page." Besides fixing this, it would be good to check to see if there are other copy/paste issues with recipe docs.

**Comment by jbrinkman** [comment]
This should be moved to the wyam-web project as it is a documentation issue and not a framework issue.

**Comment by breyed** [comment]
[Done](https://github.com/Wyamio/Wyam.Web/issues/56). Sorry about that. I checked there first, but though that repo didn't have GitHub Issues enabled. Turns out I was looking at the wrong line.
