### ISSUE TITLE
FIPS Compliant Hashing

### ISSUE THREAD

**Issue by kakrofoon** [statiqdev/Statiq#596]
My organization requires FIPS compliant hashing for all servers, including our build server.
I'm proposing that the code base be updated to use one of the SHA hashing algorithms instead.

**Comment by daveaglick** [comment]
I'm certainly open to the idea as long as it's not a big performance hit, but you might need to help me understand the request a little better. We do some hashing for caching purposes, but that's all transient. Are you able to point me to somewhere in the codebase that would need to be changed?

**Comment by kakrofoon** [comment]
I've submitting a pull request that's only 3 lines of changes.  The issue is that you're currently using MD5 to generate the hashes; this is disallowed on FIPS compliant server settings.

**Comment by kakrofoon** [comment]
SHA is slower than MD5 for older CPUs, by a factor of about 5.  For modern CPUs with SHA acceleration functions and SIMD it should not make much of a difference; either will be much faster than the disk.  It looks like the only things hashing is used for is to see if the configuration changes or if the Razor pages have changed in flight, so I'd imagine the difference would be negligible.

**Comment by daveaglick** [comment]
Thanks a bunch - that PR is exactly what I was looking for. I had no idea FIPS compliance was even a problem, but just read some more about it and definitely want to get this patched so folks with the compliance flag can still use it.

I did some benchmarks and thankfully I don't see this as a problem (at least on my machine!):

 Method |      Mean |    Error |    StdDev |    Median |
------- |----------:|---------:|----------:|----------:|
Sha512 | 162.62 us | 9.932 us | 29.129 us | 150.95 us |
Md5 |  36.86 us | 1.268 us |  3.739 us |  36.11 us |

That's only ~150 ms difference over 1,000 hashes. At 10,000 hashes we're into seconds, but even then so much else would be going on by that point (including disk access) that I just don't see it being a large contributor.

Thanks! I'll merge the PR and it'll go out with the next release.

**Comment by kakrofoon** [comment]
Awesome!  Thanks!
