### ISSUE TITLE
Multilingual web with Wyam?

### ISSUE THREAD

**Issue by tesar-tech** [statiqdev/Statiq#599]
Is there any recommended way how to make web bilingual?

**Comment by daveaglick** [comment]
There isn't really any built-in capabilities for localization. There are probably a couple ways to tackle this off the top of my head:
* Brute-force it by creating the appropriate sub-directories for languages you want to support (I.e., "/en-us"). Then put the same files in both places with different language content. They can use the same layouts, so the only thing that needs to change is the content.
* Create one set of input files but use custom pipelines to generate two sets of output files from them, using some sort of mechanism for substituting the alternate languages. For example, you could put a set of localized strings directly in the configuration file and then use Razor to include the correct one depending on which pipeline you're in.

If you do figure out a good way to do this, please blog about it! You're not the first person to ask - it's just not high enough on my own todo list to spend much time coming up with guidance or features to support it.

**Comment by daveaglick** [comment]
I have a localization strategy now, closing this in favor of #796
