### ISSUE TITLE
Add a pagination module

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#60]
User specifies items per page and then module groups documents and runs the groups through child modules, aggregating all result documents from all groups when complete. Set module metadata (#59) for page size, current page, number of pages, and if there's a next page.

**Comment by dodyg** [comment]
This is awesome. Right now I have to resort to Skip() and Take() to generate blog archive http://siwawi.demoday.us/blogs/desert-dwellers/  (temporary url)

**Comment by daveaglick** [comment]
I have an initial Paginate module prototype, but I'm hitting some mental roadblocks trying to actually make it useful. The description above says that we'll group the documents into pages, set some sort of module-level metadata, and then run each group through a series of modules. This is similar to how the Branch module works (just with multiple passes).

The problem is that this flow doesn't make a lot of sense for the use cases we would want to use Paginate for. Take an example of 7 blog posts with a paged archive of 3 posts per page (so 3 pages total). Once we've grouped the 7 input documents into 3 groups, we then send the first group of 3 documents as the input to the first child module of Paginate. Then what? If I call ReadFiles to read the archive page template, I'll end up with three copies of it since I had three inputs. Even if I could get one copy of the template, what would the template code look like to generate the paged listing inside the template? Where are the documents for each page stored that I can get to them (and only the ones for the current page) from the template?

What I may try next is to have the Paginate module output a single empty document for each page. This document would contain the metadata that was previously being put into the module-level metadata as well as a metadata value with a sequence of all the documents in the current page. Then a ReadFiles call could read the archive template and use the metadata in the document to generate the current page. This new concept may also eliminate the whole need for module-level metadata (which would be good because it's kind of confusing). The result of Paginate would be the aggregate result documents from the child modules (the input documents would get lost, so you'd need to use Paginate in a new pipeline or use something like the Concat module with a new `KeepInputs()` setting).
