### ISSUE TITLE
During suggested deploy of Wyam 1.1.0, Wyam.exe fails to install blog theme

### ISSUE THREAD

**Issue by aldosa** [statiqdev/Statiq#600]
Following the instructions in Wyam's home page, the program setup fails. The error is is repeatable and related to the recipe "Blog" not being found at Wyam.Configuration.Configurator.ApplyRecipe(). It was suggested that this may be due to file Wyam.Blog.dll being missing from the installation packages. Did not find evidence of this file anywhere in my C:\Users\YourProfile\\.nuget\packages folder.
The verbose trace is attached: [trace.txt](https://github.com/Wyamio/Wyam/files/1595484/trace.txt)

NB. Looked at a couple of Wyam packages on NuGet. Wyam.1.1.0 installs the same files as the zip distribution in the  Projects\WyamTest\packages. The file Wyam.Blog.dll is likewise missing. Since no references are added to the project, I'd suggest adding a mb file to the root of the project expalining basic usage. Similar suggestion for package Wyam.Blog.CleanBlog package.

**Comment by aldosa** [comment]
Issue fixed by adding -u flag to Wyam.exe command line. Suggested modify instructions at Wyam.exe#Usage.

**Comment by daveaglick** [comment]
This issue is also related to #587 - if everything is working correctly, the -u flag shouldn’t even be needed for recipe usage.

**Comment by daveaglick** [comment]
Whops - added the comment to the wrong issue :smile:
