### ISSUE TITLE
Support authors in Blog Recipes

### ISSUE THREAD

**Issue by juchom** [statiqdev/Statiq#615]
I'am wondering if it is possible to add to the BlogKeys.cs an Author field?

This would allow to sign a blog post!

**Comment by Klepeto** [comment]
It is possible to add Author in front-matter like this: https://raw.githubusercontent.com/cake-build/website/develop/input/blog/2018-01-17-cake-v0.25.0-released.md (source code of blog post: https://cakebuild.net/blog/2018/01/cake-v0.25.0-released)

**Comment by juchom** [comment]
Actually, we have direct access to Title, Comment, Tags.
We can browse the website per tag.

It would be nice to have direct access to Author(s) and browse per Author.

**Comment by juchom** [comment]
I think what I need is bit more complicated and involves a bit more developments.

Actually Author is a new content type.
I would like to have a bio for each authors and being able to list is blog posts.

ie: I have a blog post signed by me, if I click on my name it will link to a page with my bio and my latest posts.

I think this is not an issue at all and this can be closed.

I'm learning Wyam at the moment, so do you have any advice or baby steps on how to do it?

Thanks a lot!

**Comment by daveaglick** [comment]
What you want to do is a cool idea, but I agree it’s probably not something that should be included in the recipe by default. Wyam was designed specifically for cases like this where you want to customize and extend things. Here’s how I’d go about doing it:
* Add `Author` front matter to each post - that’ll automatically get added to the metadata for each post document
* Add Markdown files for each author that contains their bio, etc.
* Create a new pipeline that:
  * Reads all the author Markdown files into an author document (one per author)
  * Renders the Markdown
  * Moves the Markdown content to metadata in the author document
  * Gets documents from the “BlogPosts” pipeline for the corresponding author and moves those to metadata in the author document
  * Loads a `.cshtml` template and renders it - the template would place the Markdown we moved to metadata into the page and also render a list of the blog posts for that author we added to metadata
  * Outputs each rendered author document
* Override the `_PostHeader.cshtml` file from the theme to include the author and a link to the author page

**Comment by juchom** [comment]
Thanks for your reply,

Here is what I have so far...

```csharp
#recipe Blog

using System.Globalization;
using System.Text;

public static class Helpers
{
    public static string NormalizeString(this string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return text;

        text = text.Normalize(NormalizationForm.FormD);
        var chars = text.Where(c => CharUnicodeInfo.GetUnicodeCategory(c) != UnicodeCategory.NonSpacingMark).ToArray();
        return new string(chars).Normalize(NormalizationForm.FormC).ToLower().Replace(' ', '-').Replace("#", "-sharp");
    }
}

CultureInfo.DefaultThreadCurrentCulture = CultureInfo.CreateSpecificCulture("fr-FR");

string AuthorsPath = nameof(AuthorsPath);

Settings[Keys.Host] = "mysite.com";
Settings[Keys.LinksUseHttps] = true;
Settings[BlogKeys.PostsPath] = new DirectoryPath("blog");
Settings[BlogKeys.IndexPaging] = true;
Settings[AuthorsPath] = new DirectoryPath("authors");

Pipelines.Remove(Blog.Pages);

Pipelines.InsertBefore(Blog.BlogPosts,
    (IPipeline)new Wyam.Web.Pipelines.Pages(
        nameof(Blog.Pages),
        new Wyam.Web.Pipelines.PagesSettings
        {
            IgnorePaths = ctx =>
                new[] { ctx.DirectoryPath(BlogKeys.PostsPath).FullPath, ctx.DirectoryPath(AuthorsPath).FullPath }
                .Concat(ctx.List(BlogKeys.IgnoreFolders, Array.Empty<string>())),
            MarkdownConfiguration = ctx => ctx.String(BlogKeys.MarkdownConfiguration),
            MarkdownExtensionTypes = ctx => ctx.List<Type>(BlogKeys.MarkdownExtensionTypes),
            ProcessIncludes = (doc, ctx) => doc.Bool(BlogKeys.ProcessIncludes)
        }));

Pipelines[Blog.BlogPosts].Append(
  Meta(Keys.RelativeFilePath, (doc, ctx) =>
  {
    DateTime published = doc.Get<DateTime>(BlogKeys.Published);
    string fileName = doc.Bool("FrontMatterPublished")
            ? doc.FilePath(Keys.SourceFileName).ChangeExtension("html").FullPath
            : doc.FilePath(Keys.SourceFileName).ChangeExtension("html").FullPath.Substring(11);
    fileName = fileName.NormalizeString();
    return ctx.Bool(BlogKeys.IncludeDateInPostPath)
            ? $"{ctx.DirectoryPath(BlogKeys.PostsPath).FullPath}/{published:yyyy}/{published:MM}/{fileName}"
            : $"{ctx.DirectoryPath(BlogKeys.PostsPath).FullPath}/{fileName}";
    }));

Pipelines.InsertAfter("BlogPosts", "Authors",
    ReadFiles(@"authors\*.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Meta("Biography", @doc.Content));

Pipelines.Remove(Blog.Tags);

Pipelines.InsertAfter("Authors",
    (IPipeline)new Wyam.Web.Pipelines.Archive(
        nameof(Blog.Tags),
        new Wyam.Web.Pipelines.ArchiveSettings
        {
            Pipelines = new string[] { Blog.BlogPosts },
            TemplateFile = ctx => "_Tag.cshtml",
            Layout = "/_Layout.cshtml",
            Group = (doc, ctx) => doc.List<string>(BlogKeys.Tags),
            CaseInsensitiveGroupComparer = ctx => ctx.Bool(BlogKeys.CaseInsensitiveTags),
            PageSize = ctx => ctx.Get(BlogKeys.TagPageSize, int.MaxValue),
            Title = (doc, ctx) => doc.String(Keys.GroupKey),
            RelativePath = (doc, ctx) => $"tags/{(doc.String(Keys.GroupKey)).NormalizeString()}.html",
            GroupDocumentsMetadataKey = BlogKeys.Posts,
            GroupKeyMetadataKey = BlogKeys.Tag
        }));

Pipelines.InsertAfter(nameof(Blog.Tags),
    (IPipeline)new Wyam.Web.Pipelines.Archive(
        "AuthorsArticles",
        new Wyam.Web.Pipelines.ArchiveSettings
        {
            Pipelines = new string[] { Blog.BlogPosts },
            TemplateFile = ctx => "_Author.cshtml",
            Layout = "/_Layout.cshtml",
            Group = (doc, ctx) => doc.String("Author"),
            CaseInsensitiveGroupComparer = ctx => ctx.Bool(BlogKeys.CaseInsensitiveTags),
            PageSize = ctx => ctx.Get(BlogKeys.IndexPageSize, int.MaxValue),
            Title = (doc, ctx) => doc.String(Keys.GroupKey),
            RelativePath = (doc, ctx) => $"authors/{(doc.String(Keys.GroupKey)).NormalizeString()}-articles.html",
            GroupDocumentsMetadataKey = BlogKeys.Posts,
            GroupKeyMetadataKey = "Author"
        }));

Pipelines.InsertAfter("AuthorsArticles", "AuthorsIndex",
    If(
    ctx => ctx.Documents["Authors"].Any(),
    ReadFiles("_Authors.cshtml"),
    FrontMatter(Yaml()),
    Razor().IgnorePrefix(null).WithLayout("_Layout.cshtml"),
    WriteFiles((doc, ctx) => "authors/index.html"))
    .WithoutUnmatchedDocuments());
```

Here is how look one of my post
```
Title: Sample Blog Post
Tags:
  - C#
Author: John Doe
---

Nice post to come...
```

Here is how look one of my Author file
```
Name: John Doe

---
A nice biography...
```

I'm missing this part,

> Gets documents from the “BlogPosts” pipeline for the corresponding author and moves those to metadata in the author document

I'll suppose it works like tags but I don't see how to do it...

**UPDATE 1:** Update Pages Pipeline to ignore authors directory
**UPDATE 2:** Add AuthorsIndex pipeline
**UDPATE 3:** Add post and author sample, and show how to link them
**UPDATE 4:** Final update, this config add support for Authors index and a page with all post per author

**Comment by juchom** [comment]
Closing the issue, I'll try to cleanup everything and give some documentation for it.

**Comment by daveaglick** [comment]
Glad you got it figured out! Some sort of write-up would be awesome in case someone else wants to do something similar. You could add it to the issue here, blog about it, and/or we could add it as a "Tips" section or something to the official docs [here](https://wyam.io/recipes/blog/).

**Comment by juchom** [comment]
Ok, I finally fixed my last error! 

I'm going to update Wyam website, it's the best place for everyone I think.
Do you want a Tips menu with a dropdown in the left column like Themes.

And a custom document explaining what I've done?

**Comment by atiq-cs** [comment]
@juchom do you mind sharing the link where you updated the doc? Thank you :)
