### ISSUE TITLE
Docs recipe not working any more in 1.1.0

### ISSUE THREAD

**Issue by devlead** [statiqdev/Statiq#616]
Just recently pushed a new blog post and generation failed with `Method not found: 'Wyam.Core.Modules.Control.Concat` (See https://ci.appveyor.com/project/litjson/litjson-github-io/build/1.0.18 )

I've pinned Wyam & Cake.Wyam versions, but how do I pin the recipe? Or make sure updates to the recipe doesn't break the build on CI.,

Updating to 1.2.0 sorted the issue, but still perhaps there needs to be some logic to prevent loading unsupported recipes/recipes with breaking changes.

**Comment by daveaglick** [comment]
Already ahead of you :smile:

This (hopefully) shouldn't happen again. As of 1.2.0 Wyam now "locks in" the recipe version to match that of the currently running release. If the corresponding recipe version isn't found, it should be downloaded. See #587.

**Comment by devlead** [comment]
@daveaglick excellent! 👍
