### ISSUE TITLE
Add support for converting image formats in the Image module

### ISSUE THREAD

**Issue by DNF-SaS** [statiqdev/Statiq#623]
Hi,

i hope this is the right place to ask this question.
My website is using the Image-Module to resize it's input images - works great so far.
But some input-images are .png-Files - **is it possible to convert them to .jpg using the pipeline**?

Thanks for any hints!
Sascha

**Comment by daveaglick** [comment]
At this time the Image module can only output images in the same format as the input files. Being able to convert formats would certainly be a nice enhancement, though I probably won't get to it personally anytime soon. I'll update this issue to reflect a feature request and mark it as up for grabs.

**Comment by daveaglick** [comment]
This is now resolved with the image rewrite in #671 and will go out with the next release
