### ISSUE TITLE
Replace module, contentFinder's access to the current document?

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#625]
Is there any way to gain access to the current document and its metadata within `contentFinder` callback in Replace module?

Performing `<a href=''></>` and `<img />` replacement manipulations. Unfortunately, in both cases, we store additional data in the folder relative to the current documents. Hence, to make the right replacement, `contentFinder` should know on which document it operates so that it would be able to lookup additional data about the current document, location and other info. 

Is that even possible?

**Comment by daveaglick** [comment]
There is now :)

Added a Replace module constructor overload that takes a `Func<Match, IDocument, object>` content finder.
