### ISSUE TITLE
Can't set --ignore-config-hash in Cake.Wyam's WyamSettings

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#628]
Using Cake.Wyam task, trying to run Wyam in validation config mode with VerifyConfig = true before running actual Wyam generation.

Hitting the following error:

```
error: The directive --verify-config can only be specified if --ignore-config-hash is also specified.
```

Setting look as following:
```cs
settings.VerifyConfig = true;
settings.NoCache = true;
```

or
```cs
settings.VerifyConfig = true;
```

By the look in the code, WyamRunner.GetArguments() does not have this `ignore-config-hash` property promoted.
https://github.com/Wyamio/Wyam/blob/master/src/clients/Cake.Wyam/WyamRunner.cs#L64

**Comment by daveaglick** [comment]
Good catch - just needs to be added to the Cake `WyamSettings`. I’ll mark this as a bug so I get it resolved for the next release.

**Comment by daveaglick** [comment]
> I’ll mark this as a bug so I get it resolved for the next release.

Umm...about that 🤦‍♂️

This has now been added and will ship with the next release. You can either set `IgnoreConfigHash` directly or set `VerifyConfig` (which will implicitly output `--ignore-config-hash`).
