### ISSUE TITLE
Velocity Theme: Text does not wrap correctly in certain screen resolutions

### ISSUE THREAD

**Issue by onnotasler** [statiqdev/Statiq#634]
I am trying to create a website based on the Velocity theme for the booksite recipe. If I resize the browser within a certain scope, the text simply gets "cut off" and I need to scroll sideways. It works fine in bigger or smaller sizes, where it resizes as expected, but between a page width of approximately 750 px and 1000 px, it looks extremely strange. This is especially obvious on the start page, where it cuts of the description text, whereas it only cuts off the right side bars on other pages.

**Comment by daveaglick** [comment]
Thanks - I’ll take a closer look. Velocity and the book recipe isn’t widely used yet so there are probably a few rough edges like this (as you seem to be finding :smile:).

**Comment by daveaglick** [comment]
As much as I hate to, I'm going to close this as "won't fix". The BookSite recipe is going to be removed in the next version in preparation for combining all the recipes into a single omnibus static site generator application (see #668). Blog and Docs will stick around until vNext is ready, but there just isn't value in spending time supporting BookSite when it's usage is an order of magnitude less than the other two recipes.
