### ISSUE TITLE
Velocity: Make theme ready for automatic hyphenation

### ISSUE THREAD

**Issue by onnotasler** [statiqdev/Statiq#635]
HTML has a function to allow browsers to automatically put hyphens into long words to improve text flow. I propose to add this ability to the Velocity theme (and probably other themes as well). This requires two changes in Velocity:

1) main.css: Needs an additional entry "body { -webkit-text-size-adjust: none; -webkit-hyphens: auto; -ms-hyphens: auto; hyphens: auto;}" to activate hyphens.
2) _Master.cshtml: The /html/ tag needs to be assigned a language. This can be done manually, but it is probably also possible to automatically assign the value from the "CultureInfo" in the config.wyam (as far as I understand the documentation, this should default to /html lang="en-US"/ if CultureInfo is not defined in the configuration file).

**Comment by daveaglick** [comment]
This would need to be a theme-by-theme decision and change. Hyphenation may not look good for all themes. I’m fine adding it to Velocity though. Go ahead and send a PR if you like, or I can try to get it in for the next release.

**Comment by onnotasler** [comment]
I cannot program at all, so it would be great if you could include it.

**Comment by onnotasler** [comment]
I thought about this a little more: Would it be possible to include an option "hyphenation: default / on / off" in the config?

After all, it does not only depend on the theme whether hyphenation is helpful, but also on the topic one writes about (scientific texts have longer words than casual texts, and the longer the word, the more ragged the look), your audience (which kind of screen they usually use) and the language (for those with compound words, hyphenation is almost necessary, for those without, it is less crucial).

**Comment by daveaglick** [comment]
As much as I hate to, I'm going to close this as "won't fix". The BookSite recipe is going to be removed in the next version in preparation for combining all the recipes into a single omnibus static site generator application (see #668). Blog and Docs will stick around until vNext is ready, but there just isn't value in spending time supporting BookSite when it's usage is an order of magnitude less than the other two recipes.
