### ISSUE TITLE
Velocity: Define names for parts in config.wyam

### ISSUE THREAD

**Issue by onnotasler** [statiqdev/Statiq#637]
At the moment, the booksite recipe requires manually editing the cshtml pages to rename the titles of different parts, like "blog", "chapters", or "introduction". In some cases (blog and chapters) I did not find yet all entries that I have to change to properly rename them.

I propose to instead define those names in the config.wyam, replacing the actual entries by variable placeholders. this would make the theme more versatile (as one could for example change easily rename the Chapters to Essays for a series of essays or Steps for a tutorial) as well as easier to translate into other languages.

**Comment by daveaglick** [comment]
That sounds totally reasonable. Just so I’m clear - you’re talking about the headers for different sections of the pages?

**Comment by onnotasler** [comment]
I assume so, I am not sure what they are called. They are defined in the <div class="title"></div> and title: of the cshtml files, and probably in some other places as well (because, as I said, I have not yet found all of them).

**Comment by daveaglick** [comment]
As much as I hate to, I'm going to close this as "won't fix". The BookSite recipe is going to be removed in the next version in preparation for combining all the recipes into a single omnibus static site generator application (see #668). Blog and Docs will stick around until vNext is ready, but there just isn't value in spending time supporting BookSite when it's usage is an order of magnitude less than the other two recipes.
