### ISSUE TITLE
Velocity: Publishing date on blog posts not correctly displayed in German

### ISSUE THREAD

**Issue by onnotasler** [statiqdev/Statiq#639]
If the Culture is set to de-DE in the config.wyam, there is a small mistake when displaying the date.

Example of output:
09 Februar 2016

How the output should correctly look like:
9. Februar 2016

That is, a trailing zero should be ommited and the date should be followed by a point to indicate it is the ninth of february 2016 and not, say, the 9th installment / article / version that happens just to be published in february 2016.

The Get-Date command in powershell displays the date correctly if run with these parameters:
`Get-Date -Year 2016 -Month 02 -Day 09 -UFormat "%e. %B %Y"`

**Comment by daveaglick** [comment]
As much as I hate to, I'm going to close this as "won't fix". The BookSite recipe is going to be removed in the next version in preparation for combining all the recipes into a single omnibus static site generator application (see #668). Blog and Docs will stick around until vNext is ready, but there just isn't value in spending time supporting BookSite when it's usage is an order of magnitude less than the other two recipes.
