### ISSUE TITLE
Build Cake.Wyam against Cake 0.26.0

### ISSUE THREAD

**Issue by AdmiringWorm** [statiqdev/Statiq#649]
To support Cake >= 0.26.0 the Cake.Wyam addin needs to built against Cake 0.26.0.

**Comment by daveaglick** [comment]
👍 will definitely update for the next release

**Comment by AdmiringWorm** [comment]
Just a note though, it will make Cake.Wyam incompatible with earlier versions of Cake.
Haven't found a way to keep addins compatible yet (don't think it's possible either 😢)

**Comment by daveaglick** [comment]
I’m fine with that - generally speaking the older version of the Cake addin is still compatible with newer versions of Wyam since it just forks out and the CLI arguments don’t change very often.
