### ISSUE TITLE
Type link with generic types in the docs recipe

### ISSUE THREAD

**Issue by k94ll13nn3** [statiqdev/Statiq#674]
I have a couple of remarks regarding the "autolink" feature in the docs recipe (the links in the documentation pages):
- When using a known type inside a generic type (like `IEnumerable<Foo>` when `Foo` is a type from the API), no link is created for the type (`Foo`).
- When trying to link a generic type from the API, it does not work (`Foo<T>` does not link to the `Foo<T>` API page). After a quick look at the code, the text is encoded before trying to find a match, and the `<` and `>` are not matched since they are replaced: https://github.com/Wyamio/Wyam/blob/9673b57967ebbbf1a7388105551e7d409be262d8/src/extensions/Wyam.Html/AutoLink.cs#L182
So I changed the `Api` pipeline locally, by changing `name` to `WebUtility.HtmlEncode(name)` when adding a new type link in this line: https://github.com/Wyamio/Wyam/blob/9673b57967ebbbf1a7388105551e7d409be262d8/src/recipes/Wyam.Docs/Pipelines/Api.cs#L67
I got it almost working, but there is some (expected I think) cases where it does not work:
  - If I use a generic parameter different from the one in the code, it does not match: `Foo<U>` does not links to the `Foo<T>` API page
  - `Foo<T,U>` won't link to `Foo<T, U>` (no space before `U` in the first one)

Is it possible to modify the `Api` pipeline in `config.wyam` in order to have this modification in my site or is a code modification necessary ?

**Comment by daveaglick** [comment]
> Is it possible to modify the Api pipeline in config.wyam in order to have this modification in my site or is a code modification necessary

Yes, you can modify any pipelines you want. It introduces a little risk though because you have to basically replace the pipeline (you can actually replace individual modules, but that gets really complicated, really fast). If it changes in a later version, your customized version will be out of date.

```
int apiIndex = Pipelines.IndexOf(Docs.Api);
Pipelines.Remove(Docs.Api);
Pipelines.Insert(apiIndex, Docs.Api,
    new If(...)
);
```

(There's an open issue #591 to add a `.Replace()` method so you don't have to do the get index. remove, insert dance above)

That should work in the near-term for you. However, I'd like to get this change in directly. What to submit a PR? If not, no problem, I can just copy the code changes in.

**Comment by k94ll13nn3** [comment]
Yes, I can do a PR.

**Comment by daveaglick** [comment]
I'll go ahead and close out this issue since the change has been merged. Let me know if you need any more help on this and we can re-open it.

**Comment by k94ll13nn3** [comment]
I wanted to come back to my comment:
> When using a known type inside a generic type (like IEnumerable<Foo> when Foo is a type from the API), no link is created for the type (Foo).

I managed to get this working by modifying the `AutoLink` class as you can see in this screenshot:
![generics](https://user-images.githubusercontent.com/10998921/41053366-a0349478-69bb-11e8-9a59-45cd96af3262.png)

I am not 100% happy with my modification, but it's working and does not seem to introduces bugs (I need to add some tests). I can submit a PR if you like for this too.
