### ISSUE TITLE
Question: Categorizing API documentation

### ISSUE THREAD

**Issue by RLittlesII** [statiqdev/Statiq#690]
In ReactiveUI we have several API's that are specific to certain platforms.  Does Wyam provide a way when generating the API documentation to categorize the API's to relevancy?

Example would be certain API's are relevant only in iOS or Android.

See https://github.com/reactiveui/website/issues/130 for further details

**Comment by daveaglick** [comment]
I'm going to answer this over in the ReactiveUI thread since it's more about how to add functionality to that specific site than Wyam itself (which doesn't know anything about an API intended for one platform or another).
