### ISSUE TITLE
Cache output documents from pipeline phases when possible

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#694]
One of the biggest pain points of working in the docs recipe is the rebuild speed when watching/previewing and working on content or blog posts. Because the API rebuilds for every change, you have to wait to get the live preview.

This could be greatly improved by allowing pipelines to opt-out of the rebuild process. I.e., the pipelines responsible for generating API docs wouldn't ever run again. This presents a challenge in that the output folder is typically cleared on rebuilds - how to make sure pipelines that opt-out don't have their output removed? My initial thought is that if a pipeline opts-out, it's not totally invisible, instead it'll essentially short-circuit the modules and cache the output documents from the first execution and that'll be the result on every following execution. There's still the issue of writing those documents to disk though. Perhaps the idea of phased pipelines in #695 will help here and is a prerequisite - opting-out eliminates all but the write phase, which still gets executed even on rebuilds and will result in writing the cached documents from the previous phase.

Once this feature is figured out, make the API oriented pipelines in the docs recipe opt-out. I'm okay saying that if you want to see changes to source code or XML comments you have to re-run Wyam instead of relying on watch and rebuild.

**Comment by LokiMidgard** [comment]
While I'm not opposed this idea, i think #346 would be a more flexible approach.

I only use wyam for for one website, so I don't see all the use cases, especially not the recepts. But for my project it would depend on the files I'm changing, If I need to rerun a module. And there is almoast no module I could skip regardless wich file changes.

E.g. I'm currently working on a module that takes xml templates and xml data structure and generates pdf files from this. Currently this takes 30 secconds+. It would be a huge improvement, if I'm working on some text or layout of the website, to not always regenerate those pdfs. However if I'm changing the data or template files used to generate those pdf's I alsoe need to gegenerate those.

**Comment by daveaglick** [comment]
@LokiMidgard You raise some excellent points, here and in #346. Thought about this a lot more and the problem for both approaches really comes down to these points:
* A module has a set of input documents
* A module can also make use of documents from other pipelines
* If either the input documents are different or _any_ of the documents it uses from other pipelines are different, the output could also be different
* The output folder is totally cleared on rebuilds (I don't really want to revisit this behavior - anything else would be really tricky to get right)
* The result documents at the end of a pipeline need to be available to other pipelines, regardless of whether modules were actually run or not

So the question is: how to prevent work that doesn't need to be done because it's still valid from the last generation (whether a previous invocation or the current invocation if doing a rebuild) while still ensuring the correct results both get written to output and are available for other pipelines that rely on them?

Here's a refinement of this issue that uses some ideas from #346 like hashing:
* If we rely on pipelines defining the other pipelines they depend on, which is already on the board in #189, then we'll know both the input documents from the previous phase and the other documents that contribute to the output for that pipeline
  * Has to be declared - we can't just rely on looking at which pipelines they got documents from previously because that logic might be behind conditionals - I.e., get documents from pipeline A if foo, but pipeline B if bar
  * However, if we do capture the previous behavior by hooking into execution context methods that get documents from other pipelines, that's a good initial guess - so use that _combined_ with any declarations so we can turn on this feature automatically and it'll just work for most builds
* Each document could expose a `GetHash()` or similar that would calculate a hash for the document (and then cache it for later calls)
* The `Read` phase always executes - it's lightweight since it's basically getting a stream pointer
* For a given `Process` or `Render` phase, if the hashes of all input documents _and_ all documents from pipelines this one depends on match the previous generation cycle we can cache and re-output the output documents for that phase from the previous generation cycle
  * This only works for regeneration - initial generation won't have any cached output documents so we'll also need something like #346 to handle caching from generation to generation
* The `Write` phase always executes to ensure the cached documents still make it to output

Activating this behavior relies on two things:
* Pipelines defining the other pipelines they get documents from (both explicitly and by watching what happens during the initial generation)
* The `Write` phase containing the modules that write to disk

If the `Write` phase contains modules, we can assume those are the ones that write to disk so that pipeline should automatically opt-in to this caching behavior unless explicitly opted-out.

**Comment by daveaglick** [comment]
Problem: The approach above assumes only changes to documents matter, either from input documents and/or other pipelines. There's an assumption that as long as the documents a pipeline depends on don't change then the output doesn't change. That's not true in a lot of cases. For example, when a `_Layout.cshtml` file changes, that's not a document (it's read directly by Razor) so we'd trigger the caching behavior here instead of regenerating the files that depend on that layout.

After a little more thought, perhaps the best way to deal with the above problem is to look at the file(s) that changed which triggered the regen. If all of them are represented by the set of input documents + dependency documents for a given pipeline (by looking at their `IDocument.Source` property) then we can assume nothing out of band changed and use the cached results. Otherwise, if any of the watched files are not represented by a document, then act as though the hashes changed and rerun the pipeline.

**Comment by daveaglick** [comment]
Implemented in vnext
