### ISSUE TITLE
Create a Sass CSS module

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#7]
Should read Sass CSS content and transform it to CSS content. Not sure if there's a suitable library available (if not, this will have to wait - not building a new Sass parser).

**Comment by daveaglick** [comment]
Now that Bootstrap 4 is going Sass, this is probably a bit more important. Two libraries worth looking at:
- https://github.com/darrenkopp/libsass-net
- https://github.com/TBAPI-0KA/NSass

Neither is fully-managed and both just wrap the libsass C++ library.

**Comment by WestDiscGolf** [comment]
Was just thinking this myself, thought I'd have a little look around and is already listed as a module feature :-) Struggling to find a managed sass library though to use so may have to go the wrapper route for now. Unfortunately I don't know enough about sass or have the time to write a managed code sass parser at the moment either :-( Will keep a look out ...

**Comment by WestDiscGolf** [comment]
Using - https://github.com/paulcbetts/SassAndCoffee - seems like potentially a way to go ...

**Comment by daveaglick** [comment]
Another option: https://github.com/xoofx/SharpScss

**Comment by leemw1977** [comment]
When I saw that less support was in there, the first thing I thought was maybe some sass-y support would be nice for those that like to use it (boot-strap going that way makes for another big plus one I guess as Dave pointed out).

I know VS supports this, but I assume they will have their own parser - I'm off to do some digging in the first instance.

**Comment by daveaglick** [comment]
Awesome - this will become increasingly important since Bootstrap 4 isn't going to ship with any kind of Less support.

One more note: try aiming for .Net Core support - Wyam is moving to Core soon and the more stuff that's compatible to begin with, the less we'll have to do down the road.

**Comment by leemw1977** [comment]
Ok, so current thoughts: I was planning on targeting NETStandard 1.6 for now so that should be .net frameworks supported and dotnet core as we require. 

Now, I've yet to fully investigate the SharpScss library linked above so will do that next.  Putting that to one side what I've found so far is we may need to create a NETStandard 1.6 compatible wrapper for libsass - the biggest issue with using something like libsass-net - at least as I see it is going to be how we distribute Wyam with it, we don't want to be installing VC redist - at least not from what I can tell.

I'll post some more when I've done some more digging - so far enjoying the ride 👍

**Comment by daveaglick** [comment]
Awesome! You didn't pick an easy one for your first module :smile:. The lack of a pure .NET Sass port is why I keep putting this one off.

**Comment by leemw1977** [comment]
I like a challenge :) reminds me why I love coding as you know how it can be in the day job , I understand why its like it is but sometimes ya know :D

**Comment by daveaglick** [comment]
I'm going to go ahead and finally start tackling this using https://github.com/xoofx/SharpScss. I'd like to get the module out ASAP since more and more themes are using Sass and Less seems to be dying out. Seems like we should have Sass support before 1.0.

**Comment by daveaglick** [comment]
Done! Will go out with next release.
