### ISSUE TITLE
C# source documentation module

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#70]
This has always been in the plans from day 1, and the time has finally come to take a look. Initial support should be for C# powered by Roslyn (with VB.NET coming soon after). Inspiration should come from Doxygen: http://www.stack.nl/~dimitri/doxygen/manual/arch.html. Also note this module (probably) isn't about annotating source code wholesale and generating reference source pages like source.roslyn.io - that can/will be handled in a different module. This is more about API documentation and the potential for mixing API documentation with other content.

Current thinking is to ingest source files (as provided in the pipeline with a standard ReadFiles or other I/O module) and output documents with metadata corresponding to the traits of the source items. Ideally, this metadata should be general enough that we can standardize on standard keys for if/when support for additional languages is added (C/C++, Java, JavaScript, etc.). Things like:
- Source File(s) (need to account for partials spread across multiple files - though if generating a document per member, then we'd be okay since a specific member can't span files, at least not in .NET)
- Namespace
- Class/Struct/Enum/Etc Name
- Base Class(s)
- Interface(s)
- Generics (or maybe just store a string with the entire class/member definition - do we really need to break out generics information?)
- Member Name
- Member Type
- Scope
- Source Code (maybe this becomes the content of the document?)

Still need to decide what level the output documents should be at: file, class, member, etc. Perhaps output documents for all levels and each document only has metadata as appropriate for the represented type of thing. If outputting documents per-member, we can reduce memory use by doing multiple clones, one for the data in common like class name, base classes(s), etc. and then another to add metadata for member-specific data like member name, scope, and source code.

Have to be careful to limit scope here - like all modules, this should do a single job like interpreting the source code information and rely on other modules for formatting, templating, and output. We should eventually rely on recipes (#1) for no-configure generation of API documentation with included templates, etc.

There should be at least two phases internally:
- First phase reads all the input documents, attempts to generate Roslyn syntax trees, gets relevant syntax nodes, and stores them in lookup tables. Not sure if we'll need a semantic model or if text lookups with identifiers like full names will suffice. Might have to use a semantic model in order to resolve things like `using Foo = Bar`. Doxygen does this process here: http://sourceforge.net/p/doxygen/code/HEAD/tree/trunk/src/doxygen.cpp#l10583 (not that it should be ported, but might have some inspiration). 
- Second phase iterates the lookup tables and generates the relevant output documents.

**Comment by FlorianRappl** [comment]
I only want to provide some (possibly orthogonal) thoughts here. What I planned for the documentation system for AngleSharp is to be able to include snippets of source code, which are either
1. Checked-in in the unit tests (of some repo; in this case of AngleSharp or some related project, e.g., the samples)
2. Just raw snippets, but fully compilable under certain circumstances (such as pasted in a suitable `Main` function, a class method, ..., with correct .NET (e.g., 4.5) and library (e.g., AngleSharp) dependencies)

While the first case only needs parameters such as URI, startline, endline, ... the second one requires a full .NET compiler with more parameters (framework, dependencies, ...). But both are interesting scenarios. Of course the first one is much easier to implement.

The idea is to have examples in the documentation, which are always kept up-to-date (thus compilable and runable, i.e. they produce the expected (documented) result) by testing them with the code (case 1) or when generating the documentation (case 2).

I know that this is not exactly source documentation, but I think it will also be more generic (case 1) and general usable (consider a blog where you post code examples, from anywhere - maybe even checked for correctness (case 2)).

As I said its more or less orthogonal to your proposal, but maybe something like case 1 would be a great addition as well.

**Comment by daveaglick** [comment]
Very interesting. First reaction is that this is almost the inverse of the documentation module (especially the second scenario): instead of reading source files and generating markup from the embedded program objects, we want to read markup and parse/compile the embedded source.

You're right in that I think the biggest challenge would be getting the context correct (references, libraries, packages, other sources, etc.). For the first scenario of embedded source snippets in markup or other non-source files, making sure the appropriate artifacts to which the snippet refers would be the challenge. In the second scenario where we have a unit test project, we could use the Roslyn Workspaces API to get all that info from the project file, but there might be difficulty in managing the test lifecycle for correct execution (setup, teardown, etc.) This is different for each testing framework and we obviously wouldn't want to get into the "test runner" business for this.

That said, I think all those challenges could be overcome. Roslyn certainly provides the horsepower for making this happen on a technical level. And I love the idea of a stronger connection to the project and/or verification of code snippets in docs, blogs, etc.

**Comment by dodyg** [comment]
When this is completed, it will change the .NET programming world. We can finally say goodbye to  ugly source code documentation output that is impossible to figure out and tweak.

**Comment by FlorianRappl** [comment]
Agreed!

**Comment by daveaglick** [comment]
Note to self: add ability to use Roslyn Workspaces APIs to load projects or solutions in addition to pointing at a folder tree with source files.

**Comment by daveaglick** [comment]
This one should be complete! It'll come out with the next release, though at the moment it takes a little bit of work to use. The module currently analyzes source code and creates one output document per symbol with the analysis data stored as metadata. Then downstream modules can use the symbol documents to generate whatever kind of code-based content they need.

This module will really become important with the development of a documentation recipe to come in the release after this one. At that point it will serve as the basis for one-command documentation generation.
