### ISSUE TITLE
Contentful + Wyam error

### ISSUE THREAD

**Issue by rsantosdev** [statiqdev/Statiq#704]
I also posted on `Contentful.Wyam` GH, just double posting here, since people may have more experience:

I'm tring to follow the tutorial to fetch content from my Contentful account into Wyam, but I get the following error:

![image](https://user-images.githubusercontent.com/863056/44548220-de33ca80-a6f3-11e8-9140-a1c9d845fe71.png)

my config file:

```
// Preprocessor directives
#n Wyam.Razor
#n Wyam.Markdown
#n -p Contentful.Wyam
#n Wyam.Html
#n Wyam.Less

// Customize your settings and add new ones here
Settings[Keys.Host] = "host.com";

// Body code
Pipelines.Add("Products",
    Contentful("meyKey", "spaceId")
        .WithContentField("body").WithContentType("contentId")
);
```

**Comment by daveaglick** [comment]
Probably a mismatch between the supported version of Wyam in the Contentful extension and the current version of Wyam. I'll take a look at submitting a PR to the Contentful extension to update it's supported Wyam version (and fix any resulting breaks).

**Comment by daveaglick** [comment]
Noticed Contentful was recently updated so this should be resolved with the most recent version. Feel free to open a new issue or request this one be reopened if not.
