### ISSUE TITLE
Add Source Code Link for all Wyam packages

### ISSUE THREAD

**Issue by MaximRouiller** [statiqdev/Statiq#705]
As described in this post:

https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html

A few of the techniques could be used. Add the following to the different `nuspec`:

```xml
<repository type="git" url="https://github.com/Wyamio/Wyam"" />
```

Except of course the Themes which seem to use CakeBuild. So they would need to have this line added: 

```csharp
var nuGetPackSettings = new NuGetPackSettings
    {
        // snipped
        Repository = new NuGetRepository {
                Type = "git",
                Url = "https://github.com/Wyamio/Wyam"
            }
        // snipped
    };
```

**Comment by LokiMidgard** [comment]
Shouldn't the reposetory Url be `https://github.com/Wyamio/Wyam.git`.

I always thought the url should point to the actual git url where you clone the repo, not the project site.

**Comment by MaximRouiller** [comment]
Doesn't matter but I can make it so.

**Comment by MaximRouiller** [comment]
@LokiMidgard updated in the PR. 

Awaiting for binaries to go out and for @daveaglick to give it his blessing.

**Comment by MaximRouiller** [comment]
The blessing has been given. The packages are live.

![image](https://user-images.githubusercontent.com/209384/44723864-2e69ae80-aa9f-11e8-98fd-241a52df5029.png)
