### ISSUE TITLE
Type link for generic type parameters in docs

### ISSUE THREAD

**Issue by k94ll13nn3** [statiqdev/Statiq#707]
Following the fixes for the generic type parameters in docs in the new version, the type parameters are not linked to the corresponding types in the generics (like what is possible with the AutoLink feature).

![bug](https://user-images.githubusercontent.com/10998921/44733484-fa66ab80-aae7-11e8-99b6-29a662bb836e.PNG)

**Wyam**: v1.5.1

**Comment by daveaglick** [comment]
👍 Good call, still making some other related improvements so I’ll add this to the list

**Comment by daveaglick** [comment]
Resolved in develop, will go out with next release
