### ISSUE TITLE
Lunr module

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#71]
Lunr is a client-side search engine: http://lunrjs.com/. It's possible to create the data store beforehand, serialize it to JSON, and then read it in at runtime. The idea here is that the module would process all the input documents and create the appropriate JSON document that represents a Lunr store as an output document. This document could then be saved and loaded into Lunr on the client. Not sure if Lunr will actually be needed to generate the Json - may be possible to reverse engineer the format and just generate it standalone. If Lunr is needed for some reason (I.e. to get the pipelines right), could look at Jurassic or Node/Edge.js.

**Comment by reliak** [comment]
Is anybody working on this? I'm about to dive in to generate a searchindex file and js-code to provide a static site search with lunr.js

**Comment by daveaglick** [comment]
Holy cow! It would be awesome if you made headway on this one.

I'm working hard on using Wyam for generating documentation sites, but searching the docs (or even just things like class names) is an area I'm missing. I would love to fill in that gap.

**Comment by daveaglick** [comment]
Resolved by #118
