### ISSUE TITLE
Define a base path

### ISSUE THREAD

**Issue by fleed** [statiqdev/Statiq#712]
Is there a way to define a base path for the generated static website?

I'd like to include the generated static files in a subpath of a web application (/blog). All generated links are absolute (/index.html, etc.).

**Comment by daveaglick** [comment]
Yep, there’s a built-in way to do that. See if this does what you need: 
https://wyam.io/docs/deployment/serving-from-a-subdirectory

**Comment by fleed** [comment]
Exactly what I needed, thank you @daveaglick
