### ISSUE TITLE
Implement themes

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#72]
The concept of themes go hand-in-hand with recipes (#1) since a given theme is probably only going to work with a given recipe (since it'll rely on the specific metadata, document layout, etc. in that recipe). That said, the main recipes (like blog, docs, etc.) should each have a set of themes.

A theme should contain one or more files that act as though they are in the `InputFolder` provided a file with the same name isn't _actually_ in the `InputFolder`. This is similar to the [Hugo theme system](https://gohugo.io/themes/customizing/). One idea on how to make this work is to introduce an extra `ThemeFolder`. Whenever files need to be found (Razor layouts, Less includes, etc.), the `InputFolder` will be searched first and then the `ThemeFolder` will be searched. This might require an extra file system abstraction.

This will impact modules because those that read from the file system like `ReadFiles` should probably also use the new abstraction and treat files in the `ThemeFolder` as if they were in the `InputFolder` too. That way, plain resources like CSS or JavaScript will be handled in the normal workflow and can be overridden by placing overrides in the `InputFolder`.

Best idea at the moment for packaging themes is to use content-only NuGet packages (just like we do for dumping resources directly in the `InputFolder`). Not sure what the future holds since content-only is apparently going away (?). These theme packages will somehow have to be specially delineated so that content is copied to the `ThemeFolder` instead of the `InputFolder` like it normally would be. This approach also provides theme authors a little flexibility since they wouldn't have to distribute as a NuGet package. The theme could just be zipped up, distributed, and then unzipped to the `ThemeFolder`.

There should also be a way to specify a theme on the command line using something like a `--theme` flag. This would presumably refer to a NuGet package or maybe a zip file.
- Perhaps first check the working path combined with the given theme name/path (could also provide a full path in the flag), adding a `.zip` extension if one isn't already there. If a file is found, and there isn't already a `ThemeFolder` we'll unzip it to the `ThemeFolder`.
- Then, if no file is found, check for a NuGet package with the given name and if found, extract all contained content to the `ThemeFolder`, but again only if the `ThemeFolder` isn't already there.
- Also provide an `--updateTheme` flag that deletes and recreates the `ThemeFolder` from the specified source (so `--theme` must be provided if `--updateTheme` is used)

**Comment by daveaglick** [comment]
Just occurred to me that this same folder override logic could also help resolve the issue of resources from NuGet packages getting mixed in with standard input content. NuGet package content should also go into it's own folder that gets checked after checking the `InputFolder` (maybe call the property `PackageFolder`, but will need a different name than "Packages" for the actual folder since that's where the packages themselves go).

**Comment by daveaglick** [comment]
Would also be cool to load themes straight from a git repo and/or GitHub

**Comment by Kkloss** [comment]
Hey,

There hasn't been much activity on this lately but what's the story with themes for Wyam? I was looking around and saw that @gniriki added a theme to his blog (see here: https://github.com/gniriki/gniriki.com/commit/fa753ba49b37fa376adc94481da66a7ad63fd49e) but I am not sure if that's the way to go or if there is going to be an official way to implement themes.

**Comment by daveaglick** [comment]
@Kkloss I know it appears as if this issue is stalled, but that's actually really deceiving. As it turns out, everything I've been doing for the last couple months has been leading up to theme support. That includes a complete rewrite of the IO handling to add a layer of abstraction.

I view this work as critical for theming because it will enable multiple input folders aggregated to appear as one. The idea for the theming engine is that you'll be able to specify a theme, which will get installed into a "lower priority" input folder, and then your content and any theme overrides will go in a "higher priority" input folder.

Themes a recipies also go together because a given pre-canned theme is only going to make sense with a given pre-canned site configuration (or "recipie"). Recipies and themes will be the very next work item after the IO abstraction is completely finished (getting close). I don't have a definite timeline, but it's coming sooner rather than later.

**Comment by Kkloss** [comment]
@daveaglick That's awesome to hear. I will keep an eye out for the change to hit the master branch.

Also this might already be on the cards but once themes are added, it would be nice to have a tutorial or something that actually takes a Jekyll or a Bootstrap theme and converts it work with Wyam.

**Comment by daveaglick** [comment]
It's looking more and more like themes should be by convention and won't require any actual infrastructure support. The trick is just to make sure the folder containing the theme files is included in the input paths before the main input path.

They can be provided however is appropriate, but most commonly will be delivered as content NuGet packages. When a theme NuGet package is used in a build, the content folders will be automatically inserted at the beginning of the input paths.

For themes being tested, the theme can just be added to the input paths. For more control, the theme path added to the input paths doesn't have to be for the local file system. For example, you could load a theme from a GitHub repository using a path that specifies the GitHub file provider.

_Some_ configuration support could be useful to simplify this process. Current thought is that we can have a theme CLI/directive. The text in this setting will first be checked against a code-based directory of known themes which could be either a NuGet package _or_ a predetermined `DirectoryPath` (and if a `DirectoryPath` we also need to allow specifying NuGet packages that contain the needed file providers). If the provided string is not included in the directory, treat it as a path and insert it at the beginning of the input path list.

**Comment by daveaglick** [comment]
Theme "support" is done (since it ended up being so lightweight). All that's left to do is actually write the themes (and recipes they're used for).
