### ISSUE TITLE
Config file includes

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#73]
We need a way to include external config content in a config file. This is especially important for an external secrets file that shouldn't get checked in to source control, but could also be used to create more modular configs (I.e., a generic pipeline that could be used in multiple configs).

Since setup, declarations, and config sections go hand-in-hand, they have to be included as a unit. Current idea is to add a new object to the setup section to specify additional included config files.

**Comment by dodyg** [comment]
How will name conflicts be resolved especially for codes located inside in declarations where helper functions are located?

**Comment by daveaglick** [comment]
Great question. Current thinking is that included config files will be inserted in the order they're added to the collection and we would let the normal compiler rules and other checks apply and report conflict errors to the user. For example, the "config.wyam" might look like:

```
Packages
    .Install("bootstrap", "[3.3.5]")
    .Install("jQuery", "[2.1.1]");
Includes
    .Include("secrets.wyam")
    .Include("abc.wyam")
===
Pipelines.Add("Foo",
    // ...
);
```

Then "secrets.wyam" might contain some defined secrets that could be used:

```
string GitHubKey = "abcdefg";
string AzureKey = "1234567";
```

And "abc.wyam" may contain more declared strings as well as another pipeline (with the same names as existing stuff):

```
string AzureKey = "xyz1234";

Pipelines.Add("Foo",
    // ...
);
```

The net effect will be to combine the relevant config sections from all included files before sending them to Roslyn for parsing and evaluation (except for the setup section which will be evaluated for each included config file as soon as it's included, otherwise we wouldn't know what to include in the first place). That would yield this for the "final" combined config:

```
// From secrets.wyam
string GitHubKey = "abcdefg";
string AzureKey = "1234567";

// From abc.wyam
string AzureKey = "xyz1234";

Pipelines.Add("Foo",
    // ...
);

// From config.wyam
Pipelines.Add("Foo",
    // ...
);
```

The effect will be a compiler error on the redefinition of `AzureKey` and, once that's corrected, an exception when `Foo` is used for the second time to add a pipeline. It'll be up to the user to reconcile those types of conflicts before the config will evaluate and you can execute the engine.

Also, one more _note to self_: The `.Include(...)` method used to specify includes should have an overload or optional parameter (defaulting to false) to indicate if the included content should be placed _after_ the exiting stuff instead of before. This would let includes manipulate pipelines or other config objects after they've been created (I.e., append an extra module into every pipeline).

**Comment by MaximRouiller** [comment]
Or maybe we can look into how ASP.NET 5 does it with config.json? It's not code... that's for sure but the "concept" is already there.

**Comment by daveaglick** [comment]
Does it have some sort of include functionality? I wasn't aware of that... Suspect it works kind of like XInclude (for XML documents)?

**Comment by MaximRouiller** [comment]
I don't have that environment on my work machine right now but here's a blog post showing off how they do things at the moment:

http://gunnarpeipman.com/2014/11/asp-net-5-new-configuration-files-and-containers/

**Comment by daveaglick** [comment]
Something that occurred to me is that any included NuGet references will have to be combined with other references to the same package (possibly different or even incompatible versions). It's not unreasonable to think an included config file might have NuGet references of it's own. If we evaluate the setup sections as files are included (which we have to do to make sure we get nested includes), care needs to be taken to make sure duplicate NuGet packages in included files are handled gracefully.

**Comment by avishnyakov** [comment]
Folks, that not be only about config file includes, but might also be about the whole config file redesign or extensibility provider? 

The lack of intellisense is cruel. Only "Cool name" puts smile on the face while fighting typos and copy-pasting snippets in the config.

Is there any way or extensibility point to provide custom implementation of the config?

For instance you stay in VS (or other IDE), crafting a **compilable** c# file within windows library project so that the **intellisense** is there. Essentially, the config can be implemented as a class that implements IConfig/IConfigprovider interface (whatever the interface is) to load assemblies, get the pipilines and register custom functions. Hmmm, Wyam uses Roslyn, that means that the config can be provided as a compilable C# class, correct? Pure gold and win!

Not too sure how to hookup with Wyam, so knowing how to provide alternative config file would be more than needed - some would go with JSON config, some with XML, I would stick to _compilable_ c# file :)

Believe that would improve efficiency story aroube crafting *.wyam config and pipelines as well as reduce frustration around typos /  intellisense.

**Comment by daveaglick** [comment]
Note that you can basically already do this. The console application and config file are basically just a thin wrapper around directly configuring and working with the `Engine` and the rest of the Wyam.Core API. It's entirely possible and valid to create your own "Wyam app" that configures the engine just through code without using a config file at all. Or create a library with a method that configures the engine through code and then call that from your config file to get the top-level console app features like watching.

All that said, there's probably still a good story in here for VS extensibility as well...

**Comment by daveaglick** [comment]
Closing this issue as a duplicate of #228
