### ISSUE TITLE
Referencing a VS solution doesn't seem to use the specified compilation symbols

### ISSUE THREAD

**Issue by SilentSin** [statiqdev/Statiq#730]
Wyam 1.6.0.

- I'm referencing a VS solution containing a single project with only one configuration (Release).
- It has the following symbols defined: `<DefineConstants>TRACE;UNITY_EDITOR;UNITY_2017_3_OR_NEWER;UNITY_2018_1_OR_NEWER</DefineConstants>`
- I can build it successfully using VS and it spits out a DLL containing all the correct code.
- But when Wyam generates documentation for it, it still doesn't pick up anything inside the #ifs.

**Comment by SilentSin** [comment]
@daveaglick I'm still having this issue in Wyam 1.7.1. Can you suggest anything else I can try to get it working?

**Comment by daveaglick** [comment]
That's because I updated Buildalyzer to support MSBuild constants, but forgot to update the package in Wyam 😬. Going to try and get a 1.7.4 release with updated Buildalyzer out for you later today or tomorrow.

**Comment by daveaglick** [comment]
Okay, 1.7.4 is going out now. I'm going to close this since I'm like 90% sure that'll resolve this. Let me know if it doesn't and I'll re-open the issue.

**Comment by SilentSin** [comment]
Yep, that fixed it. Thanks a lot. I really love this tool you've made.

**Comment by daveaglick** [comment]
Awesome! And thanks, you made my day 😃
