### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#733]
Several code quality updates I'd like to make before 2.0 (note to self):

* Refactor tests
  * I used to adhere to a strongly nested test class structure, but I've relaxed that opinion a bit, refactor tests to be a little flatter as `ClassUnderTestTests` without the nested classes for each method/property
  * Switch all tests to use the `Wyam.Testing` classes and remove all uses of proxies and stubs
  * Get rid of other assertion libraries (include NUnit `Assert.`) and standardize on Shouldly
* Fix code style warnings (should be no warnings)
  * Add XML comments everywhere that doesn't have them
  * Other fixes as recommended (or change settings)
* CI improvements
  * Start running CI and tests on Linux once all the Framework bits are gone
  * Add the AppVeyor logger to real-time test result reporting
  * Consider Azure DevOps for beta builds and CI

**Comment by 9034725985** [comment]
maybe we can track #627 here as well

**Comment by daveaglick** [comment]
I ended up skipping these for 2.0 to get it out the door, will revisit in the near future.

**Comment by daveaglick** [comment]
Most of these code quality improvements are now done (at least the ones I'm likely to tackle any time soon). Shouldly is now the only assertion library, proxies have been removed from tests, everything is now on Azure Pipelines with real-time test reporting, and code suggestions have been acted on (except for blanket XML comments which I gave up on for now).
