### ISSUE TITLE
including Wyam.Images breaks build

### ISSUE THREAD

**Issue by olevett** [statiqdev/Statiq#739]
I've had wyam up and running for a little while, but recently updated to 1.6, and now hitting something fun...with a minimal example
```
#n Wyam.Yaml

Pipelines.Add("Footer",
    ReadFiles("footer.yml"),
    Yaml()
);
```
works, but adding `#n Wyam.Images` errors with "Line 6: CS0103: The name 'Yaml' does not exist in the current context"

With verbose on, the following error is shown
>  Attempting to resolve dependencies for package 'Wyam.Images.1.6.0' with DependencyBehavior 'Lowest'
>    Exception while installing packages: Unable to resolve dependency 'SixLabors.ImageSharp'. Source(s) used: 'https://api.nuget.org/v3/index.json', 'C:/Users/l3v5y/.nuget/packages'

but I can't work out how to persuade Wyam that this is a reasonable package.

This is happening with Wyam.Cake, Wyam.exe and on both AppVeyor and my local machine.

**Comment by daveaglick** [comment]
I wonder if it has something to do with the ImageSharp dependency being pre-release. What happens if you add `#n Wyam.Images -p`?

**Comment by olevett** [comment]
That seems to be it! I'm happy to put a PR in against the docs if you think it's worth it?

(I've now also got to update to the newer images API, so not got a complete build, but that's solved the immediate problem, thanks!)

**Comment by daveaglick** [comment]
A docs update can’t hurt. I was hoping ImageSharp would get out of pre-release soonish, but it looks like they’re taking their time (which is fine). Might save others from the same trouble you had.

**Comment by olevett** [comment]
I think, given the shift in behaviour/building in dotnet rather than in the .wyam file, so I don't think it's an issue any more...sorry for never getting round to documenting this on Wyam!
