### ISSUE TITLE
Using System.ValueTuple in wyam.config causes an error

### ISSUE THREAD

**Issue by tesar-tech** [statiqdev/Statiq#750]
Tried to use tuple:
    `var unnamed = ("one", "two");`

Throws an error:
```
1 errors compiling configuration:
Line 66: CS8356: Predefined type 'System.ValueTuple`2' is declared in multiple referenced assemblies: 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

(using wyam 1.7.4)

Any easy fix?

**Comment by daveaglick** [comment]
This looks related to #749. I’ll take a look at this first thing as soon as 2.0 rolls out the door (which should be any day - possibly today).

**Comment by tesar-tech** [comment]
Does not seem like a problem in 2.0.

**Comment by daveaglick** [comment]
Awesome! Not totally surprised since .NET Core has a much better binding mechanism and this looked like an assembly resolution problem, but happy you’re able to confirm it without me having to do much 😃
