### ISSUE TITLE
Fix AppVeyor guide and any other advanced docs that need to be updated for 2.0

### ISSUE THREAD

**Issue by tesar-tech** [statiqdev/Statiq#756]
e.g.:  https://ci.appveyor.com/project/tesar-tech/zodoc/builds/20629508

**Comment by daveaglick** [comment]
Looks like you’re extracting the zip file and then attempting to run `Wyam`? The zip file now ships with a .NET Core framework-dependent deployment (see https://wyam.io/blog/version-2.0#zip-archive). That means it contains `Wyam.dll` and needs to be invoked with the `dotnet` bootstrapper like `dotnet ..\Wyam\Wyam.dll ...`.

**Comment by tesar-tech** [comment]
It is "broken" since 2.0, yes. It means [docs](https://wyam.io/docs/deployment/appveyor) is broken too.

**Comment by daveaglick** [comment]
Yep, looks like that docs page needs to be updated. I updated the quick start and others but missed this one. Going to reopen this issue to track.

**Comment by daveaglick** [comment]
Thanks for the docs PR. I checked the other deployment sections and none of them reference the old exe directly. I did find one reference in advanced docs about unit testing and corrected it, but otherwise I think we're good.
