### ISSUE TITLE
Issue with Wyam 2.1.1

### ISSUE THREAD

**Issue by knopa** [statiqdev/Statiq#762]
Severity	Code	Description	Project	File	Line	Suppression State
While update nugate packages I got next issue, but 1.7.4 works properly

> Could not install package 'Wyam 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by daveaglick** [comment]
Could you provide a little more context? How are you using Wyam? Is it being used in conjunction with a build tool like Cake or in a .NET project or are you calling `wyam.exe` directly, in which case what action are you taking to update NuGet packages?

Note that Wyam 2.x targets .NET Standard - see https://wyam.io/blog/version-2.0

**Comment by knopa** [comment]
I use nuget to download and keep up to date. After that from nuget packages use wyam.exe directly.

**Comment by daveaglick** [comment]
Okay, think I understand. Whereas all the supporting libraries (I.e., `Wyam.*` packages) target .NET Standard, the client application `wyam.exe` contained in the `Wyam` package now targets .NET Core so it can run cross-platform. You'll need to have .NET Core installed on the system where you're installing Wyam. A new alternative that might be better than manually downloading the NuGet package would be to install it as a .NET Core global tool using the `Wyam.Tool` package, which still gives you control over versions and updates. There are no current plans to distribute a .NET Framework version of `wyam.exe` in the 2.x version (though it may come back in 3.x - still undecided on that).

**Comment by daveaglick** [comment]
Just checking back in - are you good to go now?

**Comment by knopa** [comment]
yes, thanks
