### ISSUE TITLE
Book Site example results in 404

### ISSUE THREAD

**Issue by gortok** [statiqdev/Statiq#780]
This page: https://wyam.io/recipes/booksite/overview contains a URL to: https://github.com/Wyamio/Wyam/tree/develop/examples/SherlockHolmes 
which results in a 404.  I've attempted to follow the source code to figure out where it should point to but could not find the right URL.

**Comment by daveaglick** [comment]
That's coming down with the next release within the next week or two. The BookSite recipe is being removed. You happened to catch it in between removing the example and removing the actual recipe (which will take it off the docs). See #764 for the reasoning.

**Comment by gortok** [comment]
Thanks for the quick response!
