### ISSUE TITLE
Tool fails to install

### ISSUE THREAD

**Issue by wh1337** [statiqdev/Statiq#782]
When attempting to do `dotnet tool install -g Wyam.Tool` it fails to install per the guidelines on the README.md.

![image](https://user-images.githubusercontent.com/11448029/53044659-a535a200-3459-11e9-9c59-f517e5448308.png)

**Comment by daveaglick** [comment]
This looks like you have a secondary global NuGet source configured at `http://cnet-tst-web01/httpAuth/app/nuget/feed/ProjectEos/Primary/v3/index.json` and that NuGet source is failing. Unfortunately .NET Core and the NuGet client will fail to download a package if any existing NuGet sources fail (it works under the assumption that it needs to check _every_ configured package source to make sure it's finding the best package version). Try temporarily turning off that global NuGet source and see if it works. If you can't or don't want to turn off the source then you'll need to download the executable as a ZIP and run it manually.

**Comment by wh1337** [comment]
Ah! That was the reason. Thank you!! I ended up download the zip file to do it that way. Thank you for your quick reply!
