### ISSUE TITLE
[question] Shortcode samples

### ISSUE THREAD

**Issue by TechWatching** [statiqdev/Statiq#785]
Is there somewhere I can find samples for the new shortcodes (Giphy, Highlight, YouTube ...) ?

**Comment by daveaglick** [comment]
Docs for each of the new shortcodes (including examples) should be up later tonight at https://wyam.io/shortcodes/ - just need to polish off a couple things before publishing a new version

**Comment by daveaglick** [comment]
Documentation on the new shortcodes is available now at https://wyam.io/shortcodes/. I'm also working on updating the general shortcode documentation to add a little more detail.
