### ISSUE TITLE
A shortcode with the name highlight was not found

### ISSUE THREAD

**Issue by TechWatching** [statiqdev/Statiq#787]
I receive this error when using the sample from the following documentation:
```
<?# highlight csharp ?>
public class Foo
{
  int Bar { get; set; }
}
<?#/ highlight ?>
```
My config file is the following: 
```
#recipe Blog
#theme CleanBlog
#n Wyam.Highlight.Shortcodes

// Customize your settings and add new ones here
Settings[Keys.Host] = "host.com";
Settings[BlogKeys.Title] = "My Blog";
Settings[BlogKeys.Description] = "Welcome!";

```

**Comment by daveaglick** [comment]
The docs have a little bug - the `Highlight` shortcode is actually in the `Wyam.Highlight` package (inside a nested `.Shortcodes` namespace to not conflict with the module, which is what’s tripping up the docs). Planning on fixing that today. In the meantime, please try `#n Wyam.Highlight` and let me know if that works.

**Comment by TechWatching** [comment]
Yes it works. Thanks. Is it intended that by default code renders inline (all on the same line) ?

By the way using ```#n Wyam.All``` instead of Wyam.Highligh always result in errors.
For instance: `Error while loading configuration: System.Exception: The recipe "Blog" could not be found`

**Comment by daveaglick** [comment]
Good - the docs update is going out soon.

And good catch on the `Wyam.All` meta-package - looks like it's NuGet graph has been hosed since 1.1.0 😱. No idea why packaging stopped working, but I'll take a look now. Opened #788 to track.
