### ISSUE TITLE
Generation of _redirects file to redirect the default Netlify subdomain to the primary domain 

### ISSUE THREAD

**Issue by TechWatching** [statiqdev/Statiq#791]
Is there a way with wyam to generate the "_redirects" file used by netlify ?

I have seen that there is a setting "BlogKeys.NetlifyRedirects" but from what I understood it concerns individual pages with specific Metadata value. What I want to do is redirect all the netlify subdomain to my custom domain as explained on the screeshot below from netlify site.

![netlify](https://user-images.githubusercontent.com/15186176/53883744-19577480-401a-11e9-8edf-4ee9ea6f762b.png)

**Comment by daveaglick** [comment]
The easiest way would be to add a raw `_redirects` file to the root of your `input` folder. All the files from `input` get copied to `output` (with the exception of ones that get processed like Markdown).

I think that's what you were after...or did I totally misunderstand the question?

**Comment by TechWatching** [comment]
Yes exactly what I was looking for, thanks. Sorry for the question, it seems obvious now :) but I did not think that all files were copied to output folder. Closing the issue.

**Comment by daveaglick** [comment]
No problem at all 😀
