### ISSUE TITLE
Multi Language Content

### ISSUE THREAD

**Issue by spadino** [statiqdev/Statiq#793]
Hi guys! So, loving wyam so far... however, being a polyglot myself, and dealing with a multi language audience, I need to publish my sites in at least four languages. I now that I can create a hierarchical folder tree to accommodate that, such as:

```
input/
    en-us/
        content here...
    it-it/
        contenuto qui...
    pt-br/
        conteúdo aqui...
    es-es/
        etc...
```

however, that's means that I possibly have to duplicate many things, which is not clever or elegant neither. There's some better solution by now?

Thanks

**Comment by daveaglick** [comment]
There have been several discussions about the desire for in-the-box localization support, but so far it's still not clear to me what that would look like. I'd be more than happy to consider adding some features in this area, I just honestly have no idea what would be helpful. If you've got ideas, please do share.

[In this comment](https://github.com/Wyamio/Wyam/issues/599#issuecomment-354016614), I had some suggestions for how you could make it work on top of the current functionality.

**Comment by spadino** [comment]
Thanks for you're kind reply. I'll try to help in regard, but I need to understand better the underline working of wyam and modules. 

Anyway, I find that the most comfortable solution so fare, between the ones I already used or tested, are the one hugo uses: you globally define how many and which languages your content will be published to than, for each page, you have a bunch of postfixed markdown text (e.g. Page.it.md, Page.en.md, etc...). When built, each page is linked to all their translations, and the default language is used in case of missing translations.

Of course, postfixes and prefixes should be user definable...

**Comment by spadino** [comment]
The mais reason for the hugo approach being comfortable is because avoid replicated source tree, which can be hard to maintain (unless preferred). So, each post has its folder, which can include: post.en.md, post.it.md, post.es.md, pictures/, docs/, etc...

**Comment by daveaglick** [comment]
I have a localization strategy now, closing this in favor of #796
