### ISSUE TITLE
Create a JavaScript minifier module

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#8]

**Comment by avishnyakov** [comment]
+1 for that one

**Comment by leekelleher** [comment]
Following on from #12 #260, we could use the WebMarkupMin library to handle JS & CSS #9 minification?

My question is, which module/namespace should they live in? Maybe a new "Wyam.Modules.Minification" namespace/assembly?

**Comment by daveaglick** [comment]
Yes to all counts!

I'd love to leverage the WebMarkupMin library for this, and I think you're spot-on putting these new minifiers in a separate library and moving the HTML minifier to the new library as well. That will isolate the dependency, which will be important for when we're building a version for Core and can support some module/dependency combinations but not others initially.

**Comment by daveaglick** [comment]
Implemented as `MinifyJs` in #266
