### ISSUE TITLE
Queston - asp.net mvc 5

### ISSUE THREAD

**Issue by dotnetshadow** [statiqdev/Statiq#804]
Does his library still work with asp.net mvc 5? I don't mind generating the content / cms using .net core, but is there a nuget package that will be able to used in asp.net mvc 5?

**Comment by daveaglick** [comment]
For now, yes. If you want to rig up the pipelines and execution yourself, both Wyam.Core and Wyam.Common currently target .NET Standard which is usable from .NET Framework.

In a future version (probably 3.0), all Wyam.* libraries will target .NET Core. That means the host application needs to target .NET Core as well. As far as I know, ASP.NET MVC 5 is usable from a .NET Core application, so even then you'd still be able to use Wyam _as long as_ your ASP.NET MVC 5 application also targets .NET Core.
