### ISSUE TITLE
Feature Request: specify default code highlighting language in the config file

### ISSUE THREAD

**Issue by SilentSin** [statiqdev/Statiq#829]
I just found that I can get better syntax highlighting for my code blocks by putting `csharp` at the top like so:

```csharp
    ```csharp
    public virtual void MyMethod()
    {
    }
    ```
```

But since every code block on my site is in C# I'm thinking it would be nice if I could just specify that in the config file.

**Comment by daveaglick** [comment]
After reviewing this issue some more (in the context of other broader changes I've been working on with highlighting), I don't think this particular change is quite right. The behavior of Markdown code blocks is pretty well defined and I don't want to stray from that well-known definition.

We also now have a `FencedCodeBlocksShouldHaveLanguage` [analyzer](https://www.statiq.dev/framework/execution/analyzers) in Statiq Web that can catch and warn (or generate an error) about code blocks that don't specify a language.

I suppose it would also be possible to enable this behavior by adding a `ProcessHtml` module to the Statiq Web `Content` pipeline's post-process phase. That would do the trick nicely for anyone who really wants to change the default language for generated code blocks.
