### ISSUE TITLE
Getting OutOfMemory Exception while running all tests.

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#85]
This normally happens when I run all Tests. In the ExecuteAllExamples Test case.
Running ExecuteAllExamples test case alone is fine.

I thought the problem could be that the Engine in the example doesn't get disposed. but it didn't get better after disposing it at the end of the test.

**Comment by daveaglick** [comment]
Try excluding the GeneratedBlog example and let me know if that improves the situation. That one can be a bit of a memory hog.

**Comment by LokiMidgard** [comment]
It didn't worked. I excluded all paths in the Path-Property. Now it failed in Configuratorfixture.

Maybe it has something to do with the order the tests are executed. I will try different combinations of what tests to run to get the error.

**Comment by daveaglick** [comment]
Ok, thanks. The fact that the crash happens after some number of tests have been run suggests that there's a memory leak either in the test harness (hopefully) or in the application itself. Come to think of it, I recently changed the `Engine` to a disposable pattern but I don't think I edited all the tests to dispose the engine. Long shot, but possibly related.

**Comment by LokiMidgard** [comment]
I testet a lite bit with just the Build examples test case.

I tried to measure the memory footprint. following was the first without using:
![image](https://cloud.githubusercontent.com/assets/389101/10711690/710176e6-7a83-11e5-9866-5ce4ea93087d.png)

The second one with using:
![unbenanntes bild](https://cloud.githubusercontent.com/assets/389101/10711701/2a83d8a2-7a84-11e5-8181-41207b6fc515.png)

I took an Memoryprint before and after the test case. so every odd number is before and every even number is after a test case. I wasn't able to create the last memoryprint in the first case because I run out of Memory :(

In both cases I tried to force garbage collection using GC.Collect() after each test case.

The moste interesting part is that even with using I run in the Out of MemoryException. But if I execute GC.Collect() at the end of each test I no longer get those errors. But I'm not sure if this is deterministic, it could just be a coincidence.

**Comment by LokiMidgard** [comment]
Also GC.Collect seems to prevent the out of memoryException also if the engine is not disposed. :\

**Comment by daveaglick** [comment]
Good investigatory work. It'll take me a while to digest all this. I'm traveling today, but if I get a chance I'll run it through some more profiling later. From your initial results, it does look like we're gaining a lot of allocations on each test run. What runner are you using - the one built-in to Visual Studio?

**Comment by LokiMidgard** [comment]
Yes.

**Comment by daveaglick** [comment]
Is this still an issue with 0.11.0-beta? There were several changes related to performance and memory, so wondering if we still need to investigate this...

**Comment by daveaglick** [comment]
So much has changed and I haven't seen anything like this in a while. I'm going to close this issue - just let me know if it turns out this is still a problem.
