### ISSUE TITLE
Hard coded page title "Archive" in recipe blog

### ISSUE THREAD

**Issue by deerchao** [statiqdev/Statiq#864]
https://github.com/Wyamio/Wyam/blob/8dee4f1e2b7c633658c6c05253ba9fc5914b117f/src/recipes/Wyam.Blog/Blog.cs#L135

This makes it difficult to customize or translate themes. This could be resolved by changing it into:

```
Title = (doc, ctx) => doc.WithoutSettings.Get(BlogKeys.Title, "Archive"),
```

**Comment by daveaglick** [comment]
I'm slowly working on cleaning up some of the issues that came over from Wyam. Since this one is pretty old I'm going to go ahead and close it. Please don't hesitate to comment or open a new one if it turns out this issue is still relevant in Statiq.
