### ISSUE TITLE
Usage with a GitHub Pages User site

### ISSUE THREAD

**Issue by ghost** [statiqdev/Statiq#869]
Really enjoying Wyam. Thank you.

For a GitHub Pages User site (as opposed to a project site), that is not built using Jekyll, the source and built output cannot live in the same repo (I'm fairly certain). 

Therefore I needed some solution to build output to another directory, which is also a repo. There are the options `--output <path>` and `--noclean` on `wyam build`. 

They would leave me with either not cleaning up any old files that have recently been deleted, or deleting the whole directory and therefore blatting my repo. So I end up with a manual file copy across repos in VS Code. It's the least worst option for me at the moment. I'm sure there are better/safer/consistently repeatable ways - maybe scripting it. Git scripting would be non-platform specific, but it's way too painful for me!.

I thought it might be worth pointing this out, perhaps as a future feature here or in Statiq (only just seen that). 
- Perhaps a `#partialclean` option in `config.wyam` whereby a .gitignore-style list of files & folders could be specified as **not for deletion**.
- Alternatively, an option to leave read only files in place when cleaning the directory. But that seems like relying on a side effect of the directory being a repo, rather than being specific.

Thanks..

**Comment by ewinnington** [comment]
I don't know if this helps you, but I solved it with [Actions on Github pages ](http://ewinnington.github.io/posts/wyam-github-actions). Both the source and the output live in the same repo, but on different branches.

**Comment by SilentSin** [comment]
I created a similar feature request for the ability to [exclude certain files when cleaning the output path](https://github.com/Wyamio/Wyam/issues/795) a while ago.

**Comment by daveaglick** [comment]
I'm slowly working on cleaning up some of the issues that came over from Wyam. Since this one is pretty old I'm going to go ahead and close it. Please don't hesitate to comment or open a new one if it turns out this issue is still relevant in Statiq.
