### ISSUE TITLE
RSS feed without text content?

### ISSUE THREAD

**Issue by deap82** [statiqdev/Statiq#870]
Is there any way to get the blog rss feed to only include the post headers, but none of the text?

Use case:
We're setting up Wyam to be used behind login for internal documentation but would like to expose the rss feed to be able to get notifications on new blog posts in Slack for example. In that scenario we would like to expose only the post titles (+ link and timestamp of course) in the rss feed.

**Comment by daveaglick** [comment]
Were you able to figure this out?

**Comment by deap82** [comment]
@daveaglick Actually I decided I didn't want to bother you with it because I have some other questions coming up... (Wrote in gitter just now)

Also, the wyam site will be hosted within a .net core application so I'm thinking about writing my own endpoint that will consume the wyam blog rss feed and return the "censored" version, just so we can get the notifications about new posts to Slack :-).

Sorry for just closing the issue.

**Comment by daveaglick** [comment]
No problem at all! I'll head over to Gitter...
