### ISSUE TITLE
Indented fenced code blocked not processed unless in list

### ISSUE THREAD

**Issue by hawkerm** [statiqdev/Statiq#872]
If I have the following markdown:

~~~
Create a Spaceship class:

    ```java
    import java.awt.Color;
    ...
    ```
~~~

It will render the fenced blocks:

![image](https://user-images.githubusercontent.com/8959496/67253903-0ec5e000-f42f-11e9-8803-29841c4aa240.png)

But if I instead make the first element an item in a list, it'll render as expected:

~~~
1. Create a Spaceship class:

    ```java
    import java.awt.Color;
    ...
    ```
~~~

![image](https://user-images.githubusercontent.com/8959496/67253923-27ce9100-f42f-11e9-8774-a35e9fdb3b7b.png)

It'll also render fine if I don't indent the code block:

~~~
Create a Spaceship class:

```java
import java.awt.Color;
...
```
~~~

![image](https://user-images.githubusercontent.com/8959496/67253940-387f0700-f42f-11e9-865b-4f42f3352b8a.png)

However, I'm trying to indent the code block on the page itself.

**Comment by arebee** [comment]
Isn't a Wyam.io issue IMO so much as Markdown. You're pretty much stuck with using space chars in your code block to fake the indent AFAIK or use HTML directly and lose pygments. Happy to learn an alternate.

Create a Spaceship class:

\```java
␠␠␠␠import java.awt.Color;
    ...

Will render:

Create a Spaceship class:

```java
   import java.awt.Color;
    ...
```

**Comment by daveaglick** [comment]
I'm slowly working on cleaning up some of the issues that came over from Wyam. Since this one is pretty old I'm going to go ahead and close it. Please don't hesitate to comment or open a new one if it turns out this issue is still relevant in Statiq.
