### ISSUE TITLE
Mathematics / latex notation won't render by default

### ISSUE THREAD

**Issue by atiq-cs** [statiqdev/Statiq#875]
Here's screenshot of default installation of wyam with blog recipe,

![image](https://user-images.githubusercontent.com/7858031/69453737-6b136c80-0d19-11ea-9d1c-6cadc1b82873.png)

As far as I remember default `MarkdownConfiguration` is `advanced + bootstrap` and advanced includes mathematics package. However, my math blocks are not rendering yet. I am using Cake build. Here are my package version,

```
#tool nuget:?package=Wyam&version=2.2.9
#tool "nuget:?package=GitVersion.CommandLine&version=5.1.2"
#addin nuget:?package=Cake.Wyam&version=2.2.9
#addin nuget:?package=Cake.Git&version=0.21.0
```
my `config.wyam` file is unmodified default.

## How to repro
Try default installation of wyam and write a post with a math block.

Example math blocks,

    This is a $\infty \frac{x^3}{e^x-1}$ with few symbols.

    Eq 1,
    $$
    \begin{equation}
      \int_0^\infty \frac{x^3}{e^x-1}\,dx = \frac{\pi^4}{15}
      \label{eq:sample}
    \end{equation}
    $$

    Eq 2 without starting with beginning equation tagger,
    $$
    \Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt\,.
    $$

**Comment by atiq-cs** [comment]
cc @daveaglick @phil-scott-78 @tbolon @Silvenga

**Comment by daveaglick** [comment]
Did my answer over at https://github.com/daveaglick/daveaglick/issues/7 help at all? If not, I'll go ahead and close that one and we can continue the discussion over here...

**Comment by atiq-cs** [comment]
Yes. That helps, seems to be the right direction.

Do you happen to know of an example, probably a statiq user who is using math notations?

Thanks so much again for your time. :)

**Comment by daveaglick** [comment]
I'm slowly working on cleaning up some of the issues that came over from Wyam. Since this one is pretty old I'm going to go ahead and close it. Please don't hesitate to comment or open a new one if it turns out this issue is still relevant in Statiq.
