### ISSUE TITLE
Should extra source information be made available

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#88]
@LokiMidgard brought up a great question in #86: whether we should be providing more context for the `IDocument.Source` property. Right now, it's only required to be a string and there's no information about what kind of string it is, what sort of source it refers to, etc.

For context, the `IDocument.Source` property was added for two specific reasons:
- To give the caching engine a unique key that it could use that would persist across generations. That way, even though the `IDocument` instances would be new from one generation to the next, the cache could still match up the module/source pair to get the cached information.
- To provide better error handling output by displaying a more meaningful string to the user when something goes wrong.

This second reason (more meaningful error reports) is why I exposed `IDocument.Source` at all. I actually debated whether or not I wanted to make the source string visible to external modules for fear it might be confusing. I ended up exposing it so that external modules could use it in error messages and the like.

So now the question is, should be expand on these two uses of `IDocument.Source` and make it more generally useful? The specific problem @LokiMidgard posed was what if I want to use the source to locate files on disk, and need to assume that it points to a file system path?

Here are some possibilities of how we might address this:
### SourceType Enum

One way to address this would be to rely on something like a `SourceType` enum. Everywhere source is provided (for example, `IExecutionContext.GetNewDocument()`), you would also have to provide a value for the enum. This would let downstream modules look at the enum to better understand what the `Source` property contains.
### SourceIsFileSystem bool

Another way to address this might be to only differentiate between file system sources and non-file system sources. In this case, we could just have a bool that flags whether the source points to something on the file system. This might be easier to use, but we would loose fidelity over the enum approach.
### Uri Schemes

Another approach might be to overhaul the source altogether and base it on URIs instead of just being a string (note that I'm talking about URI and not URL). Then we could look at the URI Scheme to understand what the source is referring to.
### Do Nothing

A final approach might be to just leave it the way it is, but document that `IDocument.Source` _should not_ be used outside error messages and that nothing can be inferred from it. Instead, if you're looking for information on the file system from a document, you should check for the presence or absence of metadata that the coorisponding upstream module would have produced. For example, if a module wants to only work with documents from the file system, then it should check for the `SourceFilePath` metadata key instead of relying on source. If the key is available, then the document came from the file system and you have the path. If not, then it didn't. This would go for any module that relies on a given type of document - check the metadata for keys that you know the module that creates those documents would have left.

I don't know which of these would be the best approach. It would be nice to get some additional input cc @dodyg

**Comment by LokiMidgard** [comment]
I like the two last best.

The second (IsFilesystemFile()) on the other hand is to narrow. 

What I relay like about the Uri Schemes, they are already done. Including validation, IsFile and a bunch of other helper methods.

**Comment by dodyg** [comment]
I like Uri scheme because they are extensive. The problem with Uri scheme is because they are extensive.

http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

What will happen if you need something that is not specified by the Iana  registry?
What would be the Uri scheme for documents generated by `TextGeneration` module? How do you refer to just directory?

I know SourceType enum can be limiting however you can have SourceType.URI and have modules to inspect the Uri scheme contained in the string. You can define other common source types such as SourceType.File, SourceType.Text, etc  that people can use in the modules.

**Comment by daveaglick** [comment]
Good feedback, thanks both. My first gut reaction was really leaning towards URIs. However, I think @dodyg's point about what to use for `TextGeneration` for example, is a good one. URIs appear to be geared towards actual resources, which isn't quite the same thing as source. Even with a custom scheme, it may not make much sense for documents with purely generated content.

I also have concerns about confusing users. Everyone understands a string source, but URI might be a foreign concept for some.

So now I'm leaning towards @LokiMidgard original idea of an enum. Probably with some additional validation per enum value so consumers can be assured that a file is actually a path, a URI is actually a URI, etc. I'm not 100% though, so I'll probably think about it a while longer. Any extra insights or thoughts, feel free to share!

**Comment by dodyg** [comment]
I think if we are using enum then the source becomes a mandatory field and that will impact the signature of the IDocument interface.

**Comment by daveaglick** [comment]
`IDocument.Source` is now a `FilePath` which contains information about the actual file system (local drive, web resource, etc.) the document came from as well as where within that file system it was located. I think that captures the intent of this issue, so I'm going to close it. Feel free to open a new issue (or request this one be reopened) if you feel there's more to discuss on this.
