### ISSUE TITLE
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found

### ISSUE THREAD

**Issue by ghost** [statiqdev/Statiq#883]
~~~
C:\> dotnet-runtime-3.1.0-win-x64\dotnet.exe Wyam-v2.2.9\Wyam.dll
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.0 at [C:\dotnet-runtime-3.1.0-win-x64\shared\Microsoft.NETCore.App]
~~~

**Comment by perlun** [comment]
Per [this web page](https://wyam.io/docs/usage/obtaining), I think this is expected. Wyam does not run on .NET Core 3 yet, but requires .NET Core 2.1.

.NET Core 2.1 is itself [supported until August 21, 2021](https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

**Comment by daveaglick** [comment]
What @perlun said, .NET Core 2.1 is required. .NET Core will roll forward, but only within a minor release. Also note that Wyam won't be targeting .NET Core 3.x - new development is taking place in [Statiq](https://github.com/statiqdev) and I hope to have production-ready releases of that by mid-year.

**Comment by perlun** [comment]
@daveaglick looking forward to that! 🙂👍🏻
