### ISSUE TITLE
Build instruction

### ISSUE THREAD

**Issue by fanioz** [statiqdev/Statiq#897]
Hello, could you please provide build instruction, or it is somewhere ?

**Comment by fanioz** [comment]
![image](https://user-images.githubusercontent.com/1700770/81373494-12008f00-9127-11ea-8a63-2aa341c93082.png)

**Comment by daveaglick** [comment]
It looks like you're trying to build Statiq Web itself and the Cake build script isn't cooperating. That build script is actually only used for publishing new releases (it's called "build" as a holdover from when it built everything). Statiq Web is a normal .NET Core library so you can build it with `dotnet build` or by opening the `Statiq.Web.sln` solution.

I agree the presence of a build script when it's not used is confusing. I'll rename the build script and add a `BUILDING.md` file to make it clearer.

If you're trying to _use_ Statiq Web there's a quick start here: https://statiq.dev/web/
