### ISSUE TITLE
Create a CSS minifier module

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#9]

**Comment by JimBobSquarePants** [comment]
A wrapper round AjaxMinifier would work for that. I have a class nestled inside a project of mine that demo's how to do it. You could deal with #8 doing that also. 

https://github.com/JimBobSquarePants/Cruncher/blob/6168ec379ed89ae75468cd2d9cbd5d5f82dc17bb/Cruncher/Compression/CssMinifier.cs

**Comment by daveaglick** [comment]
James-ify all the things!

But seriously, that looks pretty good - I'll take a look at Cruncher. The Wyam module part is easy, so this might be a way to get comprehensive minification for very little effort - on my part at least :). Thanks again!

**Comment by JimBobSquarePants** [comment]
Ace! You should be able to grab a few things from there. Everything works well except the Sass module just now as the dependency has a bug.

**Comment by avishnyakov** [comment]
+1 for that one

**Comment by daveaglick** [comment]
Implemented as `MinifyCss` in #266
