### ISSUE TITLE
Process multiple heading levels

### ISSUE THREAD

**Issue by drmathias** [statiqdev/Statiq#904]
Hi, I was looking to generate a table of contents with multiple levels of headings. Was looking at retrieving the list of headings and then parsing the heading level for styling.

```csharp
IReadOnlyList<IDocument> headings = Document.GetDocumentList(HtmlKeys.Headings);
foreach (IDocument heading in headings) {
    int level = heading.GetInt(HtmlKeys.Level);
    string text = await heading.GetContentStringAsync();
}
```

Currently from what I can gather, Statiq.Web is configured to currently only processes top level headings. 

```csharp
new GatherHeadings()
```

Could it instead be configured to process headings up to h6?

**Comment by daveaglick** [comment]
Great idea - and I think we can do one better. Instead of a global setting, I might be able to pull the level from document metadata so that you could specify a global level and/or a per-document level.

**Comment by daveaglick** [comment]
Nice to have an easy one for a change :). Keep an eye out for the next release.
