### ISSUE TITLE
Errors upgrading from Alpha to Beta

### ISSUE THREAD

**Issue by igor-pikovsky** [statiqdev/Statiq#916]
Having update Nuget from Alpha to Beta, I suddenly encounter the following error
```
[ERRO] Content/PostProcess » RenderPostProcessTemplates » ExecuteIf » Error while executing module RenderRazor in Content/PostProcess: Sequence contains no elements
```

I don't see how I can debug this, as placing breakpoints in cshtml files makes no difference

**Comment by igor-pikovsky** [comment]
I traced this down to the fact that Outputs["Data"] is empty.
My inpuit/Data folder contains 7 json files. Previously in cshtml document I could access input/Data/myfile.json by 
```
IDocument pageData = Outputs["Data"].FilterSources("Data/myfile.json").Single();
```
Now Outputs["Data"] is always empty.

I see the following output:
```
[INFO]    Data/Process » Finished Data Process phase execution (7 output document(s), 106 ms)
...
[INFO] -> Data/Output » Starting Data Output phase execution... (7 input document(s), 2 module(s))
...
[INFO]    Data/Output » Finished Data Output phase execution (0 output document(s), 8 ms)
```
As you see, I have 7 documents to start with in the Data folder, but none of them made it to the output.

I have attempted adding _Directory.json containing "ShouldOutput ": true , but that made no difference.

Any suggestions?

**Comment by daveaglick** [comment]
Yeah, there was a recent breaking change related to the `Outputs` collection. Whereas before the indexer returned documents from a particular pipeline, it now does an aggregate globbing search over all pipelines. 

I'm trying to keep breaking changes to an absolute minimum, but as we get really close to a 1.0 release there may still be a couple breaks like this one where, based on feedback, the break is worth it to make the final system clearer (in this case, figuring out which pipelines to find which documents in was really confusing folks).

The release notes had details on this one - I'd continue monitoring those for the next couple releases just in case I have to make one or two more breaks like this. To get you back up and running you can call `Outputs.FromPipeline("Data")` and that will give you equivalent behavior to the old call.

**Comment by igor-pikovsky** [comment]
Thank you very much – it’s up and running again.

**Comment by daveaglick** [comment]
Great! Don't hesitate to ask if you run into any more upgrading problems - I'm happy to help everyone through these final versions leading up to release.
