### ISSUE TITLE
Documentation on Razor Templating for Statiq

### ISSUE THREAD

**Issue by blachawk** [statiqdev/Statiq#921]
I am still fairly new to learning basic Razor concepts, and wanted to use Statiq as a sandbox playground to start building razor pages.  I looked through the docs, but didn't see an examples on getting started with theming in Razor.

* Is it a normal practice creating an HTML base layout, with razor syntax solely in the `<body>` area? If not, what is?
* If I was going to build a master layout in Razor, how can I build different .cshtml views for it within a Statiq web project?
* How does razor use/reference partials in a Statiq.web project?
* Where can I learn basic and advanced coding & theming practices for a full Razor project in Statiq?

Many thanks for any advice in getting me started!

**Comment by blachawk** [comment]
The CleanBlog is exactly what I need to study and learn to begin my journey.  Thanks!

**Comment by daveaglick** [comment]
Awesome! Please feel free to reach out with any follow-up questions. If you end up looking for something more complicated, the [.NET Foundation website](https://github.com/dotnet-foundation/website) uses a more complex set of layouts.
