### ISSUE TITLE
Batteries not included!

### ISSUE THREAD

**Issue by Joebeazelman** [statiqdev/Statiq#946]
I was hoping to get up and running after got the initial markdown example working. When I tried to clone the blog example, however, I got a 404 error. Reading through the documentation was a real trial of my patience, resulting in extreme frustration. Here's an excerpt:

Troubleshooting Globbing Patterns
Statiq provides the glob command to help troubleshoot globbing patterns, which has two subcommands: glob eval and **blog** [sic] test.

You have wasted an hour of my valuable time. This isn't even good enough to be an alpha release. All you have done is grab some open source here and sprinkle a little open source there and pretend you have a product. With the amount of effort required to get this crap to work, the user is better off writing their own code generator. I've written a far better code generator back in 1995 using excel reports and a bit of VB!  There's no batteries included here. Not even a crank handle to get it started. Your application wears no clothes!

The only reason I even tried this pinnacle of mediocrity is because JamStack listed it as the most popular static generator for .NET. Adding insult to injury, you expect your victims to pay you for a commercial license?  Where's your shame?

**Comment by daveaglick** [comment]
I'm not sure what you were expecting, but your tone here is rude and completely uncalled for - unlike most users whom I do my very best to support, I'm happy I won't be needing to interact with you in the future 👋
