### ISSUE TITLE
Create Chocolatey package

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#95]

**Comment by avishnyakov** [comment]
+1

Not much of a usage from Chocolatey perspective or just technical impediments?

**Comment by daveaglick** [comment]
There's no technical reason this isn't done. It just hasn't risen to the top of my priority yet. There's a lot of thumbs up though, so maybe I'll take a look soon. Should probably mark it as up for grabs too...

**Comment by avishnyakov** [comment]
Well, you moved to Cakebuild recently (great stuff!) so that Choco packaging is additional task. I'll have a look and see what can be done. Thanks!

**Comment by david-driscoll** [comment]
As a stop gap you can use `choco install Wyam -s https://www.nuget.org/api/v2/` to install it as a tool into chocolatey. 👍

**Comment by daveaglick** [comment]
@david-driscoll Awesome, thanks - added that to the docs at https://wyam.io/docs/usage/obtaining#chocolatey

**Comment by avishnyakov** [comment]
@david-driscoll, shame on me, you are so right :)

**Comment by gep13** [comment]
If you wanted to, you could even go one step further, and simply push the same nuget package to chocolatey.org, but I don't think I would recommend this.

The Chocolatey nuspec allows from additional metadata, which nuget doesn't support.  This provides enhanced information about the package.  I would recommend that you stick with the idea of creating a standalone Chocolatey Package, including the additional metadata, and push that to chocolatey.org, when you are ready.

I would also suggest NOT using the same id.  You might want to use somethign like wyam.portable, or something like that, assuming you are just shipping the wyam.exe, and wanting chocolatey to create a shim for you.  It you are going to ship the setup.exe then perhaps wyam.install would be a better choice.

**Comment by phillipsj** [comment]
@daveaglick I would like to take this issue.

**Comment by daveaglick** [comment]
Yes, please! Even more important now that I've removed the Windows installer (which wasn't reliable).

**Comment by phillipsj** [comment]
Cool, do you have any thoughts already down on how you want this handled?  It will be my first Chocolatey Package.

**Comment by daveaglick** [comment]
Nope, none at all :) - I've never written a Chocolatey package either since most of my OSS tends to be libraries. Go nuts.

**Comment by gep13** [comment]
@phillipsj let me know if you have any questions. Happy to arrange a Skype call at some point if you want to talk anything through.  /cc @daveaglick

**Comment by phillipsj** [comment]
@daveaglick I am just going to create a Cake task to do it and I am going to do it all from Cake without a nuspec file.  If you want a nuspec file instead of it all being in Cake, let me know.

**Comment by daveaglick** [comment]
> Go nuts.

:smile:

Honestly, this will be such a great improvement I don't really care how it works.

**Comment by phillipsj** [comment]
Okay, I have a few questions for you shortly, need to make sure I get everything.  I am assuming I can take all the files just like the Wyam nuspec does.  @gep13 I can use Chocolatey/Gui to install it once I create it to test, correct?

**Comment by phillipsj** [comment]
@gep13 The Cake ChocoPackSettings doesn't seem to support the dependency attribute and it seems it is required now, is that correct?  If so, I can add to issue to Cake repo and submit PR.

**Comment by phillipsj** [comment]
![image](https://user-images.githubusercontent.com/1568133/33796605-10915018-dcc6-11e7-8127-4e22909b3bbf.png)

**Comment by gep13** [comment]
@phillipsj there is actually an open PR waiting on me to review it for adding exactly that.  If you wanted to take it for a spin and test it out, that would be great.

**Comment by gep13** [comment]
@phillipsj when you say that the dependency attribute is required, can you elaborate on exactly what you mean?

**Comment by phillipsj** [comment]
@gep13  this part had to be added to get it to pack.

    <dependencies>
        <dependency id="Chocolatey" version="[0.10.3, 0.11)" />
    </dependencies>

**Comment by gep13** [comment]
@phillipsj que!?!  That is VERY strange!

**Comment by gep13** [comment]
@phillipsj what version of Chocolatey are you using?
