### ISSUE TITLE
Deploying to GitHub Pages results in abuse detection mechanism kicking in

### ISSUE THREAD

**Issue by gep13** [statiqdev/Statiq#952]
When using Statiq to publish the output to GitHub pages, there are times when the following error message appears:

![image](https://user-images.githubusercontent.com/1271146/94549113-9cb66780-0249-11eb-83f3-08952f148d95.png)

And the overall deployment fails.

Due to the number of pages that are generated in the output, and the fact that OctoKit doesn't provide any mechanism to handle the back-off required by the GitHub API, results in an overall failed build.

A suggestion has been made to use an alternative pipeline module to handle the publishing of the site in a different way, but I do feel that if Statiq ships with the ability to publish to GitHub Pages that it should handle this abuse mechanism, or at least, provide a best effort.

**Comment by daveaglick** [comment]
A good discussion and some possible mitigation strategies can be found at https://github.com/octokit/octokit.net/issues/1792. Note that Octokit will not be providing any rate limiting buffer out-of-box as discussed in that issue and it's up to callers to handle rate limiting error responses as appropriate for them.

**Comment by daveaglick** [comment]
I think I've got this one resolved 🤞
