### ISSUE TITLE
Question about command line "-i" parameter after update to 1.0.0-beta.39

### ISSUE THREAD

**Issue by jermdavis** [statiqdev/Statiq#975]
When I upgrade my site's project to beta 39, I'm finding that I can no longer run the generation process if I have specified the command line parameter to pick a different input folder. I have a blog site with >250 posts which takes a while to generate. So I was using a second input folder with just the posts I was working on to allow for faster refreshes while I'm writing new content - and that's stopped working with the latest nuget package.

Before I changed the package reference to the latest version, I could supply `-i` and see both my custom folder and the theme's input folder in the input sources. Running
```
dotnet run -- preview -i "somefolder"
```
would generate my site correctly:
![image](https://user-images.githubusercontent.com/7868341/147887802-bdbfb8c5-1b92-44b2-91a5-c41046545467.png)

But after I change the package reference to the latest version, supplying `-i` causes the generation to break. Firstly I no longer see the theme folder in the inputs:
![image](https://user-images.githubusercontent.com/7868341/147887811-01ef1bcb-77ee-4e5a-aadb-e1ab0f8c8503.png)
And then generation of my site fails because it can no longer find my theme's `_layout.cshtml` file. Each page it tries to render throws an exception along the lines of:
![image](https://user-images.githubusercontent.com/7868341/147887948-9739b958-92ca-4126-b47f-e63be386831b.png)

After a bit of head-scratching, I realise I can fix this by specifying a second `-i` parameter for the theme's input folder too. Running
```
dotnet run -- preview -i "somefolder" -i "theme\input"
```
resolves the issue with the layout file.

But I'm wondering if this is a deliberate change, or a bug that's appeared recently? I couldn't see anything in the release notes for the recent [web](https://github.com/statiqdev/Statiq.Web/releases/tag/v1.0.0-beta.38) and [framework](https://github.com/statiqdev/Statiq.Framework/releases/tag/v1.0.0-beta.53) packages that seemed to match this behaviour change? I'm fairly new to the framework, so I may have misunderstood something in those notes I suppose - but I figured I should raise this in case it was a bug...

**Comment by daveaglick** [comment]
This certainly looks like a regression bug. I'm going to guess the work I did to support theme projects (which have some tricky chicken-and-egg ordering with other initialization operations) is at fault. The ordering of command line input paths and theme paths probably got mixed up. I'll take a look and publish a patch.

Thanks for reporting! Glad you found this so early too.

**Comment by jermdavis** [comment]
No problem. Thank you for your work on this project - much appreciated.

**Comment by daveaglick** [comment]
This is fixed and a new release is rolling out now (assuming some new build tooling I put in place doesn't blow up).
