### ISSUE TITLE
Visual Builder /Components, coming anytime soon

### ISSUE THREAD

**Issue by fasteddys** [statiqdev/Statiq#976]
Hello are you planning on a visual builder for components

**Comment by daveaglick** [comment]
I'm not sure I'm following...you mean a visual builder for web components? Statiq is an engine that helps generate the HTML, CSS, and other assets that comprise a web site. It doesn't generally know or care about what's _inside_ those assets though (other than being able to do some HTML manipulation, etc. to make the job of generation easier). In other words, the particular web technologies, frameworks, JavaScript, CSS, etc. that you use are mostly outside the scope of Statiq. It can help you generate and create those artifacts, and can even help interpret and use them, but it's not intended as a full content management system or all-in-one website maker outside of [themes](https://github.com/statiqdev/CleanBlog).

So I guess the answer is "no" (assuming I understood the question). Did that answer it?

**Comment by fasteddys** [comment]
Hello, I was asking there will be visual drag and drop build like `grape.js` or `vvvwebjs`. I dont need a CMS, just wondering how to quickly create ASP MVC components, partials, VC, tagHelpes etc.

I am trying to understand how to use it, and confused with the `documentation`. In the help, I saw the sample with mark down section, but I don't know how to create tables / cards / pills etc in markdown.

Or, _are you saying_ with `static`, I can take any `Bootstrap 4/5 HTML compliant site and port it/create a Razor` ready site.  If so, this would be FANTASTIC, many asp core MVC razor developers would be excited, and even contribute.

I am asking this because I saw the razor compiler classes that were built into your framework and wondering how and what do they do?

**Comment by daveaglick** [comment]
Ah, no - there are no plans to create drag-and-drop or visual GUIs for putting together Razor components, web components, or any other front-end UI elements. You're welcome to use other tools to create those and use them inside your site being generated by Statiq though.

In more general terms, Statiq is a "static generator" and it might be helpful to understand the scope of those kinds of tools. Other examples similar to Statiq include [11ty](https://www.11ty.dev) and [Hugo](https://gohugo.io). Perhaps reading about those and seeing where they have commonalities and how they compare will help things "click"
