### ISSUE TITLE
Setting custom path stopped working after updating to version 1.0.0-beta.38 .AddSetting(WebKeys.InputPaths, new List<string>() { })

### ISSUE THREAD

**Issue by Feiko** [statiqdev/Statiq#978]
I differentiate between blogs and vlogs by putting them in different directories. From version 1.0.0-beta.38 upwards, this apparently stopped working. If I put by blogs in the directory /input/posts/, I see the content being generated. 

I specify the custom directories with the following line of code in program.cs:

` .AddSetting(WebKeys.InputPaths, new List<string>() { "input", "files", "blog", "vlog" })`

I need to have the content in different directories so netlify CMS can differentiate between blogs and vlogs.

**Comment by daveaglick** [comment]
Thanks for the report - this is definitely a regression. I can repro and have a failing test, so I should be able to get this fixed up quickly.

**Comment by Feiko** [comment]
Thanks @daveaglick  looking forward to the fix.

**Comment by daveaglick** [comment]
This _should_ be resolved now and a new version has been published. Let me know if you're still having trouble after updating.

**Comment by Feiko** [comment]
This fixed the problem for me 👍. Thanks for the quick action!
