### ISSUE TITLE
Support ability to whitelist links or domains for ValidateAbsoluteLinks 

### ISSUE THREAD

**Issue by corbob** [statiqdev/Statiq#983]
It appears that some sites (like LinkedIn) implement some scraping blocking techniques that cause them to fail this validation. Would it be an idea to provide a configuration where you can list domains or just links that are exempted from the validation?

**Comment by daveaglick** [comment]
I've got it on my to-do list to document these analyzers better (and add some more while I'm at it). In this case you're in luck - you can use a `data-no-validate` attribute to turn off link validation for a particular link.

**Comment by corbob** [comment]
That does exactly what I need. Now I can run both link validations and have it not entirely break on me 😄  I'll close the issue since my issue has been solved. Feel free to reopen it if you'd like to use it for tracking adding documentation or anything like that.
