### ISSUE TITLE
Zero license links are kind of broken

### ISSUE THREAD

**Issue by kszicsillag** [statiqdev/Statiq#992]
Zero license links (https://licensezero.com/*) e.g. in [license FAQ](https://github.com/statiqdev/Statiq.Web/blob/main/LICENSE-FAQ.md) and [readme](https://github.com/statiqdev/Statiq.Web/blob/main/README.md) are all redirecting to https://artlessdevices.com/.

Cause: https://forum.artlessdevices.com/t/sic-transit-license-zero/291

As a workaround, the links could be replaced with wayback machine ones, like [this](https://web.archive.org/web/20201111232224/https://licensezero.com/).

**Comment by daveaglick** [comment]
Doh! I've had "review licenses" on my backlog for a while, guess "a while" is now. I rather like the License Zero terms, though I do wish it had some sort of "under X amount of revenue does not require a private license" term (I'm not interested in forcing very small users like blogs with ads to pay a fee, more like larger and institutional organizations). Maybe there's an alternative license out there now that's similar but with this added clause. Or perhaps I just need to copy the License Zero terms down into a local file for now.

In any case, thanks for notifying me! I'll take a look ASAP.

**Comment by daveaglick** [comment]
In the process of changing to a modified Polyform Small Business license for public use and going to keep (but copy locally) the License Zero Private license for licensees - see https://github.com/orgs/statiqdev/discussions/147

**Comment by daveaglick** [comment]
Moved all licenses to the repo and ended up crafting a Statiq Public License that combines several terms of various PolyForm licenses to make things as permissive as possible while still having a small business clause. Thanks for pointing this out and getting the ball rolling!
