### ISSUE TITLE
Link validation appears to be flagging mailto links

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq#998]
See https://github.com/orgs/statiqdev/discussions/170

**Comment by daveaglick** [comment]
Appears related to escaping, `<a href="mailto:foo@bar.com">foo</a>` passes validation while `<a href="mailto:foo&amp;#64;bar.com">foo</a>` fails.

**Comment by daveaglick** [comment]
This is now resolved by HTML unescaping links to be analyzed. Might also address #997, but still need to verify.

**Comment by girlpunk** [comment]
Any chance of getting a new release so this is available?

**Comment by daveaglick** [comment]
@girlpunk Ha! I maybe kinda sorta forgot that this wasn't already released 😬. That's what happens when you get completely swamped for like 6 months. Pushing out a set of new packages now.
